### ISSUE TITLE
[App]: Hovering over points in embedding projection yields seemingly random images from the table

### ISSUE THREAD

**Issue by Telcrome** [wandb/wandb#3480] opened 2022-04-06 10:39 UTC
### Current Behavior

see title and the video

https://user-images.githubusercontent.com/4445277/161956927-5150133f-a579-454e-932a-643cb36a81f7.mp4

### Expected Behavior

A single point should be associated with a single image from the table

### Environment

OS: 

Browsers: MS Edge

Version:

**Comment by ramit-wandb** [comment] 2022-04-06 19:19
Hi @Telcrome,

This definitely looks like a bug on our end. Thank you for reporting this. I'm going to escalate this to our engineering team to have this resolved, and I'll keep you updated on the status of this issue.

Thanks,
Ramit

**Comment by Telcrome** [comment] 2022-04-06 19:21
Great! Let me know if you need help replicating the issue. @ramit-wandb

**Comment by ramit-wandb** [comment] 2022-04-08 18:51
Yes that would definitely be helpful! It will accelerate the pace at which this issue will be resolved. A reproduction to this would certainly help.

Thanks,
Ramit

**Comment by Telcrome** [comment] 2022-04-08 22:02
I can reproduce the problem already with the most simple case I can think of:

`import wandb
import skimage.data as demodata
import numpy as np
wandb.init()
t = wandb.Table(columns=['image', 'embedding'])
t.add_data(
    wandb.Image(demodata.cell()),
    np.random.rand(5)
)
t.add_data(
    wandb.Image(demodata.retina()),
    np.random.rand(5)
)
wandb.log({"sometable": t})`

**Comment by thanos-wandb** [comment] 2024-10-15 09:32
Hi @Telcrome just wanted to let you know that this issue with the images in the embeddings projector has been resolved, therefore we are now closing this issue. Please let us know if you are still encountering this error, and we will be more than happy to keep investigating. Thank you for reporting it, and have a great day!

**Closed by thanos-wandb** 2024-10-15 09:32 UTC
Labels: a:app
