### ISSUE TITLE
wandb tox -e py39 stuck in aarch64

### ISSUE THREAD

**Issue by pengyueqingthink** [wandb/wandb#5752] opened 2023-06-20 12:16 UTC
When I tested it, it got stuck near the end.what is the wrong?
Here is `tox -e py39` output
```
.pkg: _optional_hooks> python /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.9.2-2swlaszukyrl563ldkngbppxqi7733x6/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: get_requires_for_build_sdist> python /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.9.2-2swlaszukyrl563ldkngbppxqi7733x6/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: prepare_metadata_for_build_wheel> python /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.9.2-2swlaszukyrl563ldkngbppxqi7733x6/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
.pkg: build_sdist> python /home/spack/opt/spack/linux-centos8-aarch64/gcc-8.5.0/python-3.9.2-2swlaszukyrl563ldkngbppxqi7733x6/lib/python3.9/site-packages/pyproject_api/_backend.py True setuptools.build_meta
py39: install_package> pip install --timeout 600 --extra-index-url https://download.pytorch.org/whl/cpu --force-reinstall --no-deps /home/stage/root/spack-stage-py-wandb-master-khbj7y7fqyrbsjmvamuside7t6vfr3h4/spack-src/.tox/.tmp/package/12/wandb-0.15.5.dev1.tar.gz
py39: commands[0]> mkdir -p test-results
py39: commands[1]> pytest -n=10 --durations=20 --reruns 3 --reruns-delay 1 --junitxml=test-results/junit.xml --cov-config=.coveragerc --cov --cov-report= --no-cov-on-fail --timeout 300 tests/pytest_tests/
/home/stage/root/spack-stage-py-wandb-master-khbj7y7fqyrbsjmvamuside7t6vfr3h4/spack-src/.tox/py39/lib/python3.9/site-packages/pytest_benchmark/logger.py:46: PytestBenchmarkWarning: Benchmarks are automatically disabled because xdist plugin is active.Benchmarks cannot be performed reliably in a parallelized environment.
  warner(PytestBenchmarkWarning(text))
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.2, pytest-7.3.2, pluggy-1.0.0 -- /home/stage/root/spack-stage-py-wandb-master-khbj7y7fqyrbsjmvamuside7t6vfr3h4/spack-src/.tox/py39/bin/python
cachedir: .tox/py39/.pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/stage/root/spack-stage-py-wandb-master-khbj7y7fqyrbsjmvamuside7t6vfr3h4/spack-src/.hypothesis/examples')
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/stage/root/spack-stage-py-wandb-master-khbj7y7fqyrbsjmvamuside7t6vfr3h4/spack-src
configfile: pytest.ini
plugins: pyfakefs-5.2.2, hypothesis-6.78.2, anyio-3.7.0, xdist-3.3.1, timeout-2.1.0, split-0.8.1, rerunfailures-11.1.2, openfiles-0.5.0, mock-3.10.0, flakefinder-1.1.0, cov-4.1.0, benchmark-4.0.0, flask-1.2.0, respx-0.20.1
timeout: 300.0s
timeout method: signal
timeout func_only: False
10 workers [2232 items] errors
scheduling tests via LoadScheduling

tests/pytest_tests/system_tests/test_core/test_metric_full.py::test_metric_glob_none
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestReports::test_set_blocks[block22]
tests/pytest_tests/system_tests/test_artifacts/test_artifact_saver.py::test_calls_commit_on_success
tests/pytest_tests/system_tests/test_artifacts/test_wandb_artifacts.py::test_deduplicate_wbimagemask_from_array
tests/pytest_tests/system_tests/test_core/test_data_types_full.py::test_joined_table_logging
tests/pytest_tests/system_tests/test_core/test_public_api.py::test_from_path_report_type[test/test/reports/Name-foo--XYZ]
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestPanelGrids::test_append_panels
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestNameMappings::test_special_mappings[metric-config:metric]
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestValidators::test_one_of_validator[options2-abc-fail]
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestBlocks::test_code_block[None-x = np.random.randint(0, 10, size=(10, 10))]
[gw7] [  0%] XFAIL tests/pytest_tests/system_tests/test_core/test_report_api.py::TestNameMappings::test_special_mappings[metric-config:metric]
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestNameMappings::test_special_mappings[metric.with.dots-config:metric.value.with.dots]
[gw7] [  0%] XFAIL tests/pytest_tests/system_tests/test_core/test_report_api.py::TestNameMappings::test_special_mappings[metric.with.dots-config:metric.value.with.dots]
tests/pytest_tests/system_tests/test_core/test_report_api.py::TestNameMappings::test_special_mappings[s::metric-summary:metric]
[gw2] [  0%] RERUN tests/pytest_tests/system_tests/test_core/test_data_types_full.py::test_joined_table_logging
[gw5] [  0%] RERUN tests/pytest_tests/system_tests/test_core/test_report_api.py::TestReports::test_set_blocks[block22]
[gw4] [  0%] RERUN tests/pytest_tests/system_tests/test_core/test_public_api.py::test_from_path_report_type[test/test/reports/Name-foo--XYZ]
... Omit part of the output ...
[gw8] [ 98%] RERUN tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_set_item
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_set_item
[gw8] [ 98%] FAILED tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_set_item
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
[gw8] [ 98%] RERUN tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
[gw8] [ 98%] RERUN tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
[gw8] [ 98%] RERUN tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
[gw8] [ 98%] FAILED tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_wandb_artifact_config_update
tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_repo_job_creation
[gw8] [ 98%] PASSED tests/pytest_tests/unit_tests_old/test_wandb_run.py::test_repo_job_creation
```

wandb version: master
os system: centos8

**Comment by sydholl** [comment] 2023-06-23 17:06
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by pengyueqingthink** [comment] 2023-06-25 07:13
The error message is not printed because the test is not finished.

**Comment by rsanandres-wandb** [comment] 2023-06-29 17:30
Could you try restarting the test and let me know if there is an output? The output should be outputted to your terminal when you ran `tox -e py39`.

On top of that, could you let me know the following after you try to rerun it:
- The exact error messages from the failed tests.
- The version of wandb you're testing (you mentioned master, but including the specific commit hash could be helpful).
- The version of Python you're using.

**Comment by pengyueqingthink** [comment] 2023-06-30 09:07
The previous test environment and test data were deleted, and I'll run it again later.

**Comment by rsanandres-wandb** [comment] 2023-07-05 19:58
Sounds good! I will close this ticket for now but feel free to respond once you are able to reproduce this and it will reopen the ticket.

**Closed** 2024-04-12 23:10 UTC
