### ISSUE TITLE
"Circular reference detected" error when updating metadata with numpy array longer than 32 elements

### ISSUE THREAD

**Issue by avm19** [wandb/wandb#2994] opened 2021-12-07 00:21 UTC
The error occurs on `save()` method when `metadata` dictionary of a model Artifact is updated with a `numpy.array` of length >32 as the dictionary's value. The following code reproduces the error. For the error message and the package versions **scroll down** to the end.
```
wandb.init();
A = np.array([0]*33) 
wandb_model = wandb.Artifact(name='model1', type='model')
wandb_model.metadata.update(A=A)
wandb.log_artifact(wandb_model)
wandb_model.wait().metadata.update(A=A)
wandb_model.save() #ERROR!
```
The error occurs only when saving the artifact with updated metadata. The error does _not_ occur if `np.array` is 32 elements or shorter. The error does _not_ occur if the problematic value is removed from `wandb_mode.metadata` before saving, e.g. by calling `metadata.clear()`.

**Known workaround**: convert `numpy.array` to `list` before putting it into the Artifact's metadata.

Here is the error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     23         try:
---> 24             return func(*args, **kwargs)
     25         except requests.HTTPError as err:

/opt/conda/lib/python3.7/site-packages/wandb/apis/public.py in save(self)
   3900                 "description": self.description,
-> 3901                 "metadata": util.json_dumps_safer(self.metadata),
   3902                 "aliases": [

/opt/conda/lib/python3.7/site-packages/wandb/util.py in json_dumps_safer(obj, **kwargs)
    749     """Convert obj to json, with some extra encodable types."""
--> 750     return json.dumps(obj, cls=WandBJSONEncoder, **kwargs)
    751 

/opt/conda/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 

/opt/conda/lib/python3.7/json/encoder.py in encode(self, o)
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):

/opt/conda/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 

ValueError: Circular reference detected

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
/tmp/ipykernel_34/339382067.py in <module>
      4 wandb.log_artifact(wandb_model)
      5 wandb_model.wait().metadata.update(A=A)
----> 6 wandb_model.save()

/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_artifacts.py in save(self, project, settings)
    600 
    601         if self._logged_artifact:
--> 602             return self._logged_artifact.save()
    603         else:
    604             if wandb.run is None:

/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_run.py in save(self)
   3015 
   3016     def save(self) -> None:
-> 3017         return self._assert_instance().save()
   3018 
   3019     def delete(self) -> None:

/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     60                 six.reraise(*sys.exc_info())
     61             else:
---> 62                 six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
     63 
     64     return wrapper

/opt/conda/lib/python3.7/site-packages/six.py in reraise(tp, value, tb)
    716                 value = tp()
    717             if value.__traceback__ is not tb:
--> 718                 raise value.with_traceback(tb)
    719             raise value
    720         finally:

/opt/conda/lib/python3.7/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     22         message = "Whoa, you found a bug."
     23         try:
---> 24             return func(*args, **kwargs)
     25         except requests.HTTPError as err:
     26             raise CommError(err.response, err)

/opt/conda/lib/python3.7/site-packages/wandb/apis/public.py in save(self)
   3899                 "artifactID": self.id,
   3900                 "description": self.description,
-> 3901                 "metadata": util.json_dumps_safer(self.metadata),
   3902                 "aliases": [
   3903                     {"artifactCollectionName": self._sequence_name, "alias": alias,}

/opt/conda/lib/python3.7/site-packages/wandb/util.py in json_dumps_safer(obj, **kwargs)
    748 def json_dumps_safer(obj, **kwargs):
    749     """Convert obj to json, with some extra encodable types."""
--> 750     return json.dumps(obj, cls=WandBJSONEncoder, **kwargs)
    751 
    752 

/opt/conda/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

/opt/conda/lib/python3.7/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/opt/conda/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

CommError: Circular reference detected
```
The system configuration is the current Kaggle kernel environment with Weights and Biases manually updated:
`assert wandb.__version__ == '0.12.7'`
```
System:
    python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53)  [GCC 9.4.0]
executable: /opt/conda/bin/python
   machine: Linux-5.10.68+-x86_64-with-debian-bullseye-sid

Python dependencies:
          pip: 21.3.1
   setuptools: 59.1.1
      sklearn: 0.23.2
        numpy: 1.19.5
        scipy: 1.7.2
       Cython: 0.29.24
       pandas: 1.3.4
   matplotlib: 3.5.0
       joblib: 1.1.0
threadpoolctl: 3.0.0

Built with OpenMP: True
```

**Comment by avm19** [comment] 2021-12-07 00:32
P.S. I have a feeling that this is a new behaviour, which did not take place until a couple of days ago and which may be caused by updates in the environment. Those who will be fixing it might find it used looking into the updated dependencies. Compare v107 to v106 of the Kaggle Docker images at https://github.com/Kaggle/docker-python/releases .

**Comment by ash0ts** [comment] 2022-01-03 17:22
Hello @avm19, Thank you for bringing attention to this issue for us. Our engineers have been made aware and are looking into it. We will let you know when we have an update

**Comment by Dobatymo** [comment] 2022-08-05 04:38
I have got the same issue with `wandb==0.13.0` for many tables I want to log with `wandb.log({"name": wandb.Table(dataframe=df)})`.

**Comment by wesg52** [comment] 2022-08-28 21:02
I also got the error when logging a table which contains a `torch.long`.

`wandb==0.13.2`

**Comment by anmolmann** [comment] 2022-11-03 22:46
@wesg52 , @Dobatymo , @avm19 : this issue has been fixed in [our latest wandb sdk release](https://github.com/wandb/wandb/releases/tag/v0.13.5). Please let us know if you still encounter this issue.

**Comment by drscotthawley** [comment] 2024-05-07 15:32
Seeing this error today, in 2024. Very unclear what could be causing it. Any way to get wandb to tell us what the offending 'circular reference was'?  It's not appearing in the Traceback.

**Comment by frotaur** [comment] 2024-10-27 20:31
Can confirm just got this error when trying to log a table containing tensors of ints.

**Comment by kptkin** [comment] 2024-10-28 19:10
@drscotthawley @frotaur probably the easiest way to help us understand what's going on, is if you could provide a (short) reproduction with the latest version. Thanks and sorry for the inconvenience

**Comment by sydholl** [comment] 2024-11-26 01:55
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Closed by sydholl** 2024-11-26 01:55 UTC
Labels: ty:bug, c:artifacts
