### ISSUE TITLE
[CLI]: Summary is overwriten fromProcess with same run

### ISSUE THREAD

**Issue by mova** [wandb/wandb#4882] opened 2023-02-01 14:47 UTC
### Describe the bug

Sometimes I have a testing process running, while the model is still training in another process on another node. 
I use the following code the update the metrics:
```python
wandb.log(metrics_dict | {"epoch": epoch}, step=step)
for k, v in metrics_dict.items():
    wandb_run.summary[k] = v
```
It seems like everything works correctly:
```shell
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run summary:
...
wandb:         test/best/fpnd 1.5672
wandb:        test/best/w1efp 1.63295
wandb:          test/best/w1m 3.17476
wandb:          test/best/w1p 1.62787
...
wandb: 🚀 View run a9c7033 at: https://wandb.ai/hamgen/jetnet5/runs/vvsvds2q
wandb: Synced 3 W&B file(s), 20 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: wd/dbl_numpar_q_ext0/a9c7033/wandb/run-20230201_151428-vvsvds2q/logs
```
But if we look into the run summary these metrics are not updated:
![2023-02-01-153500_1920x1177_scrot](https://user-images.githubusercontent.com/779688/216072235-36e7f7ee-113c-4ce9-ae84-9cc89614e143.png)
Also eg. `test/best/fpnd` is not available as a metric in the panels.

### Additional Files

[run.zip](https://github.com/wandb/wandb/files/10558147/run.zip)

### Environment

WandB version: 0.13.9

OS: CentOSLinux7

Python version: 3.9.13

Versions of relevant libraries:

**Comment by mova** [comment] 2023-03-06 13:59
Sorry for the very late response.
`setup.py`
```python
import wandb
run = wandb.init(
    project="overwrite_error",
    name="run",
    resume=False,
)
with open("run_id.txt", "w") as f:
    f.write(run.id)
```
`train.py`
```python
import wandb
import numpy as np
from time import sleep

with open("run_id.txt", "r") as f:
    run_id = f.read()

run = wandb.init(
    id=run_id,
    resume="must",
    project="overwrite_error",
    job_type="train",
)

for _ in range(100):
    run.log({"loss": np.random.rand()})
    sleep(1)
```
`test.py`
```python
import wandb
import numpy as np
with open("run_id.txt", "r") as f:
    run_id = f.read()
run = wandb.init(
    id=run_id,
    resume="must",
    project="overwrite_error",
    job_type="test",
)
run.summary["test"] = np.random.rand()
```
If I run `test.py` while the training is still running, the "test" value in the summary disappears.
See https://wandb.ai/hamgen/overwrite_error/runs/7h3k1tsw/

Cheers!

**Comment by mova** [comment] 2023-03-14 15:53
Hey,
sorry, the problem persists.
This run has been running wandb 0.13.11 (from conda) and I cannot see the plots in `val/unscaled` at step 0:
https://wandb.ai/hamgen/jetnet_discdeeptree/runs/zz7bt6bo

**Comment by mova** [comment] 2023-03-14 15:59
I just noticed that in 
`wandb/run-20230314_122823-zz7bt6bo/files/media/images/val/unscaled/` the files are named like this:
`2dhist_etarel_vs_ptrel.pdf_40000_69c7cbda593b240d2ed0.png`
`2dhist_etarel_vs_ptrel.pdf_20000_7f2813ea3bfc9df53c4f.png`
`2dhist_etarel_vs_ptrel.pdf_1_bd3d7130c6d945fe44cf.png`
So the file for step `0`  as a `1` in the filename.

**Comment by billmdevs** [comment] 2023-03-14 19:26
Alright! Could you please share with me the debug logs of the run you just tried?

**Comment by mova** [comment] 2023-03-14 22:16
[wandb_step0_error.zip](https://github.com/wandb/wandb/files/10974321/wandb_step0_error.zip)

**Comment by ramit-wandb** [comment] 2023-04-18 23:22
Hey @mova,

I'll be handling this request from here on out - I noticed you are running `train.py` when you initialize `test.py`. Is there a reason you are using the same run ID for both? This is usually not recommended and might be the root cause of the error. A better approach would be to `group` the runs relating to the same model together and not using the `id`. Eg:

In `train.py`:
```python3
run = wandb.init(job_type = 'train', group=GROUP_ID)
```

In `test.py`:
```python3
run = wandb.init(job_type = 'train', group=GROUP_ID)
```

Where you can use `setup.py` to create a group ID

**Comment by mova** [comment] 2023-04-19 11:58
Hi,
I guess this would lead to a new https://wandb.ai/user/<project>/runs/<runid> every time one of my training gets restartet, right? So then I cannot inspect a single training any more, right?

**Comment by ramit-wandb** [comment] 2023-04-24 17:16
Hey @mova I wanted to check in if there is anything else we can help with. Please let us know if we can be of further assistance.

**Comment by mova** [comment] 2023-04-24 17:23
Hey, 
sorry, i didnt get around to fully test the new procedure, I'll try to do that this week and report back.

**Comment by ramit-wandb** [comment] 2023-04-24 17:48
Sure thing! Thanks for letting me know :)

**Comment by ramit-wandb** [comment] 2023-04-28 20:54
Hi @mova,

Since there has not been much movement on this issue, I'll be closing it out for now. In case the solutions above do not work, please feel free to reopen this issue and I will be happy to assist you with getting this to work for you!

**Closed by ramit-wandb** 2023-04-28 20:54 UTC
Labels: cli, c:rewind, c:summary
