### ISSUE TITLE
[Q]Why  these curves have  different number of data points?

### ISSUE THREAD

**Issue by zyw19970608** [wandb/wandb#4175] opened 2022-08-25 05:47 UTC
![image](https://user-images.githubusercontent.com/49807276/186584164-84d5435c-1ecb-4b0d-b715-5b80be18942b.png)
Why  these curves have  different number of data points?
Instead of using "step" as X axis, I use the "update"  to play the role of X axis.
Now, I found that after the same update nums, different curves sample different num of data points, this problem makes my picture looks ugly, how can I deal with it?

**Comment by AlirezaAzadbakht** [comment] 2022-08-25 06:33
My plots were doing fine yesterday and today they are facing a similar problem, I think it's a problem on wandb's frontend side.

**Comment by AlbertoPresta** [comment] 2022-08-25 06:56
I have the same problem, until yesterday the plots were perfect, today they look like this: 
<img width="843" alt="Schermata 2022-08-25 alle 08 55 52" src="https://user-images.githubusercontent.com/43781044/186596046-4299349a-36bf-4583-a96d-ca209c4d81a7.png">

**Comment by AlbertoPresta** [comment] 2022-08-25 07:01
I have the same problem! until yesterday my plots work, now they look like this: 

<img width="843" alt="Schermata 2022-08-25 alle 08 55 52" src="https://user-images.githubusercontent.com/43781044/186597106-6cc13762-eedb-4f41-8a83-b18ec69fe785.png">

**Comment by zyw19970608** [comment] 2022-08-25 07:06
> My plots were doing fine yesterday and today they are facing a similar problem, I think it's a problem on wandb's frontend.
 

> I have the same problem! until yesterday my plots work, now they look like this:
> 
> <img alt="Schermata 2022-08-25 alle 08 55 52" width="843" src="https://user-images.githubusercontent.com/43781044/186597106-6cc13762-eedb-4f41-8a83-b18ec69fe785.png">
My plot was pretty good before, but as the data grew, it became stiff. It may some trouble of the wandb.

**Comment by zyw19970608** [comment] 2022-08-25 07:07
> My plots were doing fine yesterday and today they are facing a similar problem, I think it's a problem on wandb's frontend. ![image](https://user-images.githubusercontent.com/30026056/186592252-63257fd3-4d61-4bfd-aa2b-89f130366b05.png)

I even would like to use matplotlib instead

**Comment by fdsig** [comment] 2022-08-25 11:47
Hey @zyw19970608,

Thanks so much for reporting this and apologies for the UI performance. We have looked at this as a matter of urgency. This should have been fixed now.😊

Please let us know if this issue persists for you. 
 

Best wishes W&B Team.

**Comment by fdsig** [comment] 2022-08-26 11:39
Hey @zyw19970608, I will go ahead and close this off unless you still need further help/ are still experiencing UI plot/data point issues.

**Comment by zyw19970608** [comment] 2022-10-12 07:01
> Hey @zyw19970608, I will go ahead and close this off unless you still need further help/ are still experiencing UI plot/data point issues.

I meet this problem again, why this problem already exsit? It seems really strange....
![image](https://user-images.githubusercontent.com/49807276/195272578-13c6eb49-4d2b-4684-a8e8-da427de9fa03.png)

**Comment by sydholl** [comment] 2024-11-18 21:02
We are closing this issue due to inactivity. If you feel this bug merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Closed by sydholl** 2024-11-18 21:02 UTC
Labels: a:app
