### ISSUE TITLE
wandb.init fails with error `module 'psutil' has no attribute 'pid_exists'`

### ISSUE THREAD

**Issue by dyhan316** [wandb/wandb#6305] opened 2023-09-17 12:53 UTC
### Describe the bug

When I try to do wandb, it gives me a "pid not found in psutil" error

```python
>>> import wandb
>>> run = wandb.init(
...     # Set the project where this run will be logged
...     project="my-awesome-project",
...     # Track hyperparameters and run metadata
...     config={
...         "learning_rate": 0.01,
...         "epochs": 10,
...     })
```

```shell
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 279, in service
    server.serve()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
    mux.loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 427, in loop
    raise e
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 425, in loop
    self._loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 411, in _loop
    if self._check_orphaned():
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 407, in _check_orphaned
    return not psutil.pid_exists(self._pid)
AttributeError: module 'psutil' has no attribute 'pid_exists'

```

### Environment

WandB version: wandb                     0.15.10                  pypi_0    pypi

OS: Linux

Python version: python                    3.10.4               h12debd9_0  

Versions of relevant libraries: psutil                    5.9.5                    pypi_0    pypi

### Additional Context

It worked well a few days ago.

**Comment by thanos-wandb** [comment] 2023-09-19 09:10
Hi @dyhan316 thanks for reporting this issue. Was it working fine before with same wandb version? and did you upgrade any other package? may I please ask what's your current `psutil` version? and could you please send the `debug.log` and `debug-internal.log` file from this failed run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

**Comment by dyhan316** [comment] 2023-09-19 12:53
@thanos-wandb  thank you for the reply!

Yes, it did work and I did not upgrade anything. The  version of `psutil` is `psutil 5.9.5 pypi_0 pypi`. 

Below is the error code (I did keyboard interrupt because exit() wouldn't stop)
```
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb 
>>> a = wandb.init(project='hi')
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 279, in service
    server.serve()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
    mux.loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 427, in loop
    raise e
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 425, in loop
    self._loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 411, in _loop
    if self._check_orphaned():
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 407, in _check_orphaned
    return not psutil.pid_exists(self._pid)
AttributeError: module 'psutil' has no attribute 'pid_exists'
wandb: Currently logged in as: dyhan316 (cl_mri). Use `wandb login --relogin` to force relogin
Problem at: <stdin> 1 <module>t()...
wandb: ERROR Run initialization has timed out after 90.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    raise e
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
>>> exit()
^CException ignored in atexit callback: <function _Manager._atexit_setup.<locals>.<lambda> at 0x2afaa11b9090>
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 155, in <lambda>
    self._atexit_lambda = lambda: self._atexit_teardown()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 164, in _atexit_teardown
    self._teardown(exit_code)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 175, in _teardown
    result = self._service.join()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 258, in join
    ret = self._internal_proc.wait()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt: 
```

and here is the wandb.log

```
(CL_MRI) 2657% [x2519a02@skl02 logs]$ cat debug.log 
2023-09-19 21:40:01,101 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Configure stats pid to 98955
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from /home01/x2519a02/.config/wandb/settings
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from /scratch/x2519a02/wandb/settings
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_init.py:_log_setup():524] Logging user logs to /scratch/x2519a02/wandb/run-20230919_214001-mhx2jw7t/logs/debug.log
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_init.py:_log_setup():525] Logging internal logs to /scratch/x2519a02/wandb/run-20230919_214001-mhx2jw7t/logs/debug-internal.log
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():564] calling init triggers
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():614] starting backend
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():618] setting up manager
2023-09-19 21:40:01,108 INFO    MainThread:98955 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-19 21:40:01,110 INFO    MainThread:98955 [wandb_init.py:init():624] backend started and connected
2023-09-19 21:40:01,115 INFO    MainThread:98955 [wandb_init.py:init():715] updated telemetry
2023-09-19 21:40:01,119 INFO    MainThread:98955 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-09-19 21:41:31,303 ERROR   MainThread:98955 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-19 21:41:31,447 ERROR   MainThread:98955 [wandb_init.py:init():1183] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
```

**Comment by thanos-wandb** [comment] 2023-09-21 11:12
Hi @dyhan316 thanks for the additional information. It seems that `wandb.init()` call time outs. Are you connected to the internet, and do you change anything in your network configuration, eg proxy? 

Could you please make sure that you're logged in CLI as such: `wandb login --relogin`? alternatively, you could do `wandb.login(key='api-key')` in your python script but that's not recommended to be committed in a git repository.

**Comment by sydholl** [comment] 2023-09-22 15:26
WandB Internal User commented: 
thanos-wandb commented: 
Hi @dyhan316 thanks for reporting this issue. Was it working fine before with same wandb version? and did you upgrade any other package? may I please ask what's your current `psutil` version? and could you please send the `debug.log` and `debug-internal.log` file from this failed run? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

**Comment by sydholl** [comment] 2023-09-22 15:26
WandB Internal User commented: 
dyhan316 commented: 
@thanos-wandb  thank you for the reply!

Yes, it did work and I did not upgrade anything. The  version of `psutil` is `psutil 5.9.5 pypi_0 pypi`. 

Below is the error code (I did keyboard interrupt because exit() wouldn't stop)
```
Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb 
>>> a = wandb.init(project='hi')
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/cli/cli.py", line 279, in service
    server.serve()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/server.py", line 118, in serve
    mux.loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 427, in loop
    raise e
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 425, in loop
    self._loop()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 411, in _loop
    if self._check_orphaned():
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/streams.py", line 407, in _check_orphaned
    return not psutil.pid_exists(self._pid)
AttributeError: module 'psutil' has no attribute 'pid_exists'
wandb: Currently logged in as: dyhan316 (cl_mri). Use `wandb login --relogin` to force relogin
Problem at: <stdin> 1 <module>t()...
wandb: ERROR Run initialization has timed out after 90.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1184, in init
    raise e
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
>>> exit()
^CException ignored in atexit callback: <function _Manager._atexit_setup.<locals>.<lambda> at 0x2afaa11b9090>
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 155, in <lambda>
    self._atexit_lambda = lambda: self._atexit_teardown()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 164, in _atexit_teardown
    self._teardown(exit_code)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 175, in _teardown
    result = self._service.join()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/service/service.py", line 258, in join
    ret = self._internal_proc.wait()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1204, in wait
    return self._wait(timeout=timeout)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1938, in _wait
    (pid, sts) = self._try_wait(0)
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/subprocess.py", line 1896, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt: 
```

and here is the wandb.log

```
(CL_MRI) 2657% [x2519a02@skl02 logs]$ cat debug.log 
2023-09-19 21:40:01,101 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Configure stats pid to 98955
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from /home01/x2519a02/.config/wandb/settings
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from /scratch/x2519a02/wandb/settings
2023-09-19 21:40:01,102 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_init.py:_log_setup():524] Logging user logs to /scratch/x2519a02/wandb/run-20230919_214001-mhx2jw7t/logs/debug.log
2023-09-19 21:40:01,103 INFO    MainThread:98955 [wandb_init.py:_log_setup():525] Logging internal logs to /scratch/x2519a02/wandb/run-20230919_214001-mhx2jw7t/logs/debug-internal.log
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():564] calling init triggers
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():614] starting backend
2023-09-19 21:40:01,104 INFO    MainThread:98955 [wandb_init.py:init():618] setting up manager
2023-09-19 21:40:01,108 INFO    MainThread:98955 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-09-19 21:40:01,110 INFO    MainThread:98955 [wandb_init.py:init():624] backend started and connected
2023-09-19 21:40:01,115 INFO    MainThread:98955 [wandb_init.py:init():715] updated telemetry
2023-09-19 21:40:01,119 INFO    MainThread:98955 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-09-19 21:41:31,303 ERROR   MainThread:98955 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-09-19 21:41:31,447 ERROR   MainThread:98955 [wandb_init.py:init():1183] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1165, in init
    run = wi.init()
  File "/scratch/x2519a02/.conda/envs/CL_MRI/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
```

**Comment by sydholl** [comment] 2023-09-22 15:26
Artsiom Skarakhod commented: 
Request #51874 "[SDK] wandb init doesn't work (u..." was closed and merged into this request. Last comment in request #51874:

Hi Danny,

I see that this is a duplicate of the thread you are having with my teammate Thanos. Therefore I will close and merge this thread into the one where Thanos is helping you out.

Warmly,
Artsiom

**Comment by thanos-wandb** [comment] 2023-09-25 13:09
Hi @dyhan316 We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Closed** 2023-09-27 15:09 UTC
Labels: cli

**Comment by Li-Ao-Git** [comment] 2024-01-08 07:42
replace pip with conda
uninstall the current version with `pip uninstall psutil`
install with conda `conda install psutil`
this is worked for me.
