### ISSUE TITLE
[CLI]: Random tmp files being made -- why?

### ISSUE THREAD

**Issue by brando90** [wandb/wandb#4535] opened 2022-11-24 19:16 UTC
### Describe the bug

I have a million tmp files due to wandb on my home folder. I don't know why. Why are they being created & how do I stop it?
```
anaconda					   tmpa0wf77f_wandb-artifacts  tmpmv2ewoi1wandb-media
anaconda.sh					   tmpa3t655lewandb-media      tmpmvhp3i6ewandb-media
data						   tmpa6roiz80wandb	       tmpmwszwea4
debug-cli.brando9.log				   tmpal7kticfwandb-artifacts  tmpn0p49w1hwandb-media
diversity-for-predictive-success-of-meta-learning  tmpalsnd4g1wandb-media      tmpnbxtnojbwandb-artifacts
div_install_miniconda				   tmpambb3rm9wandb-artifacts  tmpngpy96dawandb-artifacts
div_install.out					   tmpapco0xetwandb-media      tmpnqezeggnwandb-media
iit-term-synthesis				   tmpaqf80v_hwandb-media      tmpo3cug5nzwandb-media
main.sh.e449240					   tmpaqigpze6wandb-artifacts  tmpoc4x6l22wandb
main.sh.e457075					   tmpaw1kvgtgwandb-media      tmpofql583uwandb-media
main.sh.e760266					   tmpay63rbxgwandb-media      tmponqiggzswandb-artifacts
main.sh.err748250				   tmpb2clycf5		       tmpoqem6uclwandb-media
main.sh.err849450				   tmpbbrfn_kmwandb-artifacts  tmpoqth0mgpwandb-media
main.sh.err923818				   tmpbcxatqdiwandb-artifacts  tmppbd5bfm_wandb
main.sh.err962904				   tmpbgewkz10wandb	       tmppbnpm41gwandb-media
main.sh.o449240					   tmpbsd96o99wandb-media      tmppwxmebn1
main.sh.o457075					   tmpbtlp8zomwandb	       tmpq396kfo1wandb-artifacts
main.sh.o748250					   tmpby3a9u8ywandb	       tmpq8jryat0wandb-media
main.sh.o760266					   tmpc45e2nlxwandb-media      tmpqc65bfs0wandb
main.sh.o849450					   tmpc4m5b21_		       tmpqexdhp6gwandb-artifacts
main.sh.o923818					   tmpcap20jmdwandb-media      tmpqh3uu7v2wandb-media
main.sh.o950686					   tmpcl2sb6j_wandb	       tmpqh99a72vwandb-media
main.sh.o962904					   tmpcsncx8x4wandb-media      tmpqmim4sxywandb
miniconda					   tmpd7dhluxmwandb	       tmpqpfcq9uwwandb
miniconda.sh					   tmpdbbb3hw_wandb-artifacts  tmpqtds4jdiwandb-artifacts
nohup.out					   tmpdfrjyk90wandb-media      tmp_qz8pu0xwandb-artifacts
nohup.out449240					   tmpdhqwaxygwandb	       tmpr98qj7auwandb
nohup.out457075					   tmpdpj3bfz0wandb-artifacts  tmprfwooa22wandb-artifacts
nohup.out760266					   tmpdqzzy7v3		       tmpri9xu8i_wandb-media
pycoq						   tmpdr6fbpctwandb	       tmprj4g0kkhwandb
test.py						   tmpejwo7axlwandb	       tmp_rla0cb9wandb-media
tmp						   tmpekqp7b2dwandb-media      tmprmrasn0fwandb-media
tmp03kmjan0wandb				   tmpf3pk0_3t		       tmpr_yrhzj_wandb
tmp07zhon11wandb-media				   tmpf4w8yhsswandb-media      tmprzxltg0lwandb
tmp0pkwjwg8wandb				   tmpf_6vd6hkwandb-media      tmps0beul64wandb-media
tmp0ypuhnktwandb-media				   tmpf7vuwlipwandb	       tmps5qf0_w0wandb
tmp0zk3_ok1wandb				   tmpfc8ltujrwandb-media      tmpsp2djjg6wandb-artifacts
tmp14xa24j_wandb				   tmpfmcmwgb8		       tmpsqe0vylnwandb
tmp1f3gqdq1wandb-media				   tmpfqhl6c9vwandb	       tmpstniop3twandb-media
tmp1hmrx3xnwandb				   tmpfvkvyklpwandb-media      tmpsv3n4fi7wandb-media
tmp1nxq8dmowandb				   tmpfxuc2zwjwandb-artifacts  tmp_t3mkuy4
tmp1r2xah97wandb-media				   tmpg051c49z		       tmptb0urf26wandb
tmp1sdb3vnqwandb-media				   tmpg16e6zpxwandb-media      tmptgq1h308wandb-media
tmp1wq9i7tmwandb-media				   tmpg2qfjo5pwandb-artifacts  tmpthtghn1wwandb-media
tmp27k3evykwandb-artifacts			   tmpg34wt2g1wandb-media      tmptkp9qpgxwandb-media
tmp2ncmg9jmwandb-media				   tmpggaltim9wandb-media      tmptqn9w7rawandb-artifacts
tmp2qxmugpjwandb-media				   tmpgj6gyqw6wandb-media      tmptsqb0lwrwandb
tmp2w92xlzowandb				   tmpgpv_1hxk		       tmptub9i1zzwandb-media
tmp39lds7tywandb-media				   tmpgswv7jpn		       tmpu0k6cuycwandb-media
tmp3ncj9tdewandb-artifacts			   tmpgvz0_o1h		       tmpu6uv_y0pwandb
tmp3qlpfrylwandb-media				   tmpgyarr2jxwandb	       tmpumz7hmaiwandb-artifacts
tmp3snbanfnwandb				   tmph6m9dpa_wandb	       tmpun08cdmwwandb-artifacts
tmp3xrxd920wandb-artifacts			   tmph8n3b36swandb-media      tmp_uqnbz5n
tmp3zmnx6jxwandb-artifacts			   tmphddkq3_3wandb	       tmpurv7_fe2wandb
tmp4103eum2wandb				   tmphmva83y4wandb	       tmpuwoxzzfvwandb-media
tmp421qmhu3wandb				   tmphs6erdxrwandb-media      tmpvb5bk2js
tmp48khxd0nwandb-artifacts			   tmphshrf9juwandb-artifacts  tmpvd_wklrtwandb
tmp49fv73y2wandb-media				   tmpi31q87a0wandb-artifacts  tmpvg_71vtdwandb-media
tmp49sad_g1wandb-artifacts			   tmpiu05wr2_wandb	       tmpvlxyr3eawandb-media
tmp4c4800_xwandb-media				   tmpivnhmojfwandb	       tmpvqmyjo4pwandb-media
tmp4clbe6xvwandb-media				   tmpj16iv0rbwandb-media      tmpw10pvrxxwandb-media
tmp4nuizjduwandb-media				   tmpj4nmef2_wandb-media      tmpw8eaus7xwandb-media
tmp5aiik94rwandb-media				   tmpj6k4pajlwandb-artifacts  tmpw97zp6pqwandb-media
tmp5jusc1czwandb-media				   tmpjetcrm92wandb-media      tmpwkzzglljwandb-media
tmp5ks7vxpqwandb				   tmp_jfnbfwcwandb-artifacts  tmpwlpoppuwwandb-media
tmp5ss5gfoqwandb-media				   tmpjhcfo3sjwandb-media      tmpwok9yxtqwandb-media
tmp61l257guwandb-media				   tmpjhkja0n4wandb-media      tmpwqbb7793wandb
tmp66a_30crwandb				   tmpjq3bc0iywandb-media      tmpwu7oid1swandb-media
tmp6_95ss09					   tmpjseq6pjrwandb	       tmpwwmlqm3gwandb-artifacts
tmp6eb3e1v_wandb-artifacts			   tmpjywyihxswandb	       tmpwys0txyz
tmp6ev3bw0kwandb-media				   tmpk7eb9cxxwandb-artifacts  tmpx0i8_uxdwandb-media
tmp6j_pagmjwandb-media				   tmpki8mvo7pwandb	       tmpxby6g44swandb-media
tmp6uz84wzpwandb				   tmpkiqc2rxywandb-media      tmpxdsg3tk8wandb-artifacts
tmp7dmpqrecwandb				   tmpklsmildcwandb-media      tmpxm2j1915wandb
tmp7fzpg3pjwandb-artifacts			   tmpkvhsusnzwandb-artifacts  tmp_xmydpcnwandb-media
tmp7iafm3cywandb-media				   tmpkvt13pjiwandb	       tmpxpj1qkhnwandb-media
tmp7m0tkcx7wandb				   tmpkxhoutmnwandb	       tmpxqnwoio_wandb-media
tmp7p7ko5c1					   tmpl32i_q8cwandb-artifacts  tmpy3sbukw0wandb-artifacts
tmp7xmnpnjxwandb-media				   tmpldwit_dswandb-media      tmpy4tqgd9q
tmp80lef2dvwandb				   tmplf9oolt5wandb	       tmpy5mlqvf2
tmp89e0j4bjwandb-artifacts			   tmplgmiofgnwandb-artifacts  tmpy5y0mxbrwandb
tmp8h7rchd9wandb-artifacts			   tmplw1n5b69wandb-media      tmpydoskv75wandb
tmp8l4njuz2					   tmplx9285iywandb	       tmpyx791iakwandb-media
tmp8lxb4u_0wandb				   tmp_lzx3b9dwandb-media      tmpyy2hv95pwandb-artifacts
tmp8lyo8smzwandb				   tmpm1c4zy4twandb-artifacts  tmpz0gx4ikiwandb-media
tmp8q4h8lu7wandb-artifacts			   tmpm2755ginwandb-artifacts  tmpz26cajmh
tmp_8uvnuf2wandb				   tmpm56u1aa5wandb-media      tmpz5s198hnwandb-artifacts
tmp96o0qfii					   tmpm9gk_r6swandb-media      tmpz6oxqu4vwandb-media
tmp974f9ciawandb-media				   tmpm_9gv20owandb-media      tmpzgz2lbnmwandb
tmp98ec7tz8wandb-media				   tmpmdak3eqkwandb-media      tmpzyqel_hcwandb-artifacts
tmp9i4bx28vwandb				   tmpmekovp_5wandb-artifacts  tmpzzjlqqh8wandb-media
tmp9l8xrnlqwandb-media				   tmp_mpucxdiwandb-artifacts  ultimate-utils
tmp9y_56adfwandb-media				   tmpmsn3sy8mwandb-artifacts  wandb
```

### Environment

WandB version:
(metalearning_gpu) brando9~ $ python
Python 3.9.13 (main, Oct 13 2022, 21:15:33)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> wandb.__version__
'0.13.5'

OS: ubuntu/linux

(metalearning_gpu) brando9~ $ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

Python version: 3.9.13

Versions of relevant libraries:

### Additional Context

when you ask us for wandb version OS etc it would be useful if you give us the commands to run to save us time. 

----

- https://community.wandb.ai/t/how-to-stop-weights-biases-wandb-from-creating-random-tmp-files/3460
- https://stackoverflow.com/questions/74566670/how-to-stop-weights-biases-wandb-from-creating-random-tmp-files

**Comment by brando90** [comment] 2022-11-24 19:18
related issues:
- https://github.com/wandb/wandb/issues/4409
- https://github.com/wandb/wandb/issues/4534

**Comment by vanpelt** [comment] 2022-11-26 00:07
@brando90 I think this is related to your system tmp dir.   Can you:

1. print the following env variables (and check access if available):
    - TMPDIR
    - TEMP
    - TMP
2. check access to the following folder (using the ls -ltr /):
    - '/tmp'
    - '/var/tmp'
    - '/usr/tmp'
3. list the current working dir (where the script is executed)

**Comment by kptkin** [comment] 2023-03-08 20:24
@brando90 since we haven't heard from you we are going to close this issue. Please feel free to re-open it if this issue still persist.

**Comment by ethanabrooks** [comment] 2023-05-16 21:23
@kptkin would it be possible to reopen this issue? I am having the same problem. However, it is causing my disk to run out of space (the artifacts are quite large) so it is indeed blocking progress for me. I have a mounted external drive that I would like to write to instead (it has much more disk space). 

I was hoping you might at least point me to a line in the SDK code so that I could fork and modify. 

Also I can create a new issue if that would be better.

**Comment by umakrishnaswamy** [comment] 2023-05-26 17:37
Hey @ethanabrooks,

Sorry to hear that you're running into this. Could you talk a bit about your workflow? Are you running this locally or on a cluster? If you could send over a code snippet to reproduce on my end, that would be great.

**Comment by ethanabrooks** [comment] 2023-05-27 13:41
Hi, I think this was actually not an issue with wandb but with ray. Sorry for the false alarm.

**Comment by umakrishnaswamy** [comment] 2023-05-30 17:52
Hey @ethanabrooks,

No problem. I'm going to go ahead and close out this issue. If you come across any issues or have any questions regarding wandb, feel free to open another issue!

All the best,

Uma

**Comment by ethanabrooks** [comment] 2023-05-30 17:57
Sounds good.

**Comment by salcc** [comment] 2023-07-20 08:57
I'm getting this issue too, and I'm not using Ray.

**Comment by kptkin** [comment] 2024-04-17 05:08
closing this issue in favor of #7066 as duplicate

**Closed by kptkin** 2024-04-17 05:08 UTC
Labels: c:artifacts, a:cli
