### ISSUE TITLE
[CLI]: setting wandb disabled doesn't fully disable it

### ISSUE THREAD

**Issue by zplizzi** [wandb/wandb#4529] opened 2022-11-23 20:25 UTC
### Describe the bug

I'm using a performance profiler `viztracer` on a pytorch training routine that uses wandb. It seems like there's some interference between the tracer and wandb that causes wandb to crash. So I figure I can just disable wandb (`$ wandb disabled`) , but it still crashes with a bug deep inside wandb - it seems like wandb is still trying to launch the service process or something even when it's set to disabled!

Here's the traceback - the first 2 lines are from some logging that I added in the wandb code to try to figure out what was going on. I'm guessing the tracer somehow patched `python` and it no longer supports `-m`? But the solution IMO is really that wandb should not be trying to start a process at all when disabled. 
```
$ viztracer --min_duration 10us --ignore_c_function --ignore_frozen my_script.py
['/opt/venv/bin/python3.9', '-m', 'wandb', 'service', '--port-filename', '/tmp/tmpm5groj4d/port-12604.txt', '--pid', '12604', '--debug', '--serve-sock']
No such file as -m
Traceback (most recent call last):
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in init
    wi.setup(kwargs)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in setup
    self._wl = wandb_setup.setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in setup
    ret = _setup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _setup
    wl = _WandbSetup(settings=settings)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 265, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 108, in __init__
    self._service.start()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 110, in start
    self._launch_server()
  File "/opt/venv/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 106, in _launch_server
    assert ports_found
AssertionError
```

Btw this script is sufficient to replicate the issue when called by viztracer as shown above:
```
import wandb

if __name__ == "__main__":
    wandb.init()
```

### Environment

WandB version: 0.13.5

OS: Ubuntu 20.04

Python version: 3.9

Versions of relevant libraries:

**Comment by zplizzi** [comment] 2022-11-23 20:56
Fyi the last working version in this example is `wandb==0.12.21`, it seems that 0.13 broke this.

**Comment by kptkin** [comment] 2022-11-25 22:31
@zplizzi Thanks for reporting this issue, it is indeed a bug, we enabled the offending logic by default since 0.13. We will add a fix to delay spinning up this logic to a later phase allowing for the disable functionality. Sorry for the inconvenience. 
The fix will be included in the one of the upcoming releases!

**Comment by LucHayward** [comment] 2022-11-27 15:41
Just to add further context this seems to be related to #1236 and is also caused by starting too many wandb tracked runs in one go I think.

**Comment by kptkin** [comment] 2022-12-03 17:42
@LucHayward I think you might be right about the error, but what @zplizzi is asking for is the ability to disable `wandb` for a specific execution. In 0.13 we introduced some logic that runs even is you don't start a run that breaks the `wandb disable` command due to the order of execution. We will include a fix for this issue in the next release in January. 

For the issue you are pointing to is more complicated, but also relates to the same change, we are hopefully will also include a fix for it in the January release.

**Comment by kptkin** [comment] 2023-01-26 03:15
Just wanted to give an update here that we are working on a solution and we are trying to get it to the upcoming release. We fully identified the source of the issue and debating what is the best way to enable this functionality. Our main consideration is that if the the disable command should affect the entire script or if we should enable an option to have some runs be in a non-disabled mode.

**Comment by kptkin** [comment] 2023-02-09 07:53
For anyone that has an issue with this disable mode, currently, I would suggest to set the following environment variable: `WANDB_DISABLE_SERVICE` and use the regular disable mode (if you are setting it up in a script make sure to set it up before importing `wandb`). This one should work. Please let me know if you still seeing the issue.

**Closed** 2023-02-10 01:38 UTC
Labels: cli
