### ISSUE TITLE
[CLI]: Can't find port file when using wandb.require("service")

### ISSUE THREAD

**Issue by ArnolFokam** [wandb/wandb#3911] opened 2022-07-08 08:37 UTC
### Describe the bug

When running the code snippet below using **WanDB** + **PyTorchLightning** on SLURM. The code crashes randomly for most if not all runs.

```python 
logger = WandbLogger(project="MNIST")

```

```shell
Traceback (most recent call last):
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 133, in setup
    self._wl = wandb_setup.setup()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 318, in setup
    ret = _setup(settings=settings)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 313, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 299, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 113, in __init__
    self._setup()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 240, in _setup
    self._setup_manager()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 271, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 106, in __init__
    self._service.start()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 104, in start
    self._launch_server()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 100, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 996, in init
    wi.setup(kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 133, in setup
    self._wl = wandb_setup.setup()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 318, in setup
    ret = _setup(settings=settings)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 313, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 299, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 113, in __init__
    self._setup()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 240, in _setup
    self._setup_manager()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 271, in _setup_manager
    self._manager = wandb_manager._Manager(
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 106, in __init__
    self._service.start()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 104, in start
    self._launch_server()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 100, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home-mscluster/mfokam/assa/scripts/pretrain_eval.py", line 140, in train_eval
    logger = WandbLogger(
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 311, in __init__
    _ = self.experiment
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 41, in experiment
    return get_experiment() or DummyExperiment()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/pytorch_lightning/loggers/base.py", line 39, in get_experiment
    return fn(self)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/pytorch_lightning/loggers/wandb.py", line 357, in experiment
    self._experiment = wandb.init(**self._wandb_init)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1037, in init
    raise Exception("problem") from error_seen
Exception: problem
Traceback (most recent call last):
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/cli/cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/cli/cli.py", line 285, in service
    server.serve()
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 128, in serve
    self._inform_used_ports(grpc_port=grpc_port, sock_port=sock_port)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/server.py", line 65, in _inform_used_ports
    pf.write(self._port_fname)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/site-packages/wandb/sdk/service/port_file.py", line 25, in write
    f = tempfile.NamedTemporaryFile(prefix=bname, dir=dname, mode="w", delete=False)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/tempfile.py", line 540, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home-mscluster/mfokam/anaconda3/envs/assa/lib/python3.8/tempfile.py", line 250, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mfokam/tmpel7x5eip/port-21750.txti_81fekt'
```

### Environment

WandB version: 0.12.20

OS: Ubuntu 18.04.6 LTS

Python version: 3.8

Versions of relevant libraries:
PyTorch: 1.12.0
PyTorch Lightning: 1.6.4

### Additional Context

- The code seems to crash when executed on a very slow cluster node
- Tried to reproduce the error locally but I can only get a similar error if I insert a breakpoint point on the tempfile.py method executed (see last 6 lines of the stack trace) and I wait. After a certain period (3 - 5 seconds), I get an error similar to what I have on SLURM.

**Comment by nate-wandb** [comment] 2022-07-11 16:07
Hi @ArnolFokam, could you possibly send the `debug.log` and `debug-internal.log` files for a run that crashed? These can be found in the local run folder on the training machine. 

Will a certain node always lead to this crash? Are there other nodes that usually successful?

Thank you,
Nate

**Comment by ArnolFokam** [comment] 2022-07-13 11:58
Hi @nate-wandb 

This error occurs when ```wandb.init``` is called. Therefore, the wandb folder is not yet created.

In my case, I can confirm that this error occurs when the cluster is very slow. Also, this error is related to ```wandb.require('service')```. I say this because when I downgraded wandb to remove the automatic execution of that snippet on Pytorch Lightning, everything worked fine.

Thanks,
Arnol Fokam.

**Comment by anmolmann** [comment] 2022-07-28 05:33
@ArnolFokam , I see, thanks for the info. Could you share a brief code snippet, that would really help us in reproducing the issue on our end? 
1. Are you simply instantiating the logger through `pytorch_lightning.logger.WandbLogger?
2. As you mentioned in that this is happening on a very slow cluster node. Could you also try running your script in an offline mode and let us know if you still encounter this issue? The `WandbLogger` has an arg `offline` which can be set to `True` to run wandb in offline mode.

**Comment by ArnolFokam** [comment] 2022-07-28 06:38
@anmolmann,

It might be difficult to reproduce the error if you don't possess a cluster node slow enough but I remarked that when I insert a breakpoint (running locally) somewhere inside the constructor called [here](https://github.com/wandb/wandb/blob/2ba68805cabe726a9fe58eac13a4ec3c748b1d83/wandb/sdk/service/port_file.py#L25) and I wait long enough (5 - 8 seconds) I get a similar error.

1. Yes.
2.  I did set `offline=True` after the error occurred but still encountered the same issue.

Hope it helps.

**Comment by anmolmann** [comment] 2022-08-02 17:26
Thanks for the update @ArnolFokam. I'll file an internal ticket for this one and will follow-up with you once I've an update.

**Comment by ShenghaiRong** [comment] 2022-08-04 08:52
Hi, I had the same problem when I ran the code on a very slow cluster node. I found out that the reason for the error is because of the magic number 30 in the code below：
[https://github.com/wandb/wandb/blob/037dd5ba64a406b5d3d3b41d9eefaff0b177973a/wandb/sdk/service/service.py#L41](url)
 When I increase the max waiting time from 30 to 300, it works.

**Comment by anmolmann** [comment] 2022-08-05 21:24
Thanks for the update, @ShenghaiRong! @ArnolFokam, could you please confirm if the aboe suggestion by @ShenghaiRong help out in resolving your issue?

**Comment by ArnolFokam** [comment] 2022-08-06 05:09
Currently, I can't confirm this given the fact that I'm no longer affected by the error (cluster went back to normal speed). I tried reproducing the scenario using the method described in my comment https://github.com/wandb/wandb/issues/3911#issuecomment-1197726977 but still got the same error

**Comment by koulanurag** [comment] 2022-08-10 04:58
This is to add that I have been facing a similar issue on our cluster.

> Hi, @anmolmann @ArnolFokam , I had the same problem when I ran the code on a very slow cluster node. I found out that the reason for the error is because of the magic number 30 in the code below https://github.com/wandb/wandb/blob/master/wandb/sdk/service/service.py#L41 ` def _wait_for_ports(self, fname: str, proc: subprocess.Popen = None) -> bool:` `time_max = time.time() + 30` When I increase the max waiting time from 30 to 300, it works.

I was facing the same issue and changing it to 300 worked for me.

**Comment by anmolmann** [comment] 2022-08-12 16:06
Thanks for the update, @koulanurag and @ArnolFokam! I'll close this for now as it can be resolved by increasing the waiting time.

**Comment by Adam-lxd** [comment] 2022-08-16 13:06
when I upgrade pytorch-lightning==1.7.1 seeing the same problem. I tried to set `os.environ["WANDB_MODE"] = "offline"` and `offline=True` even the solution in https://github.com/wandb/wandb/issues/3911#issuecomment-1204961296. but when degrade 
pytorch-lightning==1.1.8 code can run without any problem. I guess it's may be caused by the network and the difference of WandbLogger in pytorch_lightning.loggers

**Comment by anmolmann** [comment] 2022-08-29 22:29
@Adam-lxd , you're right this is being caused by network slowness for sure. Please let us know if you see that your network speed is back to normal but you still encounter this issue.

**Comment by Adam-lxd** [comment] 2022-09-01 04:14
> @Adam-lxd , you're right this is being caused by network slowness for sure. Please let us know if you see that your network speed is back to normal but you still encounter this issue.

Thanks, the main reason is my network, may the cluster administrator block the connection to wandb service. now my solution is training on the cluster with offline mode, then switching o my PC to upload log files.

**Comment by pinakinathc** [comment] 2022-12-31 19:59
> Hi, @anmolmann @ArnolFokam , I had the same problem when I ran the code on a very slow cluster node. I found out that the reason for the error is because of the magic number 30 in the code below https://github.com/wandb/wandb/blob/master/wandb/sdk/service/service.py#L41 ` def _wait_for_ports(self, fname: str, proc: subprocess.Popen = None) -> bool:` `time_max = time.time() + 30` When I increase the max waiting time from 30 to 300, it works.

do I have to rebuild the package to fix this? Or is there some API-way to increase the time limit?

**Comment by timvandam** [comment] 2023-01-02 23:26
> @Adam-lxd , you're right this is being caused by network slowness for sure. Please let us know if you see that your network speed is back to normal but you still encounter this issue.

I'm having this issue at the moment on a cluster, and don't think it's network speed in my case. Getting 820 Mbit/s down and 741 Mbit/s up

**Comment by SimonRosen173** [comment] 2023-01-11 13:24
@anmolmann This issue is still present in WANDB and crashes the runs please reopen the issue.

**Comment by anmolmann** [comment] 2023-01-17 17:13
@timvandam & @SimonRosen173, thanks for reporting this. We've filed an internal bug report for this issue and will follow-up with you as soon as we've an update.

**Comment by vict0rsch** [comment] 2023-01-21 19:55
I'm also running on a cluster where I'm certain network is not the issue and having a ports issue that crashes my jobs...!

```
Traceback (most recent call last):
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1105, in init
    wi.setup(kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 167, in setup
    self._wl = wandb_setup.setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in setup
    ret = _setup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 302, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 288, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 262, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 112, in __init__
    self._service.start()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 137, in start
    self._launch_server()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 132, in _launch_server
    assert ports_found
AssertionError
wandb: ERROR Abnormal program exit
Traceback (most recent call last):
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1105, in init
    wi.setup(kwargs)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 167, in setup
    self._wl = wandb_setup.setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 307, in setup
    ret = _setup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 302, in _setup
    wl = _WandbSetup(settings=settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 288, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 106, in __init__
    self._setup()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 234, in _setup
    self._setup_manager()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_setup.py", line 262, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py", line 112, in __init__
    self._service.start()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 137, in start
    self._launch_server()
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 132, in _launch_server
    assert ports_found
AssertionError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 142, in <module>
    trainer: BaseTrainer = cls(**trainer_config)
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-2/ocpmodels/trainers/base_trainer.py", line 150, in __init__
    self.load()
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-2/ocpmodels/trainers/base_trainer.py", line 159, in load
    self.load_logger()
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-2/ocpmodels/trainers/base_trainer.py", line 190, in load_logger
    self.logger = registry.get_logger_class(logger_name)(self.config)
  File "/home/mila/s/schmidtv/ocp-project/run-repos/ocp-2/ocpmodels/common/logger.py", line 116, in __init__
    self.run = wandb.init(
  File "/home/mila/s/schmidtv/.conda/envs/ocp-a100/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    raise Exception("problem") from error_seen
Exception: problem
```

**Comment by sehoffmann** [comment] 2023-01-23 15:53
The problem in my case is, that importing conda packages can sometimes take an exorbitant amount of time. Thus, the wandb daemon process takes too long too start and the timeout is triggered. Increasing the timeout manually helped in my case, but even with 2 minutes, I experienced situations where the cluster was so bad that the increased timeout triggered.

Now I realize that the way our cluster behaves is not good at all, however I only have very little control of it. What I believe wandb can do though, is to weaken this failure case from being critical, i.e. terminating, to something non-critical. Also increasing the (final) timeout slightly, maybe to a minute or two, and instead adding a warning in case it exceeds 30 seconds might be another (additional) option as well.

**Comment by timvandam** [comment] 2023-01-23 16:04
I use venv, not conda, but have also noticed that packages take an exorbitant amount of time to load on a cluster. This may well be the issueOn 23 Jan 2023, at 16:53, Sebastian Hoffmann ***@***.***> wrote:﻿
The problem in my case is, that importing conda packages can sometimes take an exorbitant amount of time. Thus, the wandb daemon process takes too long too start and the timeout is triggered. Increasing the timeout manually helped in my case, but even with 2 minutes, I experienced situations where the cluster was so bad that the increased timeout triggered.
Now I realize that the way our cluster behaves is not good at all, however I only have very little control of it. What I believe wandb can do though, is to weaken this failure case from being critical, i.e. terminating, to something non-critical. Also increasing the (final) timeout slightly, maybe to a minute or two, and instead adding a warning in case it exceeds 30 seconds might be another (additional) option as well.

**Comment by kptkin** [comment] 2023-01-26 03:04
Hi all! 

Thanks for reporting this issue. We are actively working on resolving it and would like to ask for your help.
 
- If you could upgrade to the e latest version of wandb (as writing this message it would be 0.13.9) that would really helpful.
- Also we introduce new environment variable (`WANDB__SERVICE_WAIT`) this will allow you increase the startup time from the command line instead of reaching and modifying the installed code. To use it just do the following:
```WANDB__SERVICE_WAIT=300 python your_script.py``
- Another thing we added a debug flag that will print the timing information during startup to the tdout (if you have a way to collect stdout and share with us that would further help us narrow down the issue). You can do that as follows:
```_WANDB_STARTUP_DEBUG=true python your_script.py```

Sorry that you are experiencing issue and hopefully we could resolve them soon.

**Comment by gsaltintas** [comment] 2023-01-29 10:59
Hi @kptkin ,

Thank you for this update, it will be very helpful. I am wondering how this variable can be passed as a setting to `wandb.init`? I tried the following  but it doesn't work

```python
import wandb
from pytorch_lightning.loggers import WandbLogger
wandb_logger = WandbLogger(settings=wandb.Settings(_service_wait=300))
```
Also, would it be possible to update the [docs](https://docs.wandb.ai/guides/track/advanced/environment-variables)?

**Comment by kptkin** [comment] 2023-01-31 05:12
> Hi @kptkin ,
> 
> Thank you for this update, it will be very helpful. I am wondering how this variable can be passed as a setting to `wandb.init`? I tried the following but it doesn't work
> 
> ```python
> import wandb
> from pytorch_lightning.loggers import WandbLogger
> wandb_logger = WandbLogger(settings=wandb.Settings(_service_wait=300))
> ```
> 
> Also, would it be possible to update the [docs](https://docs.wandb.ai/guides/track/advanced/environment-variables)?

@gsaltintas thanks for trying it out few comments:
- settings with _ are private settings that we might remove in the future, hence we don't officially document them, until we audit them and convince ourselves these settings are necessary, but once we move them to public, we will be sure to document them.
- regarding your script, it seems that you are correct and we don't pass this setting properly (it is a special case during the setup process of our service, we are working on a fix, to make sure the settings are resolved correctly), so I would suggest in the meantime, adding is as environment variable to the beginning of your script to make it work:

```
import os
import wandb
from pytorch_lightning.loggers import WandbLogger

os.environ["WANDB__SERVICE_WAIT"] = "300"

wandb_logger = WandbLogger()
```

**Comment by sehoffmann** [comment] 2023-02-02 15:08
Hi @kptkin,

The update is very appreciated!
Here's the startup timing log I just recorded:
> WANDB_STARTUP_DEBUG 1675350229.154492 launch
WANDB_STARTUP_DEBUG 1675350229.1584668 wait_ports
WANDB_STARTUP_DEBUG 1675350264.0804012 before_network
WANDB_STARTUP_DEBUG 1675350264.0806823 after_network
WANDB_STARTUP_DEBUG 1675350264.080885 after_inform
WANDB_STARTUP_DEBUG 1675350264.0967941 before_loop
WANDB_STARTUP_DEBUG 1675350264.2041976 wait_ports_done
WANDB_STARTUP_DEBUG 1675350264.2043722 launch_done

This was a very average run; I will report back when I encounter a more severe scenario.

**Comment by jxmorris12** [comment] 2023-03-23 01:23
Wow, I saw the same timeout error:
```
│   140 │   │   │   return                                                                         │
│ ❱ 141 │   │   raise ServiceStartTimeoutError(                                                    │
│   142 │   │   │   "Timed out waiting for wandb service to start after "                          │
│   143 │   │   │   f"{self._settings._service_wait} seconds. "                                    │
│   144 │   │   │   "Try increasing the timeout with the `_service_wait` setting."                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait`
setting.
```
and fixed it by increasing the timeout via setting the `WANDB__SERVICE_WAIT` env variable to 300.

**Comment by fryguy1013** [comment] 2023-05-25 08:10
I'm on windows and receiving this error as well. With the startup debug, I see this:

```
WANDB_STARTUP_DEBUG 1685001990.7673497 launch
WANDB_STARTUP_DEBUG 1685001990.77035 wait_ports
Unhandled exception. Python.Runtime.PythonException: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.
Unhandled exception. Python.Runtime.PythonException: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\service.py", line 141, in _wait_for_ports
    raise ServiceStartTimeoutError(
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\service.py", line 191, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\analytics\sentry.py", line 146, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\service.py", line 193, in _launch_server
    _sentry.reraise(e)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\service.py", line 199, in start
    self._launch_server()
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_manager.py", line 145, in __init__
    self._service.start()
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 277, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 114, in __init__
    self._setup()
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 320, in _setup
    wl = _WandbSetup(settings=settings)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 327, in setup
    ret = _setup(settings=settings)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 172, in setup
    self._wl = wandb_setup.setup(settings=setup_settings)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1146, in init
    wi.setup(kwargs)
  File "C:\Users\********\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 1169, in init
    raise e
  File "C:\dev\PawnStop\PawnStopAgent\bin\Debug\net7.0\model.py", line 69, in wandb_init
    wandb.init(
  File "C:\dev\PawnStop\PawnStopAgent\bin\Debug\net7.0\model.py", line 188, in fit
    self.wandb_init()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure, CallSite, Object, Single[], Single[], Single[], Int32, Int32, Int32)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute7[T0,T1,T2,T3,T4,T5,T6,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6)
   at PawnStop.AlphaZero.ResidualCNN.Fit(Single[] inputs, Single[] values, Single[] policies, Int32 numSamples, Int32 epochs, Int32 initialEpoch) in C:\dev\PawnStop\PawnStopLib\AI\AlphaZero.cs:line 479
   at PawnStop.AlphaZero.Fit(IEnumerable`1 inputs, IEnumerable`1 policies, IEnumerable`1 values, Int32 epochs, Int32 initialEpochs) in C:\dev\PawnStop\PawnStopLib\AI\AlphaZero.cs:line 72
   at PawnStopAgent.TrainingAgent.Train() in C:\dev\PawnStop\PawnStopAgent\Program.cs:line 161
   at PawnStopAgent.Program.Main(String[] args) in C:\dev\PawnStop\PawnStopAgent\Program.cs:line 104
```

**Comment by Aaronponceuv** [comment] 2023-09-11 02:30
the environment variable os.environ["WANDB__SERVICE_WAIT"] = "300" doesn't work for me. Is there another alternative?

**Comment by sephmard** [comment] 2024-08-22 20:47
Hey @Aaronponceuv, @moghis, @fryguy1013, @jxmorris12, @sehoffmann,

I wanted to provide an update. We have a new Go based client that improves logging reliability. You can see more about it here: https://wandb.me/wandb-core. This update includes some stability improvements that might help with the run hangs issue you encountered. You can try it out by adding upgrading wandb and adding wandb.require("core") to your scripts.

Mind letting us know if this helps?

**Closed** 2024-08-27 16:18 UTC
Labels: a:cli, c:service, s:nexus-fix
