### ISSUE TITLE
I cannot connect wandb using wandb.init()

### ISSUE THREAD

**Issue by gulfemakpinar** [wandb/wandb#7958] opened 2024-07-15 05:53 UTC
### Environment

OS:

Browsers:

Version:

### Additional Context

just 1 or 2 hour ago, I was working on my project but now it gives 
CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
or
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
but I double check every part and I know that I did not change anything from my working code.

**Comment by ashishp166** [comment] 2024-07-15 05:59
The same issue is faced here. It was working perfectly fine with me up until just an hour ago.

**Comment by quanvuong** [comment] 2024-07-15 06:09
same here

**Comment by FrozenWolf-Cyber** [comment] 2024-07-15 06:10
Same here, in fact, right now, one of my runs from an hour ago is continuing temporarily while new runs don't seem to be able to start. I think there is some sort of server lag, maybe? This seems to be happening to many people in [wandb community](https://community.wandb.ai/t/error-while-calling-w-b-api-permission-denied/6921) very recently. I am not sure if its happening in the self-hosted wandb servers. 

Temperory fix is to resume the failed run like this:

```python
    wandb.init(
        project=<project-name>,
        entity=<username>,
        id="autumn-silence-305", resume="must", ########### COMMENT THIS LINE FOR NEW RUNS, IF NEW RUN FAILS USE NEW RUN ID in place "autumn-silence-305"
    )
```

**Comment by ksmile007** [comment] 2024-07-15 06:31
@gulfemakpinar 
Hey bro.
I also had an error with wandb.init() earlier (wandb.errors.CommError), but when I tried it again now, it worked!
Check your codes, everyone.

**Comment by Ibrah-N** [comment] 2024-07-15 07:41
Same issue i'm also encontering

**Comment by Ibrah-N** [comment] 2024-07-15 08:03
As I checked in the documentation the CommError raised due to fail in communication with wandb serever (source-> reference->init()

**Comment by fmamberti-wandb** [comment] 2024-07-15 10:42
Hi @gulfemakpinar @Ibrah-N @ksmile007 @FrozenWolf-Cyber @quanvuong @ashishp166 - Apologies you were experiencing these errors - we rolled a fixed for this and you should now be able to log Runs as expected. Please let us know if you are still experiencing issues.

**Comment by FrozenWolf-Cyber** [comment] 2024-07-15 13:04
It is working now :)

**Closed** 2024-07-17 10:27 UTC

**Comment by yaolug** [comment] 2024-09-28 22:03
hello it happens again just now

**Comment by deansereigns** [comment] 2025-02-12 11:05
The issue is still occurring wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
