### ISSUE TITLE
WandbCallback fails on TPU[CLI] 

### ISSUE THREAD

**Issue by harveenchadha** [wandb/wandb#2672] opened 2021-09-15 16:33 UTC
**Description**
Adding Keras WandbCallback fails and throws an error.

![Screenshot from 2021-09-15 21-32-25](https://user-images.githubusercontent.com/30959215/133473247-265d5805-22d0-4933-81e8-35f4c1f2382a.png)

**Comment by vanpelt** [comment] 2021-09-15 17:44
@harveenchadha can you confirm what version of wandb you're using by running `wandb --version`?

**Comment by harveenchadha** [comment] 2021-09-15 20:21
I am on the latest version:

0.12.2

**Comment by vanpelt** [comment] 2021-09-16 00:05
@harveenchadha if you're able to share a colab that can reproduce this that would really help us get to the bottom of it.  We think it's because the summary is too large for us to sync in the current time we allow.  The next release of the library should increase this timeout, but if we can reproduce ourselves before than we can likely get you a workaround.

**Comment by vanpelt** [comment] 2021-09-16 00:05
My email is vanpelt@wandb.com if you want to share a private colab.

**Comment by harveenchadha** [comment] 2021-09-16 01:54
I can give you a public kaggle [kernel](https://www.kaggle.com/harveenchadha/chaii-tpu-train-nfold-xlm-hf-tf-data-extra?scriptVersionId=74865075)

Here you will find the error.

If something is wrong with my code structure, do let me know!

**Comment by vanpelt** [comment] 2021-09-16 22:34
Hey @harveenchadha we'll need to look into a fix for this ahead of the next release.  Until then, I think the simplest solution would be to use the keras Tensorboard callback and just add `sync_tensorboard=True` to `wandb.init`.

**Comment by MiniXC** [comment] 2023-01-04 14:48
Is this still an issue? Running into a similar problem on TPU:
```
Exception in device=TPU:0: problem                                                                                                                                                            
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 331, in _mp_start_fn                                                                       
    _start_fn(index, pf_cfg, fn, args)                                                                                                                                                        
  File "/usr/local/lib/python3.8/dist-packages/torch_xla/distributed/xla_multiprocessing.py", line 325, in _start_fn                                                                          
    fn(gindex, *args)                                                                                                                                                                         
  File "/home/christoph.minixhofer/lightning/src/pytorch_lightning/strategies/launchers/xla.py", line 100, in _wrapping_function                                                              
    results = function(*args, **kwargs)                                                                                                                                                       
  File "/home/christoph.minixhofer/lightning/src/pytorch_lightning/trainer/trainer.py", line 644, in _fit_impl                                                                                
    self._run(model, ckpt_path=self.ckpt_path)                                                                                                                                                
  File "/home/christoph.minixhofer/lightning/src/pytorch_lightning/trainer/trainer.py", line 1085, in _run                                                                                    
    self._log_hyperparams()                                                                                                                                                                   
  File "/home/christoph.minixhofer/lightning/src/pytorch_lightning/trainer/trainer.py", line 1153, in _log_hyperparams                                                                        
    logger.log_hyperparams(hparams_initial)                                                                                                                                                   
  File "/home/christoph.minixhofer/.local/lib/python3.8/site-packages/lightning_utilities/core/rank_zero.py", line 24, in wrapped_fn                                                          
    return fn(*args, **kwargs)                                                                                                                                                                
  File "/home/christoph.minixhofer/lightning/src/pytorch_lightning/loggers/wandb.py", line 426, in log_hyperparams                                                                            
    self.experiment.config.update(params, allow_val_change=True)                                                                                                                              
  File "/home/christoph.minixhofer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 253, in wrapper                                                                           
    raise e                                                                                                                                                                                   
  File "/home/christoph.minixhofer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 248, in wrapper                                                                           
    wandb._attach(run=self)                                                                                                                                                                   
  File "/home/christoph.minixhofer/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 841, in _attach                                                                          
    raise UsageError("problem")                                                                                                                                                               
wandb.errors.UsageError: problem
```

**Comment by mx781** [comment] 2023-02-10 14:07
@MiniXC and anyone else stumbling upon this (as it seems to be the lone search result for the mysterious "wandb.errors.UsageError: problem") - upgrading pytorch lightning to 1.9.0 and wandb to 0.13.10 solved this issue for me.

**Comment by anmolmann** [comment] 2023-02-10 20:38
Hi @MiniXC, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by anmolmann** [comment] 2023-02-16 15:39
Hi @MiniXC , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Closed by anmolmann** 2023-02-16 15:39 UTC
Labels: cli
