### ISSUE TITLE
[App]: Sentry is still functioning even when Wandb is turned off.

### ISSUE THREAD

**Issue by homjay** [wandb/wandb#6403] opened 2023-10-03 13:41 UTC
### Current Behavior

I have already disabled `wandb` using the command:
```bash
wandb disabled
```

After disabling it, I can still observe attempted connections to `sentry.io`:

```bash
Certificate did not match expected hostname: o151352.ingest.sentry.io
```

I initially believed that disabling `wandb` would disable all monitoring services, but it appears that `sentry` is still functional.

### Environment

OS: Ubuntu

Browsers:

Version: `wandb, version 0.15.11`

**Comment by sydholl** [comment] 2023-10-03 14:13
Internal GitHub User commented: 
### Current Behavior

I have already disabled `wandb` using the command:
```bash
wandb disabled
```

After disabling it, I can still observe attempted connections to `sentry.io`:

```bash
Certificate did not match expected hostname: o151352.ingest.sentry.io
```

I initially believed that disabling `wandb` would disable all monitoring services, but it appears that `sentry` is still functional.



### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Screenshots

_No response_

### Environment

OS: Ubuntu

Browsers:

Version: `wandb, version 0.15.11`


### Additional Context

_No response_

**Comment by umakrishnaswamy** [comment] 2023-10-04 17:37
Hey @homjay - Thank you for surfacing this. `wandb disabled` just disables W&B and all its network communication, but we still use our error tracking service. If you'd like to disable Sentry as well you can run the following in your CLI: 

`export WANDB_ERROR_REPORTING=False`

Please let me know if this helps!

**Comment by umakrishnaswamy** [comment] 2023-10-06 19:02
Hi @homjay, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please feel free to write back in!

**Comment by jayagami** [comment] 2023-10-06 19:05
Thanks bro, sorry for replying late, set 

'''
export WANDB_ERROR_REPORTING=False 
'''

did solved the problem.
Closing issue.

**Closed as completed** 2023-10-06 19:08 UTC
Labels: a:app
