### ISSUE TITLE
[CLI]: `wandb docker` not working for local images

### ISSUE THREAD

**Issue by ekorman** [wandb/wandb#3442] opened 2022-03-30 19:37 UTC
### Describe the bug

Running `wandb docker` with a local image yields the error
```
Command '['docker', 'inspect', '...', '--format', '{{index .RepoDigests 0}}']' returned non-zero exit status 1.
Error: Couldn't find image locally or in a registry, try running `docker pull ...`
```

I believe the parameter that gets passed to `--format` here https://github.com/wandb/client/blob/46d4c327bd5746419d387d5df962de56158faf3d/wandb/docker/__init__.py#L206
is incorrect.

### Environment

WandB version: 0.12.11

OS: tried on Mac OS and Ubuntu

Python version:

Versions of relevant libraries: Docker versions 20.10.2 and 20.10.10

**Comment by ekorman** [comment] 2022-04-18 13:06
hi sorry for the slow response. yes this is still an issue. my PR is here that details the fix and also shows a minimal replicating example: https://github.com/wandb/client/pull/3444

**Comment by themurtazanazir** [comment] 2022-12-29 10:09
Do we have an update on this? I am still facing this issue.

**Comment by lesliewandb** [comment] 2023-01-11 19:20
Hi @themurtazanazir, I had talked to our team about this and they are currently working on a patch release at the moment. They said that they would notify me with more information after the update has been released

**Comment by lesliewandb** [comment] 2023-01-11 23:31
Our team is going to add this as part of our milestones for the next release. They are going to review the PR you had given them and hopefully include it in the next release which will be in the first week of February

**Comment by kptkin** [comment] 2023-03-02 18:31
Hi @ekorman @themurtazanazir, a comment regarding this issue, we currently use `wandb docker` to create a reproducible environment, which requires access to the digest, given that you build your image locally there is no way to reproduce the environment. Would using `wandb docker-run` work for your use case?

**Comment by anmolmann** [comment] 2024-03-07 19:06
Hi @ekorman, @themurtazanazir , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Closed by anmolmann** 2024-03-07 19:06 UTC
Labels: a:cli, s:wait-on-user
