### ISSUE TITLE
Feature Request: Sweep config: Probabilities for categorical distribution

### ISSUE THREAD

**Issue by dreamflasher** [wandb/wandb#855] opened 2020-02-10 15:10 UTC
`wandb --version && python --version && uname`

wandb, version 0.8.24
Python 3.7.5
Linux

### Description

I want to run a sweep with the following config:

```
parameters:
  param1:
    values: ["True", "False"]
```
But let the value True happen in 10% of the cases, and False in 90% of the cases.

Would be great if you could add this, thanks a lot!

**Comment by lukas** [comment] 2020-02-13 17:15
Good idea - I will file a ticket.  One hacky workaround now would be to copy "False" 9 times.

**Comment by dreamflasher** [comment] 2020-02-13 18:45
@lukas that's how I ended up doing it, but it felt very hacky to me indeed :D Also I wasn't sure how Bayesian Optimization would deal with it – would it treat the strings as different values or as the same?

**Comment by ariG23498** [comment] 2020-12-03 05:16
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by dreamflasher** [comment] 2020-12-03 06:25
Please reopen

**Comment by sydholl** [comment] 2024-11-21 21:37
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Closed by sydholl** 2024-11-21 21:37 UTC
Labels: ty:feature, c:sweeps
