### ISSUE TITLE
[CLI]: Creating a wandb server doesn't work with Pex/PyTorch Lightning

### ISSUE THREAD

**Issue by nharada1** [wandb/wandb#4593] opened 2022-12-08 20:02 UTC
### Describe the bug

When trying to use the pytorch-lightning integrations with Weights and Biases, my code fails to run when using Pex as a packaging service. This is what's used in the popular Pants project. It appears to be an issue with how Pex runs programs in a sandbox, and the wandb library is trying to execute a subprocess in this sandbox somehow without permission.

I have reproduced a minimal example in this Github repo

https://github.com/nharada1/pex-wandb-repro

```shell
Traceback (most recent call last):
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1075, in i
nit
    wi.setup(kwargs)
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 165, in se
tup
    self._wl = wandb_setup.setup()
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 312, in s
etup
    ret = _setup(settings=settings)
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 307, in _
setup
    wl = _WandbSetup(settings=settings)
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 293, in _
_init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 106, in _
_init__
    self._setup()
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 234, in _
setup
    self._setup_manager()
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 265, in _
setup_manager
    self._manager = wandb_manager._Manager(
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/wandb_manager.py", line 111, in
 __init__
    self._service.start()
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 119,
in start
    self._launch_server()
  File "/home/user/.cache/pants/named_caches/pex_root/venvs/e33dbad2e381237c2ef87dd830f8fbcc73be777f/7898379b30005666861db5e178f56a2477d285aa/lib/python3.9/site-packages/wandb/sdk/service/service.py", line 109,
in _launch_server
    internal_proc = subprocess.Popen(
  File "/home/user/Software/mambaforge/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/user/Software/mambaforge/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/tmp/pants-sandbox-6kYP6O/src.pex'
wandb: ERROR Abnormal program exit
```

### Environment

WandB version: 0.13.6

OS: Linux

Python version: 3.9

Versions of relevant libraries:

**Comment by MBakirWB** [comment] 2022-12-08 23:56
Hi @nharada1, thank you for writing in. We have built in support with launching wandb from within a [PEX environment](https://github.com/wandb/wandb/pull/4440) as of our latest client version. I will review your reproducible error and report back. In the meantime could you try disabled wandb service,  `export WANDB_DISABLE_SERVICE=True` and update me on new behaviors/errors with your experiments. Thanks

**Comment by nharada1** [comment] 2022-12-09 03:28
Ahh, yes this worked with the service disabled, awesome! Thank you very much, do you know which release the Pex support will land in?

**Comment by kptkin** [comment] 2022-12-10 00:45
@nharada1 Thanks for the detailed repro! It made the debug process so much easier 😊 

The change to support PEX was released in 0.13.6 but it seems to be only correct in the case where you run a pex script and in your case the pex executable doesn't work. 

if you want to keep service (i.e. not setting up the `WANDB_DISABLE_SERVICE` env var) i could suggest the following solution (in your example in src/main.py) adding the following lines should do the trick because our `service` process will be able to use the proper python executable and won't have permission issues:
```
def main():
   wandb.setup(settings=dict(_executable=sys.executable))
```

**Comment by nharada1** [comment] 2022-12-10 21:40
Got it, thanks so much! What's the benefit of using the service if I wanna go that route?

**Closed** 2022-12-14 01:54 UTC
Labels: cli

**Comment by kptkin** [comment] 2023-01-25 03:15
> Got it, thanks so much! What's the benefit of using the service if I wanna go that route?

For everything multiprocessing, it should work much better and it has some features that are not supported in the non-service case, like logging to the same run from multiple processes for example.
