### ISSUE TITLE
[Q] Is there a way to log in the past?

### ISSUE THREAD

**Issue by amitabe** [wandb/wandb#6077] opened 2023-08-15 14:23 UTC
I'm training a model with an evaluation code whose execution time depends on the model. So It can happen that the evaluation code of iteration 50 will finish sooner than that of iteration 20.

I'm logging both training data and evaluation data using `wandb.log(..., step=iteration)`. My problem is that I can't log the data coherently, since `step` must be increasing (so I can't log evaluation data of iteration 50 and only then for iteration 20).
If I drop the `step` argument, the data is not coherent in the UI - I see the result of iteration 50 before that of iteration 20.

Is any workaround for this?
Also, why `step` must be increasing? Can't the data be rearranged in the server side?

**Comment by nate-wandb** [comment] 2023-08-21 18:20
Hi @amitabe, have you seen this [example](https://docs.wandb.ai/guides/track/log/customize-logging-axes#customize-axes) of using the define_metric() workflow to get around this? You could plot your metric against a custom step metric that you control yourself which will allow this.

I believe the reason previous steps are immutable is because this helps significantly with database performance.

**Comment by nate-wandb** [comment] 2023-08-23 21:40
@amitabe, I just wanted to follow up and make sure that answered your question or see if I could help with anything else?

**Comment by amitabe** [comment] 2023-09-20 14:42
It's a workaround, since for every object I want to log in the past (let's say an image), I need to have 2 different metrics - its x axis and the image axis. So I need to do:

```
wandb.log({
    "past_image": wandb.Image(img),
    "past_image_x": 20,
}, step=50)
wandb.define_metric("past_image", step_metric="past_image_x")
```

But If I have many of these, It would require me to track many of their x axis. Why can't I just do the following:
```
wandb.log({"past_image": wandb.Image(img)}, step=20) # when the current training step is 50
```

**Comment by amitabe** [comment] 2023-10-02 11:44
It seems that `define_metric` doens't work on media files like videos

**Comment by kptkin** [comment] 2024-04-12 23:26
closing this issue as duplicate of #6500

**Closed by kptkin** 2024-04-12 23:26 UTC
