### ISSUE TITLE
[Bug]: `wandb disabled` is a no-op

### ISSUE THREAD

**Issue by HekpoMaH** [wandb/wandb#8571] opened 2024-10-08 08:39 UTC
### Describe the bug

I am running `wandb disabled` before running a script, but things still get logged. I've tried both the old (deprecated) backend as well as the new one.
![Image](https://github.com/user-attachments/assets/48d53f1f-a1f7-472b-b9be-28ffd2daf1a8)

It even happens with the following (attached below) MWE:
![Image](https://github.com/user-attachments/assets/5cc70d51-3474-4025-b4c8-b31d1b870033)

MWE:
```python

import wandb

# Initialize a new W&B run
wandb.init(project="minimal-example")

# Log a single value (e.g., accuracy)
wandb.log({"accuracy": 0.95})

# Finish the run
wandb.finish()

```
wandb version: 0.18.3
python version: Python 3.10.15
OS (`uname -r`): 5.15.153.1-microsoft-standard-WSL2

**Comment by luisbergua** [comment] 2024-10-08 14:19
Hey @HekpoMaH, thank you so much for flagging this issue! I was able to reproduce it, so will report to our engineers and will let you know as soon as they provide any updates.

**Comment by kptkin** [comment] 2024-10-08 21:16
@HekpoMaH this is indeed a bug, but to overcome this i suggest for now just set the env variable `WANDB_MODE="disabled"` manually and i think it should disable wandb for you

**Comment by macio232** [comment] 2024-10-10 06:56
@kptkin negative, WANDB_MODE env variable is ignored. Can you point me to the last revision that doesn't have this bug? Thx in advance.

**Comment by HekpoMaH** [comment] 2024-10-10 07:22
@macio232 

Remember that
```bash
WANDB_MODE="disabled"
python mwe.py
```

Does nothing, as wandb mode is set only until you press Enter. You need to either do:
```bash
WANDB_MODE="disabled" python mwe.py
```
or (the 2nd one, I have tried)
```bash
export WANDB_MODE="disabled"
python mwe.py
```
Once exported for the terminal session, you don't need to set the variable again.

**Comment by macio232** [comment] 2024-10-10 07:23
`WANDB_MODE="disabled" python mwe.py` - exactly what I am using. Not doing the job since upgrade to `0.18.3`

**Comment by HekpoMaH** [comment] 2024-10-10 07:26
![Image](https://github.com/user-attachments/assets/10122eec-6e0f-4bab-b86a-3d954075e379)
![Image](https://github.com/user-attachments/assets/fb37e538-08f8-40aa-8a27-cffd48d4273a)
🤷 

I guess wandb people can tell more what's going on

**Comment by macio232** [comment] 2024-10-10 07:37
EDIT: when passing `settings` to `wandb.init`, the env variable gets ignored

**Comment by luisbergua** [comment] 2024-10-10 09:21
Hey @HekpoMaH @macio232, thank you so much for sharing these details! This is being actively investigated but in the meantime, using `wandb.init(mode="disabled")` should work. Would you mind confirming if this is the case?

**Comment by kptkin** [comment] 2024-10-11 00:47
> ![Image](https://github.com/user-attachments/assets/10122eec-6e0f-4bab-b86a-3d954075e379) ![Image](https://github.com/user-attachments/assets/fb37e538-08f8-40aa-8a27-cffd48d4273a) 🤷
> 
> I guess wandb people can tell more what's going on

@HekpoMaH it seems to work as expected? what is the issue you are having when you set the env variable to disabled it disables wandb when you don't it won't.

**Comment by macio232** [comment] 2024-10-11 14:55
@kptkin it didn't work as expected for me. Because I was passing `settings` to `wandb.init` (see https://github.com/wandb/wandb/issues/8571#issuecomment-2404305655). Apparently, with the bug, the env variable gets ignore in such case.

There is also a problem with `wandb.watch` when using WANDB_MODE="disabled"

```
  File "[...]/experiments/scripts/train.py", line 153, in main
    wandb.watch(
  File [...]/lib/python3.12/site-packages/wandb/sdk/wandb_watch.py", line 105, in watch
    wandb.run._torch.add_log_parameters_hook(
    ^^^^^^^^^^^^^^^^
  File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 931, in _torch
    if self._torch_history is None:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Run' object has no attribute '_torch_history'
```

**Comment by kptkin** [comment] 2024-10-11 16:05
> [@kptkin](https://github.com/kptkin) it didn't work as expected for me. Because I was passing `settings` to `wandb.init` (see [#8571 (comment)](https://github.com/wandb/wandb/issues/8571#issuecomment-2404305655)). Apparently, with the bug, the env variable gets ignore in such case.
> 
> There is also a problem with `wandb.watch` when using WANDB_MODE="disabled"
> 
> ```
>   File "[...]/experiments/scripts/train.py", line 153, in main
>     wandb.watch(
>   File [...]/lib/python3.12/site-packages/wandb/sdk/wandb_watch.py", line 105, in watch
>     wandb.run._torch.add_log_parameters_hook(
>     ^^^^^^^^^^^^^^^^
>   File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 931, in _torch
>     if self._torch_history is None:
>        ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Run' object has no attribute '_torch_history'
> ```

@macio232 In order to help debug this issue, could you please provide a small reproduction. How you run the script, what arguments you pass to init and what wandb functions you use? Thanks for the help

**Comment by macio232** [comment] 2024-10-12 18:04
`./mwe.py`:

```python
import wandb

# Initialize a new W&B run
wandb.init(
    project="minimal-example",
    settings=wandb.Settings(
        start_method="fork",
    ),
)

# Log a single value (e.g., accuracy)
wandb.log({"accuracy": 0.95})

# Finish the run
wandb.finish()
```
Execution:

```bash
❯ WANDB_MODE=disabled python ./mwe.py
wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: [...]. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.18.3
wandb: Run data is saved locally in [...]/wandb/run-20241012_200051-d2dmugsg
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run solar-sponge-1
wandb: ⭐️ View project at https://wandb.ai/[...]/minimal-example
wandb: 🚀 View run at https://wandb.ai/[...]/minimal-example/runs/d2dmugsg
wandb:                                                                                
wandb: 
wandb: Run history:
wandb: accuracy ▁
wandb: 
wandb: Run summary:
wandb: accuracy 0.95
wandb: 
wandb: 🚀 View run solar-sponge-1 at: https://wandb.ai/[...]/minimal-example/runs/d2dmugsg
wandb: ⭐️ View project at: https://wandb.ai/[...]/minimal-example
wandb: Synced 4 W&B file(s), 0 media file(s), 3 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20241012_200051-d2dmugsg/logs
```

**Comment by macio232** [comment] 2024-10-14 15:38
> [@kptkin](https://github.com/kptkin) it didn't work as expected for me. Because I was passing `settings` to `wandb.init` (see [#8571 (comment)](https://github.com/wandb/wandb/issues/8571#issuecomment-2404305655)). Apparently, with the bug, the env variable gets ignore in such case.
> 
> There is also a problem with `wandb.watch` when using WANDB_MODE="disabled"
> 
> ```
>   File "[...]/experiments/scripts/train.py", line 153, in main
>     wandb.watch(
>   File [...]/lib/python3.12/site-packages/wandb/sdk/wandb_watch.py", line 105, in watch
>     wandb.run._torch.add_log_parameters_hook(
>     ^^^^^^^^^^^^^^^^
>   File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 931, in _torch
>     if self._torch_history is None:
>        ^^^^^^^^^^^^^^^^^^^
> AttributeError: 'Run' object has no attribute '_torch_history'
> ```

In fact, the last version for which this doesn't happen is `0.16.6`. Does this deserve a separate issue? @kptkin

**Comment by kptkin** [comment] 2024-10-14 19:54
> > [@kptkin](https://github.com/kptkin) it didn't work as expected for me. Because I was passing `settings` to `wandb.init` (see [#8571 (comment)](https://github.com/wandb/wandb/issues/8571#issuecomment-2404305655)). Apparently, with the bug, the env variable gets ignore in such case.
> > There is also a problem with `wandb.watch` when using WANDB_MODE="disabled"
> > ```
> >   File "[...]/experiments/scripts/train.py", line 153, in main
> >     wandb.watch(
> >   File [...]/lib/python3.12/site-packages/wandb/sdk/wandb_watch.py", line 105, in watch
> >     wandb.run._torch.add_log_parameters_hook(
> >     ^^^^^^^^^^^^^^^^
> >   File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 931, in _torch
> >     if self._torch_history is None:
> >        ^^^^^^^^^^^^^^^^^^^
> > AttributeError: 'Run' object has no attribute '_torch_history'
> > ```
> 
> In fact, the last version for which this doesn't happen is `0.16.6`. Does this deserve a separate issue? [@kptkin](https://github.com/kptkin)

yep, we removed the RunDisabled class and now we only have Run class and i think this is the source for this issue, it would be good to track it separately.

**Comment by kptkin** [comment] 2024-10-30 00:00
Closing this issue as all the above missing functions were added, if there another issues with disabled mode please open a new issue and we will address it. thanks!

**Closed** 2024-10-29 23:59 UTC
Labels: ty:bug, a:sdk, c:sdk:code-quality
