### ISSUE TITLE
[Bug-App]: grouping no longer works like it used to a few days ago

### ISSUE THREAD

**Issue by ronuchit** [wandb/wandb#8731] opened 2024-10-30 03:17 UTC
### Describe the bug

It seems there is some error where grouping is no longer working on the wandb plots. I attach an example from my project page:
![Image](https://github.com/user-attachments/assets/cce3a00d-4772-47bb-a768-811cc88271dc)

You can see that only one curve shows up and it is labeled with `-` for the learning rate. However, I would expect there to be 3 curves here, one for each learning rate value. This is how wandb has always worked for me in the past.

**Comment by ericchen321** [comment] 2024-10-30 03:29
Same issue here:

![Image](https://github.com/user-attachments/assets/1d625825-8045-4dd1-9222-450f6424c4cb)

**Comment by misterguick** [comment] 2024-10-30 13:41
Same issue here.

 ![Image](https://github.com/user-attachments/assets/0cd31033-2709-4784-898d-eb7ef161650c)

Are you guys testing in production ?

**Comment by luisbergua** [comment] 2024-10-30 16:38
Hey all, thanks for flagging this, and apologies about the issue! I just tested on my side but was unable to reproduce the issue![Image](https://github.com/user-attachments/assets/8381dd9e-fb5c-4c19-ae7f-24f4e980dfaf)
Would it be possible to share a link to any of your projects so I can take a look?

**Comment by hawk-li** [comment] 2024-10-30 16:40
My temporary workaround was to set the point aggregation method from full fidelity to random sampling.

**Comment by luisbergua** [comment] 2024-10-30 16:44
Thanks for sharing this @hawk-li! I'm checking with our engineers in case there's any recent PR that caused the issue, but would you have any problems with sharing a project example so I can take a look?

**Comment by ronuchit** [comment] 2024-10-30 16:54
sorry, my project is private! confirmed that switching the point aggregation method from full fidelity to random sampling resolves the issue.

**Comment by luisbergua** [comment] 2024-10-30 17:40
Thanks for confirming this! We identified the issue and are working on a fix for it. I'll let you know as soon as it's deployed

**Comment by luisbergua** [comment] 2024-10-31 18:11
Hey all, thanks for your patience! There was an issue on our end when grouping by config parameters, but our engineers already deployed a fix for it so you should now see all the lines. Please let me know if this isn't the case!

**Comment by xy9485** [comment] 2024-11-06 23:11
> Hey all, thanks for your patience! There was an issue on our end when grouping by config parameters, but our engineers already deployed a fix for it so you should now see all the lines. Please let me know if this isn't the case!

Still having the issue, not solved on my side. Again, switching from full fidelity to random sampling resolves the issue, as a temporary solution.

**Comment by xy9485** [comment] 2024-11-07 12:26
> Still having the issue, not solved on my side. Again, switching from full fidelity to random sampling resolves the issue, as a temporary solution.

Also, even switching to random sampling, it only works without smoothing, once setting smoothing greater than one,  the shaded area will be wrongly rendered.

**Comment by luisbergua** [comment] 2024-11-07 13:23
Hey @xy9485, thanks for sharing this and apologies that this is still an issue. Would you mind sharing a link to your workspace? I would like to take a look at it

**Comment by xy9485** [comment] 2024-11-07 17:21
> Hey [@xy9485](https://github.com/xy9485), thanks for sharing this and apologies that this is still an issue. Would you mind sharing a link to your workspace? I would like to take a look at it

Here is the url for an example workspace: https://wandb.ai/team-yuan/testing_groups/workspace

**Comment by luisbergua** [comment] 2024-11-07 21:20
Hey @xy9485, thanks for the link! This should be fixed now, would you mind confirming?

**Comment by xy9485** [comment] 2024-11-07 21:27
> Hey [@xy9485](https://github.com/xy9485), thanks for the link! This should be fixed now, would you mind confirming?
 Hi @luisbergua, when using Full fidelity with non-zero smoothing, the problem is fixed. However, Random sampling with non-zero smoothing still has the issue.

**Comment by luisbergua** [comment] 2024-11-08 15:46
Thanks for flagging this @@xy9485!
* Random sampling with non-zero smoothing still has the issue. - I just tested but couldn't reproduce this issue, would you mind sharing a quick video of it or letting me know if I'm doing something wrong?![Image](https://github.com/user-attachments/assets/a6097cf3-92f3-4281-a486-93841248c120)

* New Issue: new experiments results with the same script are not being upload to web anymore, no error is reported.
Edit: it seems that it takes extremely long till the run to be seen on the web interface. - there had been some issues that might have caused this delay (see our [status page](https://status.wandb.com/)), so would you mind letting me know if this is still affecting you? If so, would it be possible to share a code example so I can reproduce this?

**Comment by xy9485** [comment] 2024-11-08 16:00
> Thanks for flagging this @[@xy9485](https://github.com/xy9485)!
> 
> * Random sampling with non-zero smoothing still has the issue. - I just tested but couldn't reproduce this issue, would you mind sharing a quick video of it or letting me know if I'm doing something wrong?![Image](https://github.com/user-attachments/assets/a6097cf3-92f3-4281-a486-93841248c120)

The issue is there if you choose running average as the smoothing option

**Comment by luisbergua** [comment] 2024-11-08 16:04
Just checked, but still seeing all groups, would you have any problems with sharing a video and the workspace where you see this issue?
https://github.com/user-attachments/assets/ab74a24c-1787-4da6-b59b-b7fe5af89e16

**Comment by luisbergua** [comment] 2024-11-13 13:02
Hey @xy9485, I'm so sorry, I initially misunderstood you. I can see the issue now, will raise it with our engineers.

**Comment by lrhammond** [comment] 2024-11-17 15:05
Flagging that I have a very similar issue: my four groups are displaying as one line. This is true for any combination of:

- Full fidelity or random sampling
- Smoothing or no smoothing

Random sampling does bring back the shaded error bars, but doesn't display the different groups separately.

Unfortunately my workspace is private so I can't share it directly.

**Comment by luisbergua** [comment] 2024-11-18 12:47
Hi @lrhammond, thanks for sharing this. Would you mind emailing support@wandb.com with a link to your workspace and a reference to this thread so I can take a look at it and see what's going on? The issue should have been fixed, so this might be a different thing

**Comment by luisbergua** [comment] 2024-11-20 14:28
Hey @lrhammond, just wanted to check if you already emailed support@wandb.com with a link to your workspace? I just checked and didn't see it, so wanted to confirm

**Closed** 2024-11-26 10:27 UTC
Labels: ty:bug, a:app
