### ISSUE TITLE
[CLI]: Opening runs leaks file pointers and semaphores

### ISSUE THREAD

**Issue by Exr0n** [wandb/wandb#3974] opened 2022-07-22 18:22 UTC
### Describe the bug

Reopening #1447 which was closed in a broad issue cleanup. 

Initializing wandb runs appears to leak file pointers, as after opening a few runs, the process crashes with "too many open files." Quitting the process with Control-C leads to the common leaked semaphore message (and thus may be unrelated?) 

My use case: I intend to sequentially launch a group of runs for K-folds cross-validation. Each group must be launched from the same Python file because that file is my sweeps entry point. However, I can't get through all the folds I need without crashing on "too many open files." 

I'm on `wandb=0.12.21`, Python 3.9.13, MacOS Big Sur 11.6. 

Code to reproduce:
```python
import wandb
for i in range(100):
    with wandb.init(entity='exr0nprojects', project='snap', group='useless'):
        print(f"run number {i}")
```

The "leaked semaphores" appears during the first run, but this may be happening because I've been testing in the same shell. The full error:
```shell
/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 54 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I got the "too many open files" error after the 18th run. The error message is quite long, but appears to just repeat the following segment:

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1043, in init
    run = wi.init()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 556, in init
    backend.ensure_launched()
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 220, in ensure_launched
    self.wandb_process.start()
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/util.py", line 450, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

The above exception was the direct cause of the following exception: [etc]
```

### Environment

WandB version: 0.12.21

OS: MacOS Big Sur 11.6

Python version: 3.9.13

Versions of relevant libraries: No other libraries are needed for reproduction.

**Comment by nate-wandb** [comment] 2022-07-25 18:50
Hi @Exr0n, thank you for reporting this. I was unsuccessful in replicating the issue using the following code:

```
import wandb 
import psutil

def print_file_info()::
    proc = psutil.Process()
    print('Num open files: %s' % len(proc.open_files()))

for i in range(100): 
    with wandb.init(project='snap', group='useless'): 
        print(f"run number {i}") 
        print_file_info()
 ```
 The `print_file_info()` function never printed that it had more than 4 files open and I was able to finish all 100 iterations.
 
Do you happen to be using the `WANDB_START_METHOD` environment variable or any other custom way of running `wandb` that I may not be using in my replication?
 
 Thank you,
 Nate

**Comment by Exr0n** [comment] 2022-07-26 22:15
Hi @nate-wandb thanks for the swift response! I got the error after the 19th run again using your version of the script.

Curiously, `print_file_info()` always showed the number of open files as 5 in [Alacritty](https://github.com/alacritty/alacritty) (the terminal emulator that I use), and this never increased as more runs were created. In Terminal.app, the number of open files stays at a constant 2, but the script still crashes after the 19th run. Maybe the open files are owned by a spawned process or thread?

It's also possible that I have a lower-than-default process limit because this laptop is provided by my employer and has management profiles installed. It still seems like *something*s leaking though...

**Comment by TheoEhrenborg** [comment] 2022-08-09 12:58
With the following code, I get  `OSError: [Errno 24] Too many open files` after the 202nd model is created:
```
import wandb
while True:
    # Create new model here and pass its config to wandb.init
    wandb.init(project="project-bug-testing") 
    for x in range(100):
        wandb.log({"foo": 5}) 
        # Log data for each of 100 batches
    wandb.finish()
    # Save data for this model before moving on to next model
```
The time until failure probably depends on how many open files the computer allows. When I run `ulimit -n`, it tells me that my limit for open files is 1024.

**Comment by nate-wandb** [comment] 2022-08-09 17:46
Hi @Exr0n, sorry for the delay here. I was finally able to replicate this after setting my default number of files allowed to be opened with `ulimit -n 100`. My defaults were set to 1048575 originally which was why I could not replicate. I also can confirm what you are seeing that it appears that these files are being held by an external process that `wandb` spins up. I'll report this to our engineering team. 

In the meantime you should be able to set your limit higher with `ulimit -n <number_of_file_handles_you_need>` to get you unblocked for the time being. 

I'll follow up once we are able to come up with a fix on this and figure out what the issue is.

Thank you,
Nate

**Comment by owlesia** [comment] 2022-09-18 16:58
I also encounter the error "Too many open files" on mac. Could you let me know if there are any updates? besides changing the limit of open files

**Comment by tristanengst** [comment] 2023-01-31 08:23
Any update on this?

**Comment by owlesia** [comment] 2023-01-31 14:05
> Any update on this?

I rolled back to wandb 0.12.21 and it seems to work fine.

**Comment by owlesia** [comment] 2023-01-31 19:29
I see, thank you @nate-wandb. I haven't tried the latest version yet.

**Comment by tristanengst** [comment] 2023-02-01 07:15
@nate-wandb I was able to replicate the error with `wandb 0.13.9` in a hope that updating would fix the issue, and with a larger `ulimit` setting.

However, for me I think it was actually an issue with a PyTorch `DataLoader` that was somehow crashing my code and causing WandB workers to also crash. Following [https://github.com/pytorch/pytorch/issues/11201#issuecomment-586007563](https://github.com/pytorch/pytorch/issues/11201#issuecomment-586007563), I added the following two lines to the start of my code appears to have fixed my issue:
```
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy("file_system")
```

**Comment by n-kasatkin** [comment] 2023-02-02 08:00
Hi! I am using AWS SageMaker -- so I can't set ulimit. Pytorch Lightning 1.8.6 & Pytorch 1.12.1 & wandb 0.13.9.

I still getting this error `OSError: [Errno 24] Too many open files`.

I tried to set sharing strategy to "file_system" and even for each worker in dataloader suing worker_init_fn. Tried to wandb==0.12.21 and 0.13.9. 

This is hard to debug. Just want to bump this issue.

**Comment by nate-wandb** [comment] 2023-02-02 19:33
Thank you @tristanengst and @n-kasatkin for testing. It looks like we have this fixed in the `wandb` module but the issue still exists in the our PyTorch integration. 

Could either of you provide a minimal reproduction of the issue when using PyTorch or PTL? 

Thank you,
Nate

**Comment by n-kasatkin** [comment] 2023-02-15 10:23
The problem in my case was not related to wandb! 
I had an internal pytorchvideo bug, that prevented videos from closing.

**Closed** 2023-03-02 05:09 UTC
Labels: cli

**Comment by jxmorris12** [comment] 2023-05-09 02:44
This is still an issue, but I'm following on #2825

**Comment by eminb61** [comment] 2023-12-26 17:44
Problem still exists
