### ISSUE TITLE
Can't run weave getting started notebook locally

### ISSUE THREAD

**Issue by ahmadelsallab** [wandb/wandb#8011] opened 2024-07-25 09:37 UTC
### Describe the bug

Hi,
I'm trying to run the [Quick Start](https://wandb.github.io/weave/quickstart/) tutorial. It worked fine in [Google Colab notebook](https://colab.research.google.com/github/wandb/weave/blob/master/docs/intro_notebook.ipynb). 

But when I try to run on my PC I get the following error:
```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[15], line 24
     17     return response.choices[0].message.content
     20 sentence = """I watched as a Tyrannosaurus rex (T. rex) chased after a Triceratops (Trike), \
     21 both carnivore and herbivore locked in an ancient dance. Meanwhile, a gentle giant \
     22 Brachiosaurus (Brachi) calmly munched on treetops, blissfully unaware of the chaos below."""
---> 24 result = extract_dinos(sentence)
     25 print(result)

Cell In[15], line 2, in extract_dinos(sentence)
      1 def extract_dinos(sentence: str) -> dict:
----> 2     response = client.chat.completions.create(
      3         model="gpt-4o",
      4         messages=[
      5             {
      6                 "role": "system",
      7                 "content": """In JSON format extract a list of `dinosaurs`, with their `name`, 
      8 their `common_name`, and whether its `diet` is a herbivore or carnivore"""
      9             },
     10             {
     11                 "role": "user",
     12                 "content": sentence
     13             }
     14             ],
     15             response_format={ "type": "json_object" }
     16         )
     17     return response.choices[0].message.content

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\op.py:336, in op.<locals>.op_deco.<locals>.create_wrapper.<locals>.wrapper(*args, **kwargs)
    334 if client_context.weave_client.get_weave_client() is None:
    335     return func(*args, **kwargs)
--> 336 call = _create_call(wrapper, *args, **kwargs)  # type: ignore
    337 res, _ = _execute_call(wrapper, call, *args, **kwargs)  # type: ignore
    338 return res

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\op.py:159, in _create_call(func, *args, **kwargs)
    156 client._save_nested_objects(inputs_with_defaults)
    157 attributes = call_attributes.get()
--> 159 return client.create_call(
    160     func,
    161     inputs_with_defaults,
    162     parent_call,
    163     attributes=attributes,
    164 )

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace_sentry.py:211, in Sentry.watch.<locals>.watch_dec.<locals>.wrapper(*args, **kwargs)
    208 @functools.wraps(func)
    209 def wrapper(*args: Any, **kwargs: Any) -> Any:
    210     try:
--> 211         return func(*args, **kwargs)
    212     except Exception as e:
    213         self.exception(e)

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:507, in WeaveClient.create_call(self, op, inputs, parent, attributes, display_name, use_stack)
    505 if isinstance(op, Op):
    506     unbound_op = maybe_unbind_method(op)
--> 507     op_def_ref = self._save_op(unbound_op)
    508     op_str = op_def_ref.uri()
    509 else:

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:846, in WeaveClient._save_op(self, op, name)
    844 if name is None:
    845     name = op.name
--> 846 op_def_ref = self._save_object_basic(op, name)
    848 # setattr(op, "ref", op_def_ref) fails here
    849 # op.ref = op_def_ref fails here
    850 # Seems to be the only way to set the ref on the op
    851 op.__dict__["ref"] = op_def_ref

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:744, in WeaveClient._save_object_basic(self, val, name, branch)
    742 if isinstance(val, ObjectRef):
    743     return val
--> 744 json_val = to_json(val, self._project_id(), self.server)
    746 response = self.server.obj_create(
    747     ObjCreateReq(
    748         obj=ObjSchemaForInsert(
   (...)
    753     )
    754 )
    755 ref: Ref

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\serialize.py:39, in to_json(obj, project_id, server)
     37 file_digests = {}
     38 for name, val in encoded["files"].items():
---> 39     file_response = server.file_create(
     40         FileCreateReq(project_id=project_id, name=name, content=val)
     41     )
     42     file_digests[name] = file_response.digest
     43 result = {
     44     "_type": encoded["_type"],
     45     "weave_type": encoded["weave_type"],
     46     "files": file_digests,
     47 }

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:336, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    334 copy = self.copy()
    335 wrapped_f.statistics = copy.statistics  # type: ignore[attr-defined]
--> 336 return copy(f, *args, **kw)

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:475, in Retrying.__call__(self, fn, *args, **kwargs)
    473 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    474 while True:
--> 475     do = self.iter(retry_state=retry_state)
    476     if isinstance(do, DoAttempt):
    477         try:

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:376, in BaseRetrying.iter(self, retry_state)
    374 result = None
    375 for action in self.iter_state.actions:
--> 376     result = action(retry_state)
    377 return result

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:398, in BaseRetrying._post_retry_check_actions.<locals>.<lambda>(rs)
    396 def _post_retry_check_actions(self, retry_state: "RetryCallState") -> None:
    397     if not (self.iter_state.is_explicit_retry or self.iter_state.retry_run_result):
--> 398         self._add_action_func(lambda rs: rs.outcome.result())
    399         return
    401     if self.after is not None:

File C:\ProgramData\anaconda3\envs\finetuning\Lib\concurrent\futures\_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File C:\ProgramData\anaconda3\envs\finetuning\Lib\concurrent\futures\_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:478, in Retrying.__call__(self, fn, *args, **kwargs)
    476 if isinstance(do, DoAttempt):
    477     try:
--> 478         result = fn(*args, **kwargs)
    479     except BaseException:  # noqa: B902
    480         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace_server\remote_http_trace_server.py:397, in RemoteHTTPTraceServer.file_create(self, req)
    380 @tenacity.retry(
    381     stop=tenacity.stop_after_delay(REMOTE_REQUEST_RETRY_DURATION),
    382     wait=tenacity.wait_exponential_jitter(
   (...)
    389 )
    390 def file_create(self, req: tsi.FileCreateReq) -> tsi.FileCreateRes:
    391     r = requests.post(
    392         self.trace_server_url + "/files/create",
    393         auth=self._auth,
    394         data={"project_id": req.project_id},
    395         files={"file": (req.name, req.content)},
    396     )
--> 397     r.raise_for_status()
    398     return tsi.FileCreateRes.model_validate(r.json())

File C:\ProgramData\anaconda3\envs\finetuning\Lib\site-packages\requests\models.py:1024, in Response.raise_for_status(self)
   1019     http_error_msg = (
   1020         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1021     )
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://trace.wandb.ai/files/create
```
Here's the piece of code that caused the issue:
```python

import weave
from openai import OpenAI

client = OpenAI(api_key="...")

# Weave will track the inputs, outputs and code of this function
@weave.op()
def extract_dinos(sentence: str) -> dict:
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": """In JSON format extract a list of `dinosaurs`, with their `name`, 
their `common_name`, and whether its `diet` is a herbivore or carnivore"""
            },
            {
                "role": "user",
                "content": sentence
            }
            ],
            response_format={ "type": "json_object" }
        )
    return response.choices[0].message.content


# Initialise the weave project
weave.init('jurassic-park')

sentence = """I watched as a Tyrannosaurus rex (T. rex) chased after a Triceratops (Trike), \
both carnivore and herbivore locked in an ancient dance. Meanwhile, a gentle giant \
Brachiosaurus (Brachi) calmly munched on treetops, blissfully unaware of the chaos below."""

result = extract_dinos(sentence)
print(result)

```

### Environment

WandB version: 0.17.5

OS: Windows 11

Python version: 3.12.3

Versions of relevant libraries:
Name: weave
Version: 0.50.11
Name: openai
Version: 1.37.0

### Additional Context

Here's my environment:
```
ace_tools==0.0
adal==1.2.7
aiofiles==24.1.0
aiohttp==3.9.5
aioprocessing==2.0.1
aiosignal==1.3.1
altair==5.3.0
analytics-python==1.2.9
annotated-types==0.7.0
anyio==4.4.0
argcomplete==3.3.0
asttokens @ file:///opt/conda/conda-bld/asttokens_1646925590279/work
attrs==23.2.0
azure-ai-ml==1.16.0
azure-common==1.1.28
azure-core==1.30.1
azure-graphrbac==0.61.1
azure-identity==1.16.0
azure-keyvault-secrets==4.8.0
azure-mgmt-authorization==4.0.0
azure-mgmt-containerregistry==10.3.0
azure-mgmt-core==1.4.0
azure-mgmt-keyvault==10.3.0
azure-mgmt-network==25.4.0
azure-mgmt-resource==23.1.1
azure-mgmt-storage==21.1.0
azure-search-documents==11.4.0
azure-storage-blob==12.20.0
azure-storage-file-datalake==12.15.0
azure-storage-file-share==12.16.0
azureml-core==1.56.0
azureml-dataprep==5.1.6
azureml-dataprep-native==41.0.0
azureml-dataprep-rslex==2.22.2
azureml-fsspec==1.3.1
backoff==2.2.1
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==4.1.3
blinker==1.8.2
cachetools==5.4.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==2.2.1
colorama @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/colorama_1699472650914/work
comm @ file:///C:/b/abs_67a8058udb/croot/comm_1709322909844/work
contextlib2==21.6.0
contourpy==1.2.1
cryptography==42.0.7
cycler==0.12.1
datasets==2.20.0
debugpy @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/debugpy_1699554994633/work
decorator @ file:///opt/conda/conda-bld/decorator_1643638310831/work
dill==0.3.8
distro==1.9.0
docker==7.1.0
docker-pycreds==0.4.0
emoji==2.12.1
et-xmlfile==1.1.0
executing @ file:///opt/conda/conda-bld/executing_1646925071911/work
filelock==3.15.4
Flask==3.0.3
fonttools==4.53.1
frozenlist==1.4.1
fsspec==2024.5.0
gitdb==4.0.11
GitPython==3.1.43
google-api-core==2.19.0
google-auth==2.29.0
googleapis-common-protos==1.63.0
gql==3.5.0
graphql-core==3.2.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.23.4
humanfriendly==10.0
idna==3.7
intel-openmp==2021.4.0
ipykernel @ file:///C:/b/abs_c2u94kxcy6/croot/ipykernel_1705933907920/work
ipython @ file:///C:/b/abs_b6pfgmrqnd/croot/ipython_1704833422163/work
isodate==0.6.1
itsdangerous==2.2.0
janus==1.0.0
jedi @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/jedi_1699484554909/work
jeepney==0.8.0
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
jsonpickle==3.0.4
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter_client @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/jupyter_client_1701796382758/work
jupyter_core @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/jupyter_core_1701796658071/work
kiwisolver==1.4.5
knack==0.11.0
loguru==0.7.2
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.2
matplotlib==3.9.1
matplotlib-inline @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/matplotlib-inline_1699484796387/work
mdurl==0.1.2
mkl==2021.4.0
mldesigner==0.1.0b12
mpmath==1.3.0
msal==1.28.0
msal-extensions==1.1.0
msrest==0.7.1
msrestazure==0.6.4
multidict==6.0.5
multiprocess==0.70.16
ndg-httpsclient==0.5.1
nest-asyncio @ file:///C:/b/abs_65d6lblmoi/croot/nest-asyncio_1708532721305/work
networkx==3.3
numpy==1.26.4
oauthlib==3.2.2
openai==1.37.0
opencensus==0.11.4
opencensus-context==0.1.3
opencensus-ext-azure==1.1.13
opencensus-ext-logging==0.1.1
openpyxl==3.1.3
packaging @ file:///C:/b/abs_cc1h2xfosn/croot/packaging_1710807447479/work
pandas==2.2.2
paramiko==3.4.0
parso @ file:///opt/conda/conda-bld/parso_1641458642106/work
pathspec==0.12.1
pdf2image==1.17.0
pillow==10.3.0
pkginfo==1.11.0
platformdirs @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/platformdirs_1701797392447/work
portalocker==2.8.2
prompt-toolkit @ file:///C:/b/abs_68uwr58ed1/croot/prompt-toolkit_1704404394082/work
proto-plus==1.23.0
protobuf==5.27.2
psutil @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/psutil_1699482842340/work
pure-eval @ file:///opt/conda/conda-bld/pure_eval_1646925070566/work
pyarrow==16.1.0
pyarrow-hotfix==0.6
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycparser==2.22
pydantic==2.7.2
pydantic_core==2.18.3
pydash==8.0.1
pydeck==0.9.1
Pygments @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/pygments_1699474141968/work
PyJWT==2.8.0
PyMuPDF==1.24.5
PyMuPDFb==1.24.3
PyNaCl==1.5.0
pyOpenSSL==24.1.0
pyparsing==3.1.2
pyreadline3==3.4.1
PySocks==1.7.1
python-dateutil @ file:///C:/b/abs_3au_koqnbs/croot/python-dateutil_1716495777160/work
python-dotenv==1.0.1
python-json-logger==2.0.7
pytz==2024.1
pywin32==305.1
PyYAML==6.0.1
pyzmq @ file:///C:/b/abs_89aq69t0up/croot/pyzmq_1705605705281/work
referencing==0.35.1
regex==2024.5.15
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
rich==13.7.1
rpds-py==0.18.1
rsa==4.9
safetensors==0.4.3
scikit-learn==1.5.0
scipy==1.13.1
seaborn==0.13.2
SecretStorage==3.3.3
sentence-transformers==3.0.0
sentry-sdk==2.11.0
set-env-colab-kaggle-dotenv==0.1.2
setproctitle==1.3.3
setuptools==69.5.1
six @ file:///tmp/build/80754af9/six_1644875935023/work
smmap==5.0.1
sniffio==1.3.1
stack-data @ file:///opt/conda/conda-bld/stack_data_1646927590127/work
streamlit==1.36.0
strictyaml==1.7.3
sympy==1.12.1
tabulate==0.9.0
tbb==2021.12.0
tenacity==8.5.0
threadpoolctl==3.5.0
tiktoken==0.7.0
tokenizers==0.19.1
toml==0.10.2
toolz==0.12.1
torch==2.3.0
tornado @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/tornado_1699496839511/work
tqdm==4.66.4
traitlets @ file:///C:/Users/dev-admin/perseverance-python-buildout/croot/traitlets_1699474642113/work
transformers==4.41.2
typing_extensions==4.12.1
tzdata==2024.1
urllib3==2.2.1
wandb==0.17.5
watchdog==4.0.1
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
weave==0.50.11
Werkzeug==3.0.3
wheel==0.43.0
win32-setctime==1.1.0
xxhash==3.4.1
yarl==1.9.4
```

**Comment by jamie-rasmussen** [comment] 2024-07-25 16:01
Hello, I'd be happy to try to help you with this. My current theory is that there was an error when two of our backend services were communicating. Could you tell me if this is consistently reproducible for you or intermittent?

**Comment by ahmadelsallab** [comment] 2024-07-25 16:30
It is consistent

**Comment by ahmadelsallab** [comment] 2024-07-29 05:39
Any update on this issue?
Thanks

**Comment by jamie-rasmussen** [comment] 2024-07-29 14:30
We've identified two causes of the Unauthorized error so far, but we don't think either of them applies to your case.
1. There was a brief backend service communication problem during some write authorization checks.
2. We identified a problem with service accounts accessing Weave.

One thing you could try is running "wandb login --relogin" and letting us know what that shows and whether the problem persists.

Another thing we could try is having you upgrade to our latest release, weave 0.50.12. That supports an environment variable designed to help us debug this sort of situation. You could add this to your script:
```
import os
os.environ["WEAVE_DEBUG_HTTP"] = "1"
```
And the resulting output should give us a better idea of if there is a problem with the headers your client is sending.

**Comment by jamie-rasmussen** [comment] 2024-07-29 15:26
Actually, I just discovered a Windows-only bug that I think might be the cause of your problem. apikeys on Windows are typically kept in `~/_netrc` instead of `~/.netrc`. Most of our code checks both places but some authentication code in Weave wasn't. I've got a proposed fix up at https://github.com/wandb/weave/pull/2039

**Comment by ahmadelsallab** [comment] 2024-07-30 07:30
@jamie-rasmussen Thanks for the update and follow up.

1- Upgrading to `weave=0.50.12` didn't work.

I set the debug var as you said:
```
import os
os.environ["WEAVE_DEBUG_HTTP"] = "1"
```

Here's the output:
Running the following init code:
```
import weave
# Initialise the weave project
weave.init('jurassic-park')
```
The output is:
```
Please login to Weights & Biases (https://wandb.ai/) to continue:
---------------------
Time: 10:25:42.945668
Thread ID: 11480
Method: GET
URL: https://trace.wandb.ai/server_info
Headers:
  User-Agent: 
python-requests/2.32.3
  Accept-Encoding: 
gzip, deflate
  Accept: 
*/*
  Connection: 
keep-alive
Body:
  None
----- Response below -----
Elapsed Time: 0.47 seconds
Status Code: 200
Reason: OK
Headers:
  content-type: 
application/json
  x-cloud-trace-context: 
21b8b242b36cc2b92a0ad5f9470cd0ce;o=1
  date: 
Tue, 30 Jul 2024 07:25:43 GMT
  server: 
Google Frontend
  Content-Length: 
46
  via: 
1.1 google
  Alt-Svc: 
h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Body:
  1 {
  2     "min_required_weave_python_version": "0.46.0"
  3 }
Logged in as Weights & Biases user: ahmadelsallab.
View Weave data at https://wandb.ai/ahmadelsallab/jurassic-park/weave
<weave.weave_client.WeaveClient at 0x1f5451dc8f0>
```
Running:
```
import weave

# Weave will track the inputs, outputs and code of this function
@weave.op()
def extract_dinos(sentence: str) -> dict:
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": """In JSON format extract a list of `dinosaurs`, with their `name`, 
their `common_name`, and whether its `diet` is a herbivore or carnivore"""
            },
            {
                "role": "user",
                "content": sentence
            }
            ],
            response_format={ "type": "json_object" }
        )
    return response.choices[0].message.content


# Initialise the weave project
#weave.init('jurassic-park')

sentence = """I watched as a Tyrannosaurus rex (T. rex) chased after a Triceratops (Trike), \
both carnivore and herbivore locked in an ancient dance. Meanwhile, a gentle giant \
Brachiosaurus (Brachi) calmly munched on treetops, blissfully unaware of the chaos below."""

result = extract_dinos(sentence)
print(result)
```

I get an error + new debug output as follows:
```
---------------------
Time: 10:25:44.194407
Thread ID: 11480
Method: POST
URL: https://trace.wandb.ai/files/create
Headers:
  User-Agent: 
python-requests/2.32.3
  Accept-Encoding: 
gzip, deflate
  Accept: 
*/*
  Connection: 
keep-alive
  Content-Length: 
874
  Content-Type: 
multipart/form-data; boundary=958220b639a5cdb3b19af48b8e25d4dd
Body:
--958220b639a5cdb3b19af48b8e25d4dd
Content-Disposition: form-data; name="project_id"

ahmadelsallab/jurassic-park
--958220b639a5cdb3b19af48b8e25d4dd
Content-Disposition: form-data; name="file"; filename="obj.py"

import weave

@weave.op()
def extract_dinos(sentence: str) -> dict:
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": """In JSON format extract a list of `dinosaurs`, with their `name`, 
their `common_name`, and whether its `diet` is a herbivore or carnivore"""
            },
            {
                "role": "user",
                "content": sentence
            }
            ],
            response_format={ "type": "json_object" }
        )
    return response.choices[0].message.content

--958220b639a5cdb3b19af48b8e25d4dd--

----- Response below -----
Elapsed Time: 0.24 seconds
Status Code: 401
Reason: Unauthorized
Headers:
  www-authenticate: 
Basic
  content-type: 
application/json
  x-cloud-trace-context: 
d952b356bdf57d3fab51ac4091dde3b9;o=1
  date: 
Tue, 30 Jul 2024 07:25:44 GMT
  server: 
Google Frontend
  Content-Length: 
30
  via: 
1.1 google
  Alt-Svc: 
h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
Body:
  1 {
  2     "detail": "Not authenticated"
  3 }
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[15], line 31
     24 # Initialise the weave project
     25 #weave.init('jurassic-park')
     27 sentence = """I watched as a Tyrannosaurus rex (T. rex) chased after a Triceratops (Trike), \
     28 both carnivore and herbivore locked in an ancient dance. Meanwhile, a gentle giant \
     29 Brachiosaurus (Brachi) calmly munched on treetops, blissfully unaware of the chaos below."""
---> 31 result = extract_dinos(sentence)
     32 print(result)

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\op.py:336, in op.<locals>.op_deco.<locals>.create_wrapper.<locals>.wrapper(*args, **kwargs)
    334 if client_context.weave_client.get_weave_client() is None:
    335     return func(*args, **kwargs)
--> 336 call = _create_call(wrapper, *args, **kwargs)  # type: ignore
    337 res, _ = _execute_call(wrapper, call, *args, **kwargs)  # type: ignore
    338 return res

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\op.py:159, in _create_call(func, *args, **kwargs)
    156 client._save_nested_objects(inputs_with_defaults)
    157 attributes = call_attributes.get()
--> 159 return client.create_call(
    160     func,
    161     inputs_with_defaults,
    162     parent_call,
    163     attributes=attributes,
    164 )

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace_sentry.py:211, in Sentry.watch.<locals>.watch_dec.<locals>.wrapper(*args, **kwargs)
    208 @functools.wraps(func)
    209 def wrapper(*args: Any, **kwargs: Any) -> Any:
    210     try:
--> 211         return func(*args, **kwargs)
    212     except Exception as e:
    213         self.exception(e)

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:507, in WeaveClient.create_call(self, op, inputs, parent, attributes, display_name, use_stack)
    505 if isinstance(op, Op):
    506     unbound_op = maybe_unbind_method(op)
--> 507     op_def_ref = self._save_op(unbound_op)
    508     op_str = op_def_ref.uri()
    509 else:

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:846, in WeaveClient._save_op(self, op, name)
    844 if name is None:
    845     name = op.name
--> 846 op_def_ref = self._save_object_basic(op, name)
    848 # setattr(op, "ref", op_def_ref) fails here
    849 # op.ref = op_def_ref fails here
    850 # Seems to be the only way to set the ref on the op
    851 op.__dict__["ref"] = op_def_ref

File ~\AppData\Roaming\Python\Python312\site-packages\weave\weave_client.py:744, in WeaveClient._save_object_basic(self, val, name, branch)
    742 if isinstance(val, ObjectRef):
    743     return val
--> 744 json_val = to_json(val, self._project_id(), self.server)
    746 response = self.server.obj_create(
    747     ObjCreateReq(
    748         obj=ObjSchemaForInsert(
   (...)
    753     )
    754 )
    755 ref: Ref

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace\serialize.py:39, in to_json(obj, project_id, server)
     37 file_digests = {}
     38 for name, val in encoded["files"].items():
---> 39     file_response = server.file_create(
     40         FileCreateReq(project_id=project_id, name=name, content=val)
     41     )
     42     file_digests[name] = file_response.digest
     43 result = {
     44     "_type": encoded["_type"],
     45     "weave_type": encoded["weave_type"],
     46     "files": file_digests,
     47 }

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:336, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    334 copy = self.copy()
    335 wrapped_f.statistics = copy.statistics  # type: ignore[attr-defined]
--> 336 return copy(f, *args, **kw)

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:475, in Retrying.__call__(self, fn, *args, **kwargs)
    473 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    474 while True:
--> 475     do = self.iter(retry_state=retry_state)
    476     if isinstance(do, DoAttempt):
    477         try:

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:376, in BaseRetrying.iter(self, retry_state)
    374 result = None
    375 for action in self.iter_state.actions:
--> 376     result = action(retry_state)
    377 return result

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:398, in BaseRetrying._post_retry_check_actions.<locals>.<lambda>(rs)
    396 def _post_retry_check_actions(self, retry_state: "RetryCallState") -> None:
    397     if not (self.iter_state.is_explicit_retry or self.iter_state.retry_run_result):
--> 398         self._add_action_func(lambda rs: rs.outcome.result())
    399         return
    401     if self.after is not None:

File C:\ProgramData\anaconda3\envs\finetuning\Lib\concurrent\futures\_base.py:449, in Future.result(self, timeout)
    447     raise CancelledError()
    448 elif self._state == FINISHED:
--> 449     return self.__get_result()
    451 self._condition.wait(timeout)
    453 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File C:\ProgramData\anaconda3\envs\finetuning\Lib\concurrent\futures\_base.py:401, in Future.__get_result(self)
    399 if self._exception:
    400     try:
--> 401         raise self._exception
    402     finally:
    403         # Break a reference cycle with the exception in self._exception
    404         self = None

File ~\AppData\Roaming\Python\Python312\site-packages\tenacity\__init__.py:478, in Retrying.__call__(self, fn, *args, **kwargs)
    476 if isinstance(do, DoAttempt):
    477     try:
--> 478         result = fn(*args, **kwargs)
    479     except BaseException:  # noqa: B902
    480         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File ~\AppData\Roaming\Python\Python312\site-packages\weave\trace_server\remote_http_trace_server.py:402, in RemoteHTTPTraceServer.file_create(self, req)
    385 @tenacity.retry(
    386     stop=tenacity.stop_after_delay(REMOTE_REQUEST_RETRY_DURATION),
    387     wait=tenacity.wait_exponential_jitter(
   (...)
    394 )
    395 def file_create(self, req: tsi.FileCreateReq) -> tsi.FileCreateRes:
    396     r = requests.post(
    397         self.trace_server_url + "/files/create",
    398         auth=self._auth,
    399         data={"project_id": req.project_id},
    400         files={"file": (req.name, req.content)},
    401     )
--> 402     r.raise_for_status()
    403     return tsi.FileCreateRes.model_validate(r.json())

File C:\ProgramData\anaconda3\envs\finetuning\Lib\site-packages\requests\models.py:1024, in Response.raise_for_status(self)
   1019     http_error_msg = (
   1020         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1021     )
   1023 if http_error_msg:
-> 1024     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://trace.wandb.ai/files/create
```

2- Renaming `~/_netrc` into `~/.netrc` worked. Thanks!

**Comment by jamie-rasmussen** [comment] 2024-07-30 12:11
Thank you again for the detailed information. The fix (https://github.com/wandb/weave/pull/2039) has been merged and will be part of the next Weave library release. We've been posting new releases approximately weekly. If you upgrade after that you should be able to remove the duplicate ~/.netrc file workaround. I'll close this ticket now. 

If you have additional feedback or error reports for Weave, posting them to its repo (https://github.com/wandb/weave) will help get them to our team quicker. We appreciate you trying Weave and helping us make it better!

**Closed by jamie-rasmussen** 2024-07-30 12:11 UTC
Labels: c:weave
