### ISSUE TITLE
[CLI]: media/ folder does not sync when there are special characters in the file path

### ISSUE THREAD

**Issue by francelico** [wandb/wandb#4102] opened 2022-08-15 15:04 UTC
### Describe the bug

Images in /media folder are not synchronised if the folder run name includes the characters "[" or "]".

Images are saved locally in the media/ folder. Using wandb sync with various flags has no effect, the client is convinced there are no media files to sync up. However, artifacts with files in the /media folder get synchronised properly (for example a table with images stored in the columns).

I also noticed that in the run summary page, the categories below the Hostname are missing (except the Wandb CLI version category).

Happy to share runs demonstrating this privately if needed.

No exceptions thrown. Sync message looks like this
```shell
wandb: Synced 6 W&B file(s), 0 media file(s), 514 artifact file(s) and 0 other file(s)
```

### Environment

WandB version: 0.13.1

OS: Ubuntu 18.04

Python version: 3.10

Versions of relevant libraries:

**Comment by francelico** [comment] 2022-08-15 15:09
Another possibility is that this occurs when the run folder name is very long. I didn't check this.

**Comment by nate-wandb** [comment] 2022-08-24 16:38
Hi @francelico,
I wasn't able to reproduce this. Could you clarify where the "[" or "]" characters are that will cause this issue? I attempted this by naming the run "test[_run]" and then trying to sync the run folder but this actually caused the entire sync to fail, not just the media.

Thank you,
Nate

**Comment by nate-wandb** [comment] 2022-08-29 18:59
@francelico I wanted to follow up and see if you were able to give me a little more information on how to replicate this issue?

Thank you,
Nate

**Comment by francelico** [comment] 2022-08-30 15:22
Sure, sorry about the delay. They were in one of the parent directories. I am using hydra and some options automatically append overridden parameters to the folder name. An example of a path that was causing the issue:

`~/dev/PhD/maze_representations/outputs/gridworlds/graph_minimal/GraphVAE/big_decoder/epochs=10,models.
configuration.decoder.layer_dim=[256,1024,1024,1024],models.configuration.shared_parameters.latent_dim=64,models.hyperparameters.loss.elbo_coeffs.Fx=[.2,.2]/2022-08-13_03-04-36`

**Comment by nate-wandb** [comment] 2022-09-12 19:18
Hi @francelico, sorry for the delay getting back. I think I was able to recreate this. Do you get a media panel showing up in the UI but then it never loads? 
![Screen Shot 2022-09-12 at 1 13 50 PM](https://user-images.githubusercontent.com/97066933/189737217-46d8a32c-1947-4ef1-b3b0-3e17810426b5.png)

Thank you,
Nate

**Comment by francelico** [comment] 2022-09-12 22:27
Yes I was getting the exact same behaviour.

**Comment by kptkin** [comment] 2024-12-19 00:40
tried to reproduce it with the provided directory name and it seems to work with the client version 0.19.1 and backed of todays date, feel free to re-open if the issue is not fixed on your end.

**Closed by kptkin** 2024-12-19 00:40 UTC
Labels: c:sdk:media, a:sdk
