### ISSUE TITLE
[CLI] wandb.watch interfers with torch.script.jit

### ISSUE THREAD

**Issue by manuel-delverme** [wandb/wandb#3148] opened 2022-01-16 00:20 UTC
`torch.jit.script(...)` requires hooks to have names, unnamed functions make it crash.
https://github.com/pytorch/pytorch/blob/0d7d44615447d336feebeda22f03be40418b9f84/torch/_sources.py#L50-L55
This loop will fail if the hook code contains no "def"

```
local variable 'idx' referenced before assignment
Traceback (most recent call last):
  File "/home/usr/projects/xxxx/main.py", line 169, in train
    train_loop(model, model_q, optimizer, stats_q, train_data_loader, writer)
  File "/home/usr/projects/xxxx/main.py", line 210, in train_loop
    torch.jit.save(torch.jit.script(model), local_path)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 465, in create_script_module_impl
    hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 754, in get_hook_stubs
    hook_stubs.append(make_stub(hook, hook.__name__))
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 51, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/frontend.py", line 233, in get_jit_def
    parsed_def = parse_def(fn)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/_sources.py", line 96, in parse_def
    sourcelines = normalize_source_lines(sourcelines)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/_sources.py", line 55, in normalize_source_lines
    fn_def = sourcelines[idx]
UnboundLocalError: local variable 'idx' referenced before assignment
2022-01-15 19:14:30,188 train        ERROR    Waiting for the test workers to finish.
Traceback (most recent call last):
  File "/home/usr/projects/xxxx/main.py", line 169, in train
    train_loop(model, model_q, optimizer, stats_q, train_data_loader, writer)
  File "/home/usr/projects/xxxx/main.py", line 210, in train_loop
    torch.jit.save(torch.jit.script(model), local_path)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_script.py", line 1257, in script
    return torch.jit._recursive.create_script_module(
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 451, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 465, in create_script_module_impl
    hook_stubs, pre_hook_stubs = get_hook_stubs(nn_module)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 754, in get_hook_stubs
    hook_stubs.append(make_stub(hook, hook.__name__))
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/_recursive.py", line 51, in make_stub
    ast = get_jit_def(func, name, self_name="RecursiveScriptModule")
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/jit/frontend.py", line 233, in get_jit_def
    parsed_def = parse_def(fn)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/_sources.py", line 96, in parse_def
    sourcelines = normalize_source_lines(sourcelines)
  File "/home/usr/projects/venv/lib/python3.8/site-packages/torch/_sources.py", line 55, in normalize_source_lines
    fn_def = sourcelines[idx]
UnboundLocalError: local variable 'idx' referenced before assignment
python-BaseException
```

**Comment by manuel-delverme** [comment] 2022-01-16 00:35
I've tried to address the problem in but a name and a def are not enough:
https://github.com/manuel-delverme/client/tree/watch_torch_jit_models

The new error is:


Hook 'parameter_log_hook_with_closure' on module 'Model' expected the input argument to be typed as a Tuple but found type: 'Tensor' instead.
This error occured while scripting the forward hook 'parameter_log_hook_with_closure' on module Model. If you did not want to script this hook remove it from the original NN module before scripting. This hook was expected to have the following signature: parameter_log_hook_with_closure(self, input: Tuple[Tensor, Tensor], output: Tuple[Tensor, Tensor]). The type of the output arg is the returned type from either the forward method or the previous hook if it exists. Note that hooks can return anything, but if the hook is on a submodule the outer module is expecting the same return type as the submodule's forward.

**Comment by ramit-wandb** [comment] 2022-01-19 17:50
Hi @manuel-delverme,

Thanks for bringing this to our notice! Could you share a self-contained reproduction of this issue (in a colab or a script)? It will help us pin down the source of this error.

Thanks,
Ramit

**Comment by manuel-delverme** [comment] 2022-01-19 19:00
```
import torch
import wandb

wandb.init()
nn = torch.nn.Linear(1, 1)
wandb.watch(nn, log="all")
gg = torch.jit.script(nn)
```

**Comment by ramit-wandb** [comment] 2022-01-24 23:41
Hey @manuel-delverme,

Thanks for the reproduction! I'm going to escalate this up to our engineering team, and we should have a fix out for this soon. I'll let you know as soon as I have any news on the progress of this issue.

Thanks,
Ramit

**Comment by ishitamed19** [comment] 2022-05-14 13:22
@ramit-wandb Hi! Has there been any progress on this issue? I too am facing the same problem, wherein if I try watching the parameters of the model which is initialized using `torch.hit.script`, then the following error is thrown:
```
Traceback (most recent call last):
  File "/private/home/ishitamed/miniconda3/envs/braxnew/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/home/ishitamed/miniconda3/envs/braxnew/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/private/home/ishitamed/projects/multiagent_brax/train.py", line 448, in <module>
    train(env_name=args.env_name, num_envs=args.num_envs, episode_length=args.episode_length,
  File "/private/home/ishitamed/projects/multiagent_brax/train.py", line 124, in train
    wandb.watch([agent, agent_2], log="parameters")
  File "/private/home/ishitamed/miniconda3/envs/braxnew/lib/python3.10/site-packages/wandb/sdk/wandb_watch.py", line 91, in watch
    wandb.run._torch.add_log_hooks_to_pytorch_module(
  File "/private/home/ishitamed/miniconda3/envs/braxnew/lib/python3.10/site-packages/wandb/wandb_torch.py", line 112, in add_log_hooks_to_pytorch_module
    hook = module.register_forward_hook(
  File "/private/home/ishitamed/miniconda3/envs/braxnew/lib/python3.10/site-packages/torch/jit/_script.py", line 922, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: register_forward_hook is not supported on ScriptModules
```

**Comment by kptkin** [comment] 2022-05-15 00:21
Hello @ishitamed19, thanks for your question. Unfortunately, we currently don't support `watch` with scripted modules, since we use `register_forward_hook` under the hood to track the parameters and torch does not support registering hooks on scripted modules as you can see from the error: `RuntimeError: register_forward_hook is not supported on ScriptModules`.

We are thinking of alternative ways of tracking the parameters of the torch models, we will update here as soon as we release a fixed version.

**Comment by ramit-wandb** [comment] 2022-08-18 06:02
Hi @manuel-delverme!

This has been resolved and should be released in the next version of the `wandb` SDK!

Thanks,
Ramit

**Closed** 2022-08-23 18:17 UTC
Labels: cli
