### ISSUE TITLE
[Q] Support for ComplexFloat

### ISSUE THREAD

**Issue by aclifton314** [wandb/wandb#4382] opened 2022-10-18 20:41 UTC
I posted this in the wandb forum, but also wanted to post it here to just in case it's more appropriate. If it's best to leave it in the forum, please let me know and I'll close this question.

Python 3.9.7
Wandb 0.13.4
Pytorch 1.12.0+cu116

I am running a neural network over complex valued data and getting the following error:
```python
Traceback (most recent call last):
  File "/home/aclifton/rf_fp/run_training_w_evaluate.py", line 523, in <module>
    run_training_pipeline(tmp_dict)
  File "/home/aclifton/rf_fp/run_training_w_evaluate.py", line 229, in run_training_pipeline
    outputs = rffp_model(**batch)
  File "/home/aclifton/anaconda3/envs/rffp/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1151, in _call_impl
    hook_result = hook(self, input, result)
  File "/home/aclifton/anaconda3/envs/rffp/lib/python3.9/site-packages/wandb/wandb_torch.py", line 110, in <lambda>
    lambda mod, inp, outp: parameter_log_hook(
  File "/home/aclifton/anaconda3/envs/rffp/lib/python3.9/site-packages/wandb/wandb_torch.py", line 105, in parameter_log_hook
    self.log_tensor_stats(data.cpu(), "parameters/" + prefix + name)
  File "/home/aclifton/anaconda3/envs/rffp/lib/python3.9/site-packages/wandb/wandb_torch.py", line 221, in log_tensor_stats
    tmin = flat.min().item()
RuntimeError: "min_all" not implemented for 'ComplexFloat'
```
I’m not quite sure what to make of it and was wondering if anyone could offer some advice? Thanks in advance for your help!

**Comment by ramit-wandb** [comment] 2022-10-19 12:37
Hi @aclifton314,

Let's keep the thread here so that it can reach a larger audience in case anyone runs into the same issue - Is it possible for you to share a minimal reproduction of the issue you are seeing here? It will help me nail down where this issue is coming from and appropriately file a request / provide a proper implementation for you.

Thanks,
Ramit

**Comment by aclifton314** [comment] 2022-10-19 18:26
@ramit-wandb No problem! Here are the dependencies:
pytorch: 1.12.0+cu116
wandb: 0.13.4
python: 3.9.7
and here is the MRE:
```python
import torch
from torch import nn
import logging
from typing import (Dict)
import wandb
from torch.utils.data import DataLoader, Dataset
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

class MyDataset(Dataset):
    def __init__(self):
        self.re_tensor = torch.rand(1000,800)
        self.im_tensor = torch.rand(1000,800)
        self.labels = torch.randint(0,11,(1000,))
    
    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {'re': self.re_tensor[idx], 'im': self.im_tensor[idx], 'labelz': self.labels[idx]}


class complexReLU(nn.Module):
    def forward(self, input):
        return nn.functional.relu(input.clone().real, inplace=True).type(
            torch.complex64
        ) + 1j * nn.functional.relu(input.clone().imag, inplace=True).type(
            torch.complex64
        )


class complexLinear(nn.Module):
    def __init__(self, in_features, out_features, device):
        super(complexLinear, self).__init__()
        self.fc_real = nn.Linear(in_features, out_features, device=device)
        self.fc_imag = nn.Linear(in_features, out_features, device=device)

    def forward(self, input):
        tmp = (self.fc_real(input.real) - self.fc_imag(input.imag)).type(
            torch.complex64
        ) + 1j * (self.fc_real(input.imag) + self.fc_imag(input.real)).type(
            torch.complex64
        )
        return tmp
    

class ComplexConv1d(nn.Module):
    def __init__(self, device:str, n_labels: int=None):
        super(ComplexConv1d, self).__init__()
        
        self.cconv = nn.Sequential(
            nn.Conv1d(1, 64, kernel_size=9, stride=2, padding=9 // 2, dtype=torch.cfloat, device=device),
            complexReLU(), 
            nn.Conv1d(64, 128, kernel_size=9, stride=2, padding=9 // 2, dtype=torch.cfloat, device=device),
            complexReLU(), 
            nn.Conv1d(128, 256, kernel_size=9, stride=2, padding=9 // 2, dtype=torch.cfloat, device=device),
            complexReLU(), 
            nn.Conv1d(256, 256, kernel_size=9, stride=2, padding=9 // 2, dtype=torch.cfloat, device=device),
            complexReLU()
        )

        self.cclassifier = nn.Sequential(
            complexLinear(12800, 1024, device=device),
            complexReLU(), 
            complexLinear(1024, 512, device=device),
            complexReLU(), 
            complexLinear(512, 256, device=device),
            complexReLU(), 
            complexLinear(256, n_labels, device=device)
        )
        
        self.loss_fn = nn.CrossEntropyLoss()


    def forward(self, re:torch.Tensor=None, im:torch.Tensor=None, labelz:torch.Tensor=None)-> Dict[str, torch.Tensor]:
        if re is not None and im is not None:
            complex_tensor = torch.complex(re, im).unsqueeze_(1)
            cconv_out = self.cconv(complex_tensor)
            logits = self.cclassifier(cconv_out.flatten(1))
            abs_logits = logits.abs()
            loss = self.loss_fn(abs_logits, labelz)
            return {'logits': abs_logits, 'loss': loss, 'complex_logits': logits}
        else:
            raise Exception('re = {}.\n im = {}.\n Must be a tensor of batched data.'.format(re, im))



my_data = MyDataset()
my_n_labels = 11
my_device = 'cuda:0'
my_batch_size = 4
n_epochs = 1


train_dataloader = DataLoader(
            my_data,
            shuffle=True,
            batch_size=my_batch_size)


my_model = ComplexConv1d(my_device, n_labels=my_n_labels)
wandb.init(project='my_project')
wandb.run.name = 'my_run'
wandb.watch(my_model, log='all', log_freq=5)


for epoch in range(n_epochs):
    my_model.train()
    batch_counter = 0
    for batch in train_dataloader:
        print('epoch: {}, batch: {}'.format(epoch, batch_counter))
        batch = {k: v.to(my_device) for k, v in batch.items()}
        batch_counter += 1
        outputs = my_model(**batch)                
```
It appears to happen because of the log frequency in `wandb.watch(my_model, log='all', log_freq=5)`.

**Comment by kptkin** [comment] 2022-10-20 21:34
Hi @aclifton314,

Thanks for the detailed information and the full repro.

You are right it fails due to `wandb.watch`, but the log frequency shouldn't affect this. The issue arise from the fact that your model has complex tensors (`'ComplexFloat'`) and when we try to bin it (the model weights) into a histogram we check the `min` and `max` ranges. However, using `min` on a Complex tensors is not supported and rises the above error. To verify this you could run this simple example:

```
import torch
x = torch.randn(2,2, dtype=torch.cfloat)
x.min()
```

Looking at the torch documentation (https://pytorch.org/docs/stable/complex_numbers.html), the current complex number support is still in beta and we haven't added explicit support for it in `wandb`. We will add this as feature request to extend support for complex number and update this thread once it is available.

**Comment by aclifton314** [comment] 2022-10-21 16:01
@kptkin Thank you so much for your detailed response. Shall I close this issue until the feature is implemented or just leave it open?

**Comment by ramit-wandb** [comment] 2022-10-27 05:21
Hey @aclifton314, Just wanted to provide an update here. I have filed a feature request for this and will be closing this support request for now.  Once this feature has been implemented, we will reach out to confirm this feature works as expected!

**Closed** 2022-10-27 05:22 UTC
