### ISSUE TITLE
[CLI]: TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by YooSungHyun** [wandb/wandb#6546] opened 2023-11-03 07:42 UTC
### Describe the bug

if i used `run = wandb.init(entity="bart_tadev", project='GPT-4 in Python', name="test")` in jupyter notebook
error raised `TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given`

```python
run = wandb.init(entity="bart_tadev", project='GPT-4 in Python', name="test")
```

```shell
wandb: Currently logged in as: bart_tadev. Use `wandb login --relogin` to force relogin
Tracking run with wandb version 0.15.12
Run data is saved locally in /data01/bart/private/kaggle/AI-gen-detector/wandb/run-20231103_163805-aqkwtf24
Syncing run [test](https://wandb.ai/bart_tadev/GPT-4%20in%20Python/runs/aqkwtf24) to [Weights & Biases](https://wandb.ai/bart_tadev/GPT-4%20in%20Python) ([docs](https://wandb.me/run))
View project at https://wandb.ai/bart_tadev/GPT-4%20in%20Python
View run at https://wandb.ai/bart_tadev/GPT-4%20in%20Python/runs/aqkwtf24
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7f252ade0610>> (for post_run_cell), with arguments args (<ExecutionResult object at 7f252add6e10, execution_count=4 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7f252add79d0, raw_cell="run = wandb.init(entity="bart_tadev", project='GPT.." store_history=True silent=False shell_futures=True cell_id=[vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a22284750553037295f3139322e3136382e302e323335227d/data01/bart/private/kaggle/AI-gen-detector/wandb_gpt_api.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D>](vscode-notebook-cell://ssh-remote%2B7b22686f73744e616d65223a22284750553037295f3139322e3136382e302e323335227d/data01/bart/private/kaggle/AI-gen-detector/wandb_gpt_api.ipynb#W3sdnNjb2RlLXJlbW90ZQ%3D%3D%3E) result=None>,),kwargs {}:
```

### Environment

WandB version: wandb==0.15.12

OS: ubuntu 18.04

Python version: 3.11

Versions of relevant libraries:

**Comment by simonlevine** [comment] 2023-11-06 17:21
> Hi @YooSungHyun, thanks for reporting this! It seems that there's something wrong with the environment and how wandb is installed on it. Would you mind testing this on a fresh environment and see if the same error raises?

After installing on a fresh environment this issue persists.

**Comment by texasdave2** [comment] 2023-11-06 21:06
having the same issue today, hadn't had it before:


```
rror in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7f9c928c7880>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7f9c9292ac80, raw_cell="%pip install wandb
import wandb
wandb.login()" store_history=True silent=False shell_futures=True cell_id=b8744c96-7f02-4560-bc52-535fb5cb3af8>,),kwargs {}:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._resume_backend() takes 1 positional argument but 2 were given


Requirement already satisfied: wandb in /home/demouser/miniconda3/envs/ft/lib/python3.10/site-packages (0.15.12)


```

**Comment by jason-brian-anderson** [comment] 2023-11-07 00:39
I'm seeing this as well. Started after i rebuilt my docker container that pulled the most recent version of wandb yesterday (0.15.12)  it has a weird interaction with jupyterlab.  I'm not even importing wandb, and just by running trl.sfttrainer i get the error:

`
from trl import SFTTrainer
trainer = SFTTrainer(
    model=model,
    args=args,
    train_dataset=dataset,
    peft_config=config,
    dataset_text_field="text",
    tokenizer=tokenizer,
    packing=False,
    max_seq_length=512)
`

But not only then, but *all subsequent cell executions thereafter*.

 I literally get the error while running the single command 

`print('hello world')`

talk about imposter syndrome when you can't even run hello world ;-)

**Comment by simonlevine** [comment] 2023-11-07 01:04
Hi all, another clean rebuild my my conda env and reinstall of conda and another clean install of wandb (latest) seems to have fixed the issue.

**Comment by drscotthawley** [comment] 2023-11-07 02:15
Hi folks. I'm getting this all over the place (e.g. for `wandb.init()` ) on my fresh environment with recent update to Ubuntu 22.04 LTS, using Python 3.10.  I get the error with wandb versions 0.15.12 and 0.15.10 (so far) 

On Discord, wandbot suggested setting `settings=wandb.Settings(start_method="fork")` when I call `wandb.init()`, but adding that had no effect.

**Comment by YooSungHyun** [comment] 2023-11-07 02:30
@luisbergua 
Is that enough experimentation for you? I have a serious cold and wasn't able to concentrate, is there anything else I should be doing now? I'm still feeling very sick. 🤒

**Comment by luisbergua** [comment] 2023-11-07 10:44
Hey all, thanks a lot for reporting this! I'm currently investigating this so will post an update as soon as I have something

**Comment by luisbergua** [comment] 2023-11-07 12:57
Hello everyone. I tried to reproduce this on a fresh environment using a jupyter notebook and `wandb==0.15.12` but was unable. Created some runs (with and without explicitly finishing those) and also executed non-wandb ops but everything looks fine. Would really appreciate if anyone could share detailed steps to reproduce this issue. Thanks!

**Comment by jason-brian-anderson** [comment] 2023-11-07 14:19
fwiw, i'm running numpy '1.26.1'   

the most interesting thing to me is that every invocation of any subsequent cell execution in jupyterlab thereafter. what is wandb doing such that every subsequent, non-related cell execution is somehow _wrapped_ by this resume/pause method?  i don't think i've ever seen anything like this before

here is how i reproduced it:

```
import numpy as np
import wandb
import transformers
print(np.__version__)
print(wandb.__version__)
print(transformers.__version__)
import wandb
run = wandb.init()
assert run is wandb.run

```
gives:

```
1.26.1
0.15.12
4.34.1
wandb: Currently logged in as: jason-anderson-professional. Use `wandb login --relogin` to force relogin
Tracking run with wandb version 0.15.12
Run data is saved locally in /app/jupyter/lora_gptq/wandb/run-20231107_140745-86c160ks
Syncing run [morning-eon-3](https://wandb.ai/jason-anderson-professional/lora_gptq-jupyter_lora_gptq/runs/86c160ks) to [Weights & Biases](https://wandb.ai/jason-anderson-professional/lora_gptq-jupyter_lora_gptq) ([docs](https://wandb.me/run))
View project at https://wandb.ai/jason-anderson-professional/lora_gptq-jupyter_lora_gptq
View run at https://wandb.ai/jason-anderson-professional/lora_gptq-jupyter_lora_gptq/runs/86c160ks
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7ff247a80100>> (for post_run_cell), with arguments args (<ExecutionResult object at 7ff247a82ad0, execution_count=1 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7ff247a80190, raw_cell="import numpy as np
import wandb
import transformer.." store_history=True silent=False shell_futures=True cell_id=04e878bb-37eb-4914-949e-1992fae4c8ff> result=None>,),kwargs {}:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given


```

and running the next cell with:
`
print('hello world')`

gives:


```
Error in callback <bound method _WandbInit._resume_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7ff247a80100>> (for pre_run_cell), with arguments args (<ExecutionInfo object at 7ff1df76aa10, raw_cell="print('hello world')" store_history=True silent=False shell_futures=True cell_id=4b869ce9-75c6-4b2f-879b-d35b15cf1d74>,),kwargs {}:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._resume_backend() takes 1 positional argument but 2 were given
hello world
Error in callback <bound method _WandbInit._pause_backend of <wandb.sdk.wandb_init._WandbInit object at 0x7ff247a80100>> (for post_run_cell), with arguments args (<ExecutionResult object at 7ff1df76a680, execution_count=2 error_before_exec=None error_in_exec=None info=<ExecutionInfo object at 7ff1df76aa10, raw_cell="print('hello world')" store_history=True silent=False shell_futures=True cell_id=4b869ce9-75c6-4b2f-879b-d35b15cf1d74> result=None>,),kwargs {}:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given


```

why is wandb even running at all in this cell?  it's like it's @decorating every cell ?! 

[python isn't wrong to assert that the method only takes 1 arg](https://github.com/wandb/wandb/blob/b86aaff3851f9ab9e137f10969878a7e21827f65/wandb/sdk/wandb_init.py#L438):


```
    def _resume_backend(self) -> None:
        if self.backend is not None and self.backend.interface is not None:
            logger.info("resuming backend")  # type: ignore
            self.backend.interface.publish_resume()
```

i'm not even sure how to start trouble shooting  given the weird control over jupyter's cell execution.

**Comment by drscotthawley** [comment] 2023-11-07 14:55
I confirm @jason-brian-anderson's steps, with yet another fresh env.  
@luisbergua, here are the steps I took:

python3 is Python 3.10.12
```
python3 -m venv ~/envs/test_env
source ~/envs/test_env/bin/activate
pip install numpy wandb transformers jupyter
jupyter-notebook --no-browser --port=8889   # this is because I connect remotely
```
Then the lines of code that @jason-brian-anderson posted above produce the error immediately. 

<img width="1162" alt="Screenshot 2023-11-07 at 8 52 20 AM" src="https://github.com/wandb/wandb/assets/13925685/04641cb2-ec43-48eb-82a5-cca9d1ee41f5">

PS - Also note that, once after the `activate` call, the `pip` and `jupyter-notebook` calls are using the binaries within the `test_env` (as per usual).

**Comment by drscotthawley** [comment] 2023-11-07 14:59
Here's a clue: this seems to be some kind of interaction with `jupyter-notebook`.  If i run those same lines of code in CLI Python for that environment, i see no errors!

**Comment by thanos-wandb** [comment] 2023-11-07 14:59
@drscotthawley @jason-brian-anderson @YooSungHyun sorry to hear you're running into this issue, could you please try to downgrade your `ipython` package to `8.16.1` version, and then restart your Jupyter kernel? You can downgrade as follows from the terminal: `pip install ipython==8.16.1`

**Comment by drscotthawley** [comment] 2023-11-07 15:02
@thanos-wandb  That worked!   Hooray!    Thank you.

**Comment by thanos-wandb** [comment] 2023-11-07 15:03
Great, we're glad this unblocks you for now, @drscotthawley, we will raise to our SDK team and follow-up with you here. It seems something broke with latest ipython: https://pypi.org/project/ipython/8.17.2/#history

**Comment by drscotthawley** [comment] 2023-11-07 15:27
Thanks. @thanos-wandb.  Still, I want to echo @jason-brian-anderson's question: 
For what reason is wandb taking control of every jupyter cell execution?

**Comment by thanos-wandb** [comment] 2023-11-07 15:50
@drscotthawley I will get back to you on this with a more concrete answer. From a quick look, it seems there are some jupyter hooks defined using ipython [in wandb SDK here](https://github.com/wandb/wandb/blob/b86aaff3851f9ab9e137f10969878a7e21827f65/wandb/sdk/wandb_init.py#L463).

**Comment by jason-brian-anderson** [comment] 2023-11-07 17:21
> @drscotthawley @jason-brian-anderson @YooSungHyun sorry to hear you're running into this issue, could you please try to downgrade your `ipython` package to `8.16.1` version, and then restart your Jupyter kernel? You can downgrade as follows from the terminal: `pip install ipython==8.16.1`

Confirmed.  This worked.  I pinned it to 8.16.1 in my dockerfile, rebuild, and the problem went away.  Thanks for the quick workaround!

**Comment by vanpelt** [comment] 2023-11-07 21:18
Hey folks, we're aware of the issue.  The root cause is coming from the most recent version of IPython.  We're working on a fix.  In the meantime time if you downgrade IPython to 8.15.0 the issue should go away.

**Comment by vanpelt** [comment] 2023-11-07 21:22
> Thanks. @thanos-wandb.  Still, I want to echo @jason-brian-anderson's question: 
> 
> For what reason is wandb taking control of every jupyter cell execution? 

We have pre and post cell execution hooks to capture the source code for reproducibility.

**Comment by jason-brian-anderson** [comment] 2023-11-08 00:31
> @drscotthawley
> 
> > Thanks. @thanos-wandb.  Still, I want to echo @jason-brian-anderson's question:
> > For what reason is wandb taking control of every jupyter cell execution?
> 
> We have pre and post cell execution hooks to capture the source code for reproducibility.

thanks again for the quick fix.  

you're capturing the contents of every cell? is this data being shipped somewhere or does it stay local?

**Comment by YooSungHyun** [comment] 2023-11-08 03:36
> @drscotthawley @jason-brian-anderson @YooSungHyun sorry to hear you're running into this issue, could you please try to downgrade your `ipython` package to `8.16.1` version, and then restart your Jupyter kernel? You can downgrade as follows from the terminal: `pip install ipython==8.16.1`

YEAA~~~ It work!!!!
wow it is been a long journey...! so glad all of you!!

so... could i close this issue...?

**Comment by thanos-wandb** [comment] 2023-11-08 10:33
A quick update on the issue @here: our SDK team has successfully implemented a fix, which has been shipped in the latest release of `wandb` (`v0.16.0`). You can now upgrade `IPython` if you are using `wandb` version `0.16.0`. For more details, you can check out the pull request [here](https://github.com/wandb/wandb/pull/6563) and our [release notes](https://github.com/wandb/wandb/releases/tag/v0.16.0). Please let us know if you're still encountering any issues.

**Comment by thanos-wandb** [comment] 2023-11-08 18:39
@jason-brian-anderson @drscotthawley to answer the pending question:

> you're capturing the contents of every cell? is this data being shipped somewhere or does it stay local?

The cell contents are captured if `code saving` is on ([docs](https://docs.wandb.ai/guides/track/jupyter#use-cases-for-wb-with-jupyter-notebooks)). In this case, it's “shipped” to the associated run. You can see the notebook in `Code` tab of your run's workspace. I hope this helps! 

Since the issue is resolved, I will go ahead and close this ticket for now. Feel free to reopen this if you had any more follow-up questions or if it isn't resolved for you. Thanks once again everyone for reporting it!

**Closed by thanos-wandb** 2023-11-08 18:39 UTC
Labels: cli

**Comment by harshidkoladara-intive** [comment] 2024-04-23 09:44
> @drscotthawley @jason-brian-anderson @YooSungHyun sorry to hear you're running into this issue, could you please try to downgrade your `ipython` package to `8.16.1` version, and then restart your Jupyter kernel? You can downgrade as follows from the terminal: `pip install ipython==8.16.1`


Thanks @drscotthawley , this resolved the issue

**Comment by youssefpearls** [comment] 2024-07-27 11:43
Just add 
`import wandb
wandb.finish()`

e.g. :
`
from trl import SFTTrainer
import transformers

# Initialize the trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=data_dict["train"],
    dataset_text_field="contetn",
    peft_config=lora_config,
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=4,
        max_steps=100,
        learning_rate=2e-4,
        logging_steps=1,
        output_dir="outputs",
        optim="paged_adamw_8bit",
        save_strategy="epoch",
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

# Train the model
model.config.use_cache = False
trainer.train()

## Finish process to save training and remove the error
import wandb
wandb.finish()
`

the output used to be :
`{
	"name": "TypeError",
	"message": "_WandbInit._pause_backend() takes 1 positional argument but 2 were given",
	"stack": "---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: _WandbInit._pause_backend() takes 1 positional argument but 2 were given"
}`
after the addition :
![Screenshot 2024-07-27 124244](https://github.com/user-attachments/assets/cbaa2159-a04f-40c9-8241-4f16269a6bd4)
