### ISSUE TITLE
[CLI] [Bug] KeyError when adding a new dictionary as statistic to existing run

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/wandb#1934] opened 2021-03-08 03:02 UTC
**Description**
I'm adding a new summary to the existing run following the docs https://docs.wandb.ai/library/public-api-guide.
If a new summary is a scalar value, everything works fine, but if it's a dictionary, I get the following:

```
$ python tmp_wandb.py 
Traceback (most recent call last):
  File "tmp_wandb.py", line 5, in <module>
    run.summary.update({'new_metric_d': {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}})
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\old\summary.py", line 179, in update
    write_items = self._update(key_vals, overwrite)
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\old\summary.py", line 198, in _update
    self._dict[key] = SummarySubDict(
  File "C:\Users\Maria\.conda\envs\Garments\lib\site-packages\wandb\old\summary.py", line 48, in __init__
    json_dict = json_dict[k]
KeyError: 'new_metric_d'
```

**Wandb features**
`run.summary.update()` according to the docs https://docs.wandb.ai/library/public-api-guide.

**How to reproduce**
This is the minimum script: 
```
import wandb

run = wandb.Api().run(<run_path>)
run.summary.update({'new_metric_d': {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}})
run.summary.update()

```
The run at <run_path> already exists and has a "failed" state (in case it's important)
Here is the run I work with: https://wandb.ai/maria_korosteleva/Garments-Reconstruction/runs/5cnaly5h/

**Environment**
- OS: Win 10
- Environment: Anaconda + Visual Code
- Python Version: 3.8.5
- wandb Version: 0.10.21

**Comment by vanpelt** [comment] 2021-03-08 03:33
Hey @maria-korosteleva we'll look into the root cause.  Until then you should be able to do the following:

```
run.summary["new_metric_d"] = {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}
run.summary.update()
```

**Comment by maria-korosteleva** [comment] 2021-04-06 07:53
Hey @vanpelt 

Just letting you know that the issue is still there in 0.10.25. And both of the methods don't work (the one in the issue description and the one that you proposed).

>
> ```
> run = wandb.Api().run(<run_path>)
> run.summary.update({'new_metric_d': {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}})
> run.summary.update() 
> ```
>

> ```
> run = wandb.Api().run(<run_path>)
> run.summary["new_metric_d"] = {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}
> run.summary.update()
> ```

Both fail with the same `KeyError: 'new_metric_d'`  😥

**Comment by corneliusboehm** [comment] 2021-07-15 11:54
I just reproduced this issue on `0.10.27`. From what I can tell, a fix might be swapping lines 144 and 145 here, so that the key is added to `root._json_dict` before `SummarySubDict` tries to access it in `__init__`: https://github.com/wandb/client/blob/321654aea55440622371594da9279f4e97f25607/wandb/old/summary.py#L137-L149
Something similar would also need to be done for the `update` method.

In the meantime, this workaround did the trick for me:
```python
def update_run(run, k, v):
    if (isinstance(run.summary, wandb.old.summary.Summary) and k not in run.summary):
        run.summary._root_set(run.summary._path, [(k, {})])
    run.summary[k] = v
```

**Comment by huy29433** [comment] 2021-11-29 09:50
Same issue in `0.12.7`. @corneliusboehm's works for me, thank you!

**Comment by sajastu** [comment] 2023-01-30 08:48
Yeah, same for me. @corneliusboehm 's workaround did the trick. Thanks a lot!

**Comment by universome** [comment] 2023-08-30 13:13
The issue still persists.

**Comment by noamsgl** [comment] 2023-09-21 08:06
Issue still persists

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
maria-korosteleva commented: 
Hey @vanpelt 

Just letting you know that the issue is still there in 0.10.25. And both of the methods don't work (the one in the issue description and the one that you proposed).

>
> ```
> run = wandb.Api().run(<run_path>)
> run.summary.update({'new_metric_d': {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}})
> run.summary.update() 
> ```
>

> ```
> run = wandb.Api().run(<run_path>)
> run.summary["new_metric_d"] = {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'}
> run.summary.update()
> ```

Both fail with the same `KeyError: 'new_metric_d'`  😥

----

For now, the workaround that worked for me is recording each dictionary entry one by one as individual scalar values with extended names, e.g.
```
import wandb

def add_statistic(run, tag, info):
    """Add info the run summary (e.g. stats on test set)"""
    if isinstance(info, dict):
        for key in info:
            add_statistic(run, tag + '.' + key, info[key])
    else:
        run.summary[tag] = info
        run.summary.update()

run = wandb.Api().run('maria_korosteleva/Test-Garments-Reconstruction/2ckc3ecs')
add_statistic(run, 'new_metric_d2',  {'full_loss': 2.5, 'Extra_loss': 1.5, 'type': 'dict_metric'})
```

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
github-actions[bot] commented: 
This issue is stale because it has been open 60 days with no activity.

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
corneliusboehm commented: 
I just reproduced this issue on `0.10.27`. From what I can tell, a fix might be swapping lines 144 and 145 here, so that the key is added to `root._json_dict` before `SummarySubDict` tries to access it in `__init__`: https://github.com/wandb/client/blob/321654aea55440622371594da9279f4e97f25607/wandb/old/summary.py#L137-L149
Something similar would also need to be done for the `update` method.

In the meantime, this workaround did the trick for me:
```python
def update_run(run, k, v):
    if (isinstance(run.summary, wandb.old.summary.Summary) and k not in run.summary):
        run.summary._root_set(run.summary._path, [(k, {})])
    run.summary[k] = v
```

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
github-actions[bot] commented: 
This issue is stale because it has been open 60 days with no activity.

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
huy29433 commented: 
Same issue in `0.12.7`. @corneliusboehm's workaround works for me, thank you!

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
universome commented: 
The issue still persists.

**Comment by sydholl** [comment] 2023-09-21 08:07
WandB Internal User commented: 
noamsgl commented: 
Issue still persists

**Comment by universome** [comment] 2023-09-23 05:25
Do not close this issue please because it still persists and causes inconvenience.

**Comment by sydholl** [comment] 2023-10-11 16:59
WandB Internal User commented: 
universome commented: 
Do not close this issue please because it still persists and causes inconvenience.

**Comment by MBakirWB** [comment] 2023-11-14 00:06
Hi All, please note this issue with be fixed with the next SDK release. See PR above for detail.

**Closed by MBakirWB** 2023-11-14 00:06 UTC
Labels: bug, cli, c:summary
