### ISSUE TITLE
[CLI]: repeated runs started instead of the correct ones in sweep

### ISSUE THREAD

**Issue by QianqianF** [wandb/wandb#7173] opened 2024-03-18 21:37 UTC
### Describe the bug

While starting a sweep through `.yml` file, the agent did not correctly started the sweep with the right combinations of parameters. Instead some hyperparameter combo is repeated while others never run.

The yml I'm using
```
method: grid
name: scan_a2c_BP_cosine_decay_0.1
parameters:

  tau_u: 
    values:
      - 0.1
  tau_delta: 
    values:
      - 0.1
  prospective: 
    values: 
      - 0.0
      - 0.1
      - 0.25
      - 0.5
      - 1.0
  actor_lr:
    values:
      - 1e-4
      - 1e-5
      - 1e-6
      - 1e-7
  critic_lr:
    values: 
      - 1e-4
      - 1e-5
      - 1e-6
      - 1e-7
  tau_int: 
    value: 1.0
  dt: 
    value: 1e-3
  T: 
    value: 4 
  entropy_beta:
    value: 0.0
  delay: 
    value: False
  num_episodes: 
    value: 6000
  num_agents: 
    values:
      - 1
  gamma: 
    values: 
      - 0.99
  seed:
    values:
      - 8
      - 9
  criteria_k:
    values:
      - 35
  decay_steps:
    values:
      - 3e6
  use_wandb:
    value: True
  save_obs:
    value: False
  debug:
    value: False
  actor_BP:
    values: 
      - False
  critic_BP:
    values: 
      - False
  logging_freq:
    value: 1
  gpu:
    value: 3

program: EqProp_a2c_cartpole.py
```
The runs in the sweep I'm getting (filtered for prospective == 1)
![image](https://github.com/wandb/wandb/assets/32441593/75fa5c42-5e20-4175-a4b4-6f622b21255e)

Note that if I only scan for `actor_lr` or `critic_lr` things work fine.

The sweep referred to is: https://wandb.ai/ethz_joao/TemporalDEQ/sweeps/0j1fnqf2?nw=nwuserqqqqf

### Environment

WandB version: 0.15.10

OS: Ubuntu 22.04

Python version: 3.10.11

Versions of relevant libraries:

**Comment by luisbergua** [comment] 2024-03-19 11:20
Hi @QianqianF, thanks for raising this! Would you mind installing the latest SDK version with `pip install wandb -U` and see if the issue is still happening? A similar one was fixed in the past so wanted to check if it's the same

**Comment by QianqianF** [comment] 2024-03-20 10:01
Moreover in [a different sweep](https://wandb.ai/ethz_joao/TemporalDEQ/sweeps/bvrt54wo?nw=nwuserqqqqf) the agent keeps starting new runs after all the hyperparameter configurations are covered already, resulting in much more runs than it should.

**Comment by HannesStagge** [comment] 2024-03-20 14:55
I encounter the same issue. It seems to be an old problem already? I found [this ](https://github.com/wandb/wandb/issues/3522) old thread as well.

**Comment by HannesStagge** [comment] 2024-03-20 14:59
I would even say it has not been like that a few months ago. I have some very similar runs now and from a few months back where everything worked just fine. If I figure out a way to find out the version of wandb i was using back then I will let you know.

**Comment by luisbergua** [comment] 2024-03-22 10:45
Hey @HannesStagge @QianqianF , thanks for sharing this information! Would it be possible to share a minimal repro example? I tested on my end using `0.16.4` and both CLI and SDK sweep but don't see combinations being repeated
## train.py
```
import wandb
import yaml
import random
import numpy as np

def main():
    # Set up your default hyperparameters
    with open("./config.yaml") as file:
        config = yaml.load(file, Loader=yaml.FullLoader)

    run = wandb.init(config=config)
    # lr = wandb.config.lr
    bs = wandb.config.batch_size
    epochs = wandb.config.epochs

    for epoch in np.arange(1, epochs):
        wandb.log({"epoch": epoch, "acc": random.random()})

main()
```

## config.yaml
```
program: train.py
project: test_grid_config
method: grid
name: sweep
metric:
  goal: maximize
  name: val_acc
parameters:
  batch_size: 
    values: [16,32,64]
  epochs:
    values: [5, 10, 15]
```
![image](https://github.com/wandb/wandb/assets/113048227/f45f89a8-45a9-471a-9e54-b3ff7ca7fa51)


## SDK sweep
```
import wandb
import numpy as np
import random

sweep_configuration = {
    "method": "grid",
    "name": "sweep",
    "metric": {"goal": "maximize", "name": "val_acc"},
    "parameters": {
        "batch_size": {"values": [16, 32, 64]},
        "epochs": {"values": [5, 10, 15]},
    },
}

sweep_id = wandb.sweep(sweep=sweep_configuration, project="test_grid_config")

def main():
    run = wandb.init()
    bs = wandb.config.batch_size
    epochs = wandb.config.epochs
    for epoch in np.arange(1, epochs):
        wandb.log({"epoch": epoch, "acc": random.random()})

wandb.agent(sweep_id, function=main)
```
![image](https://github.com/wandb/wandb/assets/113048227/77632a5a-7bc8-426c-bdab-2a594d4e30c3)

**Comment by HannesStagge** [comment] 2024-03-22 11:48
@luisbergua Thanks for your effort. I too tested it on different version (including the "old" 0.15.8, 0.16.0 and 0.16.4) and the error is reproducible so that's off the table. However, on my local PC everything is working fine but the problems occur on cluster with SLURM manager. I am in contact with the local administrator of the cluster and could share with you the configuration (and a mwe as well). However, I would suggest to start a new issue for that?

**Comment by QianqianF** [comment] 2024-03-22 17:11
Hi @luisbergua Thanks for taking a look at the issue. I just quickly made this example. It's not completely minimal (sorry) because I tried reducing the yaml file partially but then it works fine. When I have a bit more time later I can also try to pin point where exactly the problem is. Hopefully that can get you started somewhere. 

#### config.yaml
```
method: grid
project: test_grid_config
name: sweep
parameters:

  tau_u: 
    values:
      - 0.1
  tau_delta: 
    values:
      - 0.1
  prospective: 
    values: 
      - 0.0
      - 0.1
      - 0.25
      - 0.5
      - 1.0
  actor_lr:
    values:
      - 1e-4
      - 1e-5
      - 1e-6
      - 1e-7
  critic_lr:
    values: 
      - 1e-4
      - 1e-5
      - 1e-6
      - 1e-7
  tau_int: 
    value: 1.0
  dt: 
    value: 1e-3
  T: 
    value: 4 
  entropy_beta:
    value: 0.0
  delay: 
    value: False
  num_episodes: 
    value: 6000
  num_agents: 
    values:
      - 1
  gamma: 
    values: 
      - 0.99
  seed:
    values:
      - 50
      - 60
  criteria_k:
    values:
      - 35
  decay_steps:
    values:
      - 3e6
  save_obs:
    value: False
  debug:
    value: False
  actor_BP:
    values: 
      - False
  critic_BP:
    values: 
      - False
  logging_freq:
    value: 1
  gpu:
    value: 3

program: train.py
```

#### train.py (same as yours)
```
import wandb
import yaml
import random
import numpy as np

def main():
    # Set up your default hyperparameters
    with open("./config.yaml") as file:
        config = yaml.load(file, Loader=yaml.FullLoader)

    run = wandb.init(config=config)
    T = wandb.config.T

    for epoch in np.arange(1, T):
        wandb.log({"epoch": epoch, "acc": random.random()})

main()
```

#### CLI
```
wandb sweep config.yaml
wandb agent <sweep_id>
```

Thanks again.

**Comment by luisbergua** [comment] 2024-03-27 16:10
Hey @QianqianF, thanks a lot for sharing the code! Mind sharing a link to the sweep as well? I'll test on my end but would like to take a look

**Comment by QianqianF** [comment] 2024-03-27 16:21
Sure, thanks for taking a look. [Here](https://wandb.ai/ethz_joao/test_grid_config/sweeps/jf81vi4y) is the link.

**Comment by luisbergua** [comment] 2024-04-10 11:24
Hey @QianqianF, thanks for sharing the link and apologies aboput the delay! After doing some tests, I was able to reproduce the issue so will raise it with our engineers and will keep you posted with any relevant updates

**Comment by QianqianF** [comment] 2024-04-10 15:21
No worries. Thanks so much for raising it.

**Comment by luisbergua** [comment] 2024-06-04 09:09
Hey @QianqianF, thanks for your patience! I just wanted to let you know that this issue has been fixed

**Comment by QianqianF** [comment] 2024-06-04 11:54
Amazing. Thanks! What turned out to be the problem?

**Comment by luisbergua** [comment] 2024-06-04 12:56
[This](https://github.com/wandb/sweeps/pull/109) is the PR with the fix in case you want to take a look

**Closed** 2024-11-14 19:20 UTC
Labels: c:sweeps
