### ISSUE TITLE
[CLI]:   RuntimeError: "histogram_cpu" not implemented for 'Char'

### ISSUE THREAD

**Issue by Qubitium** [wandb/wandb#5271] opened 2023-03-31 13:58 UTC
### Describe the bug

46 minutes into training and I got this .  Killed everything. Ah!!!!!

```python

```

```shell
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1550, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1403, in _run_ddp_forward
    return self.module(*args, **kwargs)  # type: ignore[index]
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/wandb_torch.py", line 110, in <lambda>
    lambda mod, inp, outp: parameter_log_hook(
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/wandb_torch.py", line 105, in parameter_log_hook
    self.log_tensor_stats(data.cpu(), "parameters/" + prefix + name)
  File "/root/miniconda3/lib/python3.9/site-packages/wandb/wandb_torch.py", line 231, in log_tensor_stats
    tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)
RuntimeError: "histogram_cpu" not implemented for 'Char'

```

### Environment

WandB version: 0.14.0

OS: ubuntu 22.04

Python version: miniconda 3.9

Versions of relevant libraries: pytorch 2.0 cuda 11.8

**Comment by thanos-wandb** [comment] 2023-04-06 10:16
Hi @diegomontoya sorry to hear about this, and thanks for reporting the issue with any libraries versions information. 

The error seems to be coming from [this line](https://github.com/wandb/wandb/blob/df6f7909d8ec9511452d51a027b33ebda31b5d9d/wandb/wandb_torch.py#L231) of `wandb_torch` script, while the `histogram_cpu` function is defined on [PyTorch repo](https://github.com/pytorch/pytorch/blob/b8cf01013975dfabe40966b8dc4555a2e069336c/aten/src/ATen/native/Histogram.cpp#L393). I can see there's already a PR contribution to get this issue fixed. 

Is there a minimal code example you could share that can reproduce the issue?

**Comment by thanos-wandb** [comment] 2023-04-11 13:13
Hi @diegomontoya just checking in here to see if you were able to provide us with a minimal code example to help reproduce the issue? I will move the ticket to on-hold for now, and will let you know once the PR is merged to our SDK code.

**Comment by diegomontoya** [comment] 2023-04-11 13:33
I have since bypassed this issue by only logging gradient and instead of all.

The model in training was Llama but noy sure if the error happend on training under tf16 or 8bit. One of the two. It was done on rented A100 80g so I have not tried to recreate the error.

**Comment by diegomontoya** [comment] 2023-04-19 14:04
@thanos-wandb  More detailed stacktrace on pytorch 2.1 nightly, transformer [head], peft [head]

```
home/fsuser/alpaca-lora/finetune.py:346 in <module>                                             │
│                                                                                                  │
│   343                                                                                            │
│   344                                                                                            │
│   345 if __name__ == "__main__":                                                                 │
│ ❱ 346 │   fire.Fire(train)                                                                       │
│   347                                                                                            │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/fire/core.py:141 in Fire                    │
│                                                                                                  │
│   138 │   context.update(caller_globals)                                                         │
│   139 │   context.update(caller_locals)                                                          │
│   140                                                                                            │
│ ❱ 141   component_trace = _Fire(component, args, parsed_flag_args, context, name)                │
│   142                                                                                            │
│   143   if component_trace.HasError():                                                           │
│   144 │   _DisplayError(component_trace)                                                         │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/fire/core.py:475 in _Fire                   │
│                                                                                                  │
│   472 │     is_class = inspect.isclass(component)                                                │
│   473 │                                                                                          │
│   474 │     try:                                                                                 │
│ ❱ 475 │   │   component, remaining_args = _CallAndUpdateTrace(                                   │
│   476 │   │   │   component,                                                                     │
│   477 │   │   │   remaining_args,                                                                │
│   478 │   │   │   component_trace,                                                               │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/fire/core.py:691 in _CallAndUpdateTrace     │
│                                                                                                  │
│   688 │   loop = asyncio.get_event_loop()                                                        │
│   689 │   component = loop.run_until_complete(fn(*varargs, **kwargs))                            │
│   690   else:                                                                                    │
│ ❱ 691 │   component = fn(*varargs, **kwargs)                                                     │
│   692                                                                                            │
│   693   if treatment == 'class':                                                                 │
│   694 │   action = trace.INSTANTIATED_CLASS                                                      │
│                                                                                                  │
│ /home/fsuser/alpaca-lora/finetune.py:336 in train                                                │
│                                                                                                  │
│   333 │   if torch.__version__ >= "2" and sys.platform != "win32":                               │
│   334 │   │   model = torch.compile(model)                                                       │
│   335 │                                                                                          │
│ ❱ 336 │   trainer.train(resume_from_checkpoint=resume_from_checkpoint)                           │
│   337 │                                                                                          │
│   338 │   model.save_pretrained(output_dir)                                                      │
│   339                                                                                            │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:1662 in train       │
│                                                                                                  │
│   1659 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1660 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1661 │   │   )                                                                                 │
│ ❱ 1662 │   │   return inner_training_loop(                                                       │
│   1663 │   │   │   args=args,                                                                    │
│   1664 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1665 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:1929 in             │
│ _inner_training_loop                                                                             │
│                                                                                                  │
│   1926 │   │   │   │   │   with model.no_sync():                                                 │
│   1927 │   │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                  │
│   1928 │   │   │   │   else:                                                                     │
│ ❱ 1929 │   │   │   │   │   tr_loss_step = self.training_step(model, inputs)                      │
│   1930 │   │   │   │                                                                             │
│   1931 │   │   │   │   if (                                                                      │
│   1932 │   │   │   │   │   args.logging_nan_inf_filter                                           │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:2699 in             │
│ training_step                                                                                    │
│                                                                                                  │
│   2696 │   │   │   return loss_mb.reduce_mean().detach().to(self.args.device)                    │
│   2697 │   │                                                                                     │
│   2698 │   │   with self.compute_loss_context_manager():                                         │
│ ❱ 2699 │   │   │   loss = self.compute_loss(model, inputs)                                       │
│   2700 │   │                                                                                     │
│   2701 │   │   if self.args.n_gpu > 1:                                                           │
│   2702 │   │   │   loss = loss.mean()  # mean() to average on multi-gpu parallel training        │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/transformers/trainer.py:2731 in             │
│ compute_loss                                                                                     │
│                                                                                                  │
│   2728 │   │   │   labels = inputs.pop("labels")                                                 │
│   2729 │   │   else:                                                                             │
│   2730 │   │   │   labels = None                                                                 │
│ ❱ 2731 │   │   outputs = model(**inputs)                                                         │
│   2732 │   │   # Save past state if it exists                                                    │
│   2733 │   │   # TODO: this needs to be fixed and made cleaner later.                            │
│   2734 │   │   if self.args.past_index >= 0:                                                     │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py:1535 in    │
│ forward                                                                                          │
│                                                                                                  │
│   1532 │   │   │   output = (                                                                    │
│   1533 │   │   │   │   self.module.forward(*inputs, **kwargs)                                    │
│   1534 │   │   │   │   if self._delay_all_reduce_all_params                                      │
│ ❱ 1535 │   │   │   │   else self._run_ddp_forward(*inputs, **kwargs)                             │
│   1536 │   │   │   )                                                                             │
│   1537 │   │   │   return self._post_forward(output)                                             │
│   1538                                                                                           │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/nn/parallel/distributed.py:1388 in    │
│ _run_ddp_forward                                                                                 │
│                                                                                                  │
│   1385 │   │   │   │   │   **kwargs,                                                             │
│   1386 │   │   │   │   )                                                                         │
│   1387 │   │   │   with self._inside_ddp_forward():                                              │
│ ❱ 1388 │   │   │   │   return self.module(*args, **kwargs)  # type: ignore[index]                │
│   1389 │   │   else:                                                                             │
│   1390 │   │   │   # Cast inputs to reduced precision if needed.                                 │
│   1391 │   │   │   # TODO (rohan-varma) test this codepath.                                      │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py:1547 in          │
│ _call_impl                                                                                       │
│                                                                                                  │
│   1544 │   │   │   │   if hook_id in self._forward_hooks_with_kwargs:                            │
│   1545 │   │   │   │   │   hook_result = hook(self, args, kwargs, result)                        │
│   1546 │   │   │   │   else:                                                                     │
│ ❱ 1547 │   │   │   │   │   hook_result = hook(self, args, result)                                │
│   1548 │   │   │   │                                                                             │
│   1549 │   │   │   │   if hook_result is not None:                                               │
│   1550 │   │   │   │   │   result = hook_result                                                  │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/wandb/wandb_torch.py:110 in <lambda>        │
│                                                                                                  │
│   107 │   │   log_track_params = log_track_init(log_freq)                                        │
│   108 │   │   try:                                                                               │
│   109 │   │   │   hook = module.register_forward_hook(                                           │
│ ❱ 110 │   │   │   │   lambda mod, inp, outp: parameter_log_hook(                                 │
│   111 │   │   │   │   │   mod, inp, outp, log_track_params                                       │
│   112 │   │   │   │   )                                                                          │
│   113 │   │   │   )                                                                              │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/wandb/wandb_torch.py:105 in                 │
│ parameter_log_hook                                                                               │
│                                                                                                  │
│   102 │   │   │   │   │   data = parameter.data                                                  │
│   103 │   │   │   │   else:                                                                      │
│   104 │   │   │   │   │   data = parameter                                                       │
│ ❱ 105 │   │   │   │   self.log_tensor_stats(data.cpu(), "parameters/" + prefix + name)           │
│   106 │   │                                                                                      │
│   107 │   │   log_track_params = log_track_init(log_freq)                                        │
│   108 │   │   try:                                                                               │
│                                                                                                  │
│ /home/fsuser/miniconda3/lib/python3.10/site-packages/wandb/wandb_torch.py:231 in                 │
│ log_tensor_stats                                                                                 │
│                                                                                                  │
│   228 │   │   # in min()/max() above. Swap here to prevent a runtime error.                      │
│   229 │   │   if tmin > tmax:                                                                    │
│   230 │   │   │   tmin, tmax = tmax, tmin                                                        │
│ ❱ 231 │   │   tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)                       │
│   232 │   │   tensor = tensor.cpu().clone().detach()                                             │
│   233 │   │   bins = torch.linspace(tmin, tmax, steps=self._num_bins + 1)                        │
│   234                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: "histogram_cpu" not implemented for 'Char'
```

**Comment by thanos-wandb** [comment] 2023-04-19 14:12
Hi @diegomontoya thanks for the additional stack trace error, the PR that should address this issue is under review and is planned to be merged for our release in May. We will keep you posted here!

**Comment by teknium1** [comment] 2023-04-30 07:46
I just ran into this error training alpaca-lora.. no fix available now?

**Comment by thanos-wandb** [comment] 2023-04-30 11:58
Hi @teknium1 [this PR](https://github.com/wandb/wandb/pull/5283) may fix the issue, but it's currently under review. I will keep this thread updated once it's merged to master branch.

**Comment by teknium1** [comment] 2023-04-30 13:46
> Hi @teknium1 [this PR](https://github.com/wandb/wandb/pull/5283) may fix the issue, but it's currently under review. I will keep this thread updated once it's merged to master branch.

Its okay, for whatever reason when I don't set the wandb settings when launching the trainer - it automatically creates a wandb run and that does not crash lol

**Comment by gameveloster** [comment] 2023-07-10 19:28
I'm seeing a similar error message with a different type involved, wonder if it can be fixed by the above PR linked by @thanos-wandb 

> RuntimeError: "histogram_cpu" not implemented for 'Byte'

Also no longer see this error if wandb params are not passed to the `Trainer` but somehow wandb logs are still being sent for the training run, just like what @teknium1 had observed.

**Comment by thanos-wandb** [comment] 2023-07-11 08:27
Hi @gameveloster thanks for reporting this, could you please provide more details for which other type you've seen the same error? The above PR is currently planned to be reviewed for August's SDK release, so I can keep you posted here once it's merged to check.

**Comment by gameveloster** [comment] 2023-07-14 16:40
@thanos-wandb I think this type might be named `Byte`, also reported at https://github.com/huggingface/transformers/issues/16689#issuecomment-1298655647

Encountered this when using `transformers.Trainer` on LLMs.

**Comment by thanos-wandb** [comment] 2023-07-14 17:34
Thanks a lot @gameveloster for the link to HF Transformers repo. Would you have a minimal code example for this error?

**Comment by jitingxu1** [comment] 2023-07-22 20:57
I had this error too, I was trying to run the https://github.com/tloen/alpaca-lora using the recommended steps:
```
python finetune.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --data_path 'yahma/alpaca-cleaned' \
    --output_dir './lora-alpaca'
```
Ran this on google colab with A100 GPU.

**Comment by jitingxu1** [comment] 2023-07-22 21:01
```
Traceback (most recent call last):
  File "/content/alpaca-lora/finetune.py", line 288, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/alpaca-lora/finetune.py", line 278, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1809, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2654, in training_step
    loss = self.compute_loss(model, inputs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 2679, in compute_loss
    outputs = model(**inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/usr/local/lib/python3.10/dist-packages/wandb/wandb_torch.py", line 110, in <lambda>
    lambda mod, inp, outp: parameter_log_hook(
  File "/usr/local/lib/python3.10/dist-packages/wandb/wandb_torch.py", line 105, in parameter_log_hook
    self.log_tensor_stats(data.cpu(), "parameters/" + prefix + name)
  File "/usr/local/lib/python3.10/dist-packages/wandb/wandb_torch.py", line 231, in log_tensor_stats
    tensor = flat.histc(bins=self._num_bins, min=tmin, max=tmax)
RuntimeError: "histogram_cpu" not implemented for 'Char'
```

**Comment by morganmcg1** [comment] 2023-08-11 17:57
This looks to be coming from `wandb.watch`, maybe explicitly turn it off?

set  wandb_watch=false in the alpaca-lora script: https://github.com/tloen/alpaca-lora/blob/main/finetune.py

or `os.environ["WANDB_WATCH"] = "false"` in your script and see if that works?

**Closed** 2023-08-22 05:56 UTC
Labels: cli
