### ISSUE TITLE
[CLI]: non-parallelism breaks cross validation

### ISSUE THREAD

**Issue by BagelOrb** [wandb/wandb#6547] opened 2023-11-03 10:24 UTC
### Describe the bug

[The cross validation example](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py) seems to depend on parallelism. When I replace `import multiprocessing` with `import multiprocessing.dummy as multiprocessing` the first fold will never appear in the project. This seems to indicate that the code depends on the arbitrary order in which code gets executed in parallelism, which might indicate that sometimes even the parallel code might fail.

Perhaps the first call to `run.finish()` finishes the `sweep_run` instead of the group `run`..?

On the very last call to `sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))` it crashes with the following stack trace:

```
wandb: ERROR Run (3tpcua5p) is finished. The call to `log` will be ignored. Please make sure that you are using an active run.
Traceback (most recent call last):
  File "/home/tim.kuipers/dev/deeplearning/projects/iris_drone_classification/pipeline_2023_fastai2/__ff.py", line 98, in <module>
    main()
  File "/home/tim.kuipers/dev/deeplearning/projects/iris_drone_classification/pipeline_2023_fastai2/__ff.py", line 88, in main
    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
  File "/home/tim.kuipers/mambaforge-pypy3/envs/fastai_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 419, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tim.kuipers/mambaforge-pypy3/envs/fastai_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 380, in wrapper_fn
    raise errors.UsageError(resolved_message)
wandb.errors.UsageError: Run (3tpcua5p) is finished. The call to `log` will be ignored. Please make sure that you are using an active run.
```

Is it even possible to work with groups inside a sweep without using parallelism?

### Additional Files

![image](https://github.com/wandb/examples/assets/8895761/719c600a-d8d9-4ce6-acb1-cc3b08b1803c)
Here playful sponge was with the original example, while bright water was with `multiprocessing.dummy`.

### Environment

$ wandb --version
wandb, version 0.15.12
$ python3 --version
Python 3.10.12
$ uname -a
Linux WS-Tim-kuipers 5.15.0-88-generic #98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Additional Context

Here I provide some code which reproduces the problem I describe exactly. 
NOTE: **I did not run the following code to get to this bug report,** but this code does in fact reproduce the exact same two problems: the first fold doesn't appear in the web interface and we end with a stack trace error.
(The code to get to this bug report is the example train-cross-validation.py with `import multiprocessing` replaced by `import multiprocessing.dummy as multiprocessing`.)

```python
import wandb
import os
import random


def reset_wandb_env():
    exclude = ("WANDB_PROJECT", "WANDB_ENTITY", "WANDB_API_KEY")
    for k in list(os.environ.keys()):
        if k.startswith("WANDB_") and k not in exclude:
            del os.environ[k]


def train(worker_num, sweep_id, sweep_run_name, config):
    reset_wandb_env()
    run_name = f"{sweep_run_name}-{worker_num}"
    run = wandb.init(
        group=sweep_id,
        job_type=sweep_run_name,
        name=run_name,
        config=config,
    )
    val_accuracy = random.random()
    run.log({'val_accuracy': val_accuracy})
    run.finish()
    return val_accuracy


def main():
    num_folds = 5
    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    sweep_group_url = f"{sweep_run.get_project_url()}/groups/{sweep_id}"
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown"

    metrics = []
    for num in range(num_folds):
        val_accuracy = train(
            worker_num=num,
            sweep_id=sweep_id,
            sweep_run_name=sweep_run_name,
            config=sweep_run.config,
        )
        metrics.append(val_accuracy)

    average_val_accuracy = sum(metrics) / num_folds
    sweep_run.log({'val_accuracy': average_val_accuracy})
    sweep_run.finish()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("Average Val Accuracy: ", average_val_accuracy)
    print("*" * 40)


if __name__ == "__main__":
    main()

```

**Comment by nate-wandb** [comment] 2023-11-06 16:27
Hi @BagelOrb, just to clarify were you able to reproduce this without using `multiprocessing.dummy` ? I'll test out the code sample you send but if I understand correctly, you are saying that since the parallel processes are executed in an arbitrary order it's possible that `wandb.finish` could be called before `wandb.log` in this example correct?

**Comment by BagelOrb** [comment] 2023-11-08 14:41
Hi @nate-wandb,

Please start by testing the [train-cross-validation.py](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py) from your examples library.

Then change the line `import multiprocessing` in that file for `import multiprocessing.dummy as multiprocessing`.

This change shouldn't introduce a bug, but it does. The parallelism isn't the problem, turning off the parallelism causes the problem somehow. That's really odd.

**Comment by BagelOrb** [comment] 2023-11-15 09:41
Just to clarify: the basic example train-cross-validation.py without any changes doesn't cause any issue. It's just that I want to do cross validation without doing parallelism, but I can't get it working. Not using code that's very close to your example, and also not with code that's much simpler which doesn't use parallelism. Something seems to be horribly broken. Please make it possible to do cross validation without parallelism.

**Comment by anmolmann** [comment] 2023-11-17 21:26
Hey @BagelOrb, the reason this is happening is because `multiprocessing.dummy` is just a wrapper for the threading lib. Therefore, spinning up multiple threads would cause these threads to share memory and resources across all of the initialized runs. That's why `worker_q.get()` doesn't fetch anything as it gets executed before the `worker.queue.put` call. And, from the snippets you can see the order in which the runs are initialized.


Also, you see 4 folds [runs] in that job type not 5 because the first run (`atomic-gorge-239`) run doesn't have the same job type as the other 4. The job type for the other 4 runs is the same `=atomic-gorge-239` [as seen in the second snippet].
 
<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/acc5dfab-4135-44b3-b70c-8a86ff8b342c">

<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/8a4696fa-4472-4bda-847e-9abe09a3d393">

**Comment by anmolmann** [comment] 2023-11-20 17:01
Hey @BagelOrb , here's an example via which you can get cross-validation running without multiprocessing -- 

```
#!/usr/bin/env python
import wandb
import os
import collections
import random

SweepData = collections.namedtuple(
    "SweepData", ("num", "sweep_id", "sweep_run_name", "config")
)


def reset_wandb_env():
    exclude = {
        "WANDB_PROJECT",
        "WANDB_ENTITY",
        "WANDB_API_KEY",
    }
    for key in os.environ.keys():
        if key.startswith("WANDB_") and key not in exclude:
            del os.environ[key]


def train(sweep_data):

    run_name = "{}-{}".format(sweep_data.sweep_run_name, sweep_data.num)
    config = sweep_data.config
    run = wandb.init(
        group=sweep_data.sweep_id,
        job_type=sweep_data.sweep_run_name,
        name=run_name,
        config=config,
        reinit=True
        # project='kFold-without-MP',
        # entity='anmol',
        # id=wandb.util.generate_id()
    )
    val_accuracy = random.random()
    run.log(dict(val_accuracy=val_accuracy))
    run.finish()
    return val_accuracy


def main():
    num_folds = 5

    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    project_url = sweep_run.get_project_url()
    sweep_group_url = "{}/groups/{}".format(project_url, sweep_id)
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown_2"
    sweep_run_id = sweep_run.id
    sweep_run.finish()
    wandb.sdk.wandb_setup._setup(_reset=True)

    metrics = []
    for num in range(num_folds):
        reset_wandb_env()
        result = train(
            SweepData(
                sweep_id=sweep_id,
                num=num,
                sweep_run_name=sweep_run_name,
                config=dict(sweep_run.config),
            )
        )
        metrics.append(result)

    # resume the sweep run
    sweep_run = wandb.init(id=sweep_run_id, resume="must")
    # log metric to sweep run
    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
    sweep_run.finish()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("*" * 40)


if __name__ == "__main__":
    main()
```

As a workaround, we use `_setup(_reset=True)` in the above script. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

<img width="1660" alt="image" src="https://github.com/wandb/wandb/assets/20401632/47e95844-ffba-4d91-adcf-c1f43841e1cf">

**Comment by TimKuipersRobinRadar** [comment] 2023-11-21 10:38
> As a workaround, we use _setup(_reset=True) in the above script to reset the settings which are set during the sweep run initialization. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

I don't understand what you are saying here. For what is this a workaround?

I see you've also added `wandb.init(..., reinit=True)` which seems to be important.

Please note that I did not request to allow for multi-threading - I wanted to be able to do cross validation *without* multi-threading. The example file I've linked to above already shows how to do cross-validation in a multi-processing context. (Or am I confusing multi-threading with multi-processing here?)

The only `WANDB_` env var being deleted by `reset_wandb_env` is WANDB_SERVICE. I've tested and the code also works without `reset_wandb_env`. I've simplified the code for anybody reading this thread in the future:


```
#!/usr/bin/env python
import wandb
import os
import collections
import random


def train(num, sweep_id, sweep_run_name, config):

    run_name = f'{sweep_run_name}-{num}'
    run = wandb.init(
        group=sweep_id,
        job_type=sweep_run_name,
        name=run_name,
        config=config,
        reinit=True
    )
    val_accuracy = random.random()
    run.log(dict(val_accuracy=val_accuracy))
    run.finish()
    return val_accuracy


def main():
    num_folds = 5

    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    project_url = sweep_run.get_project_url()
    sweep_group_url = f'{project_url}/groups/{sweep_id}'
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown_2"
    sweep_run_id = sweep_run.id
    sweep_run.finish()
    wandb.sdk.wandb_setup._setup(_reset=True)

    metrics = []
    for num in range(num_folds):
        result = train(
            sweep_id=sweep_id,
            num=num,
            sweep_run_name=sweep_run_name,
            config=dict(sweep_run.config),
        )
        metrics.append(result)

    # resume the sweep run
    sweep_run = wandb.init(id=sweep_run_id, resume="must")
    # log metric to sweep run
    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
    sweep_run.finish()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("*" * 40)


if __name__ == "__main__":
    main()
```

**Comment by anmolmann** [comment] 2023-11-21 12:28
The reason I thought the user [above](https://github.com/wandb/wandb/issues/6547#issue-1975865928) was interested in mult-threading was because of their use of `multiprocessing.dummy` lib. 
However, to achieve cross-validation either without multi-threading or multi-processing, the [example snippet above](https://github.com/wandb/wandb/issues/6547#issuecomment-1819464812) suffices and works well. Please let me know if it doesn't work for you or in case you have further queries in this regard.

**Comment by TimKuipersRobinRadar** [comment] 2023-11-21 12:43
I'm sorry, the 'other user' is just my alt account. The only reason I mentioned multiprocessing was that the only example of cross validation in your examples library uses multiprocessing. I just wanted to get it to work without multiprocessing. That's why I tried replacing multiprocessing by multiprocessing.dummy as a first step.

Thanks for all your effort. You can close this issue as far as I'm concerned.

You might want to include the sample code above in the reference library. (I hereby absolve the code of any copyright of mine.)

**Comment by BagelOrb** [comment] 2023-11-21 12:45
(just to verify this is indeed my alt account)

**Comment by anmolmann** [comment] 2023-11-21 12:46
> I'm sorry, the 'other user' is just my alt account. The only reason I mentioned multiprocessing was that the only example of cross validation in your examples library uses multiprocessing. I just wanted to get it to work without multiprocessing. That's why I tried replacing multiprocessing by multiprocessing.dummy as a first step.

Ah, I see. No worries, @TimKuipersRobinRadar 
I'll put a PR up to include this code in our reference library. Thanks for your prompt responses. :)

**Closed by anmolmann** 2023-11-21 12:46 UTC
Labels: cli

**Comment by sydholl** [comment] 2023-11-25 13:05
WandB Internal User commented: 
BagelOrb commented: 
Hi @nate-wandb,

Please start by testing the [train-cross-validation.py](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py) from your examples library.

Then change the line `import multiprocessing` in that file for `import multiprocessing.dummy as multiprocessing`.

This change shouldn't introduce a bug, but it does. The parallelism isn't the problem, turning off the parallelism causes the problem somehow. That's really odd.

**Comment by sydholl** [comment] 2023-11-25 13:11
WandB Internal User commented: 
anmolmann commented: 
Hey @BagelOrb, the reason this is happening is because `multiprocessing.dummy` is just a wrapper for the threading lib. Therefore, spinning up multiple threads would cause these threads to share memory and resources across all of the initialized runs. That's why `worker_q.get()` doesn't fetch anything as it gets executed before the `worker.queue.put` call. And, from the snippets you can see the order in which the runs are initialized.


Also, you see 4 folds [runs] in that job type not 5 because the first run (`atomic-gorge-239`) run doesn't have the same job type as the other 4. The job type for the other 4 runs is the same `=atomic-gorge-239` [as seen in the second snippet].
 
<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/acc5dfab-4135-44b3-b70c-8a86ff8b342c">

<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/8a4696fa-4472-4bda-847e-9abe09a3d393">

**Comment by sydholl** [comment] 2023-11-25 13:12
WandB Internal User commented: 
BagelOrb commented: 
Hi @nate-wandb,

Please start by testing the [train-cross-validation.py](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/train-cross-validation.py) from your examples library.

Then change the line `import multiprocessing` in that file for `import multiprocessing.dummy as multiprocessing`.

This change shouldn't introduce a bug, but it does. The parallelism isn't the problem, turning off the parallelism causes the problem somehow. That's really odd.

**Comment by sydholl** [comment] 2023-11-25 13:12
WandB Internal User commented: 
BagelOrb commented: 
Thank you very much for looking into this more deeply.

Perhaps the `multiprocessing.dummy` was besides the point after all. Please have a look at the piece of code I've written.

All I am trying to do is get cross validation working without using threads. I don't want to do multiprocessing, since my models are too resource heavy to do them concurrently.

Please helps me with getting cross validation working. I don't see why the code I had posted above wouldn't work - but I don't know whether that is because of some bug or whether I am just missing some essential piece of code.

Please help. I'm not the only one with this problem. I've looked all over online and found quite some people having problems with this, but haven't found anything close to a solution.

Please make it possible to do cross validation without multiprocessing.

**Comment by sydholl** [comment] 2023-11-25 13:13
WandB Internal User commented: 
anmolmann commented: 
Hey @BagelOrb , here's an example via which you can get cross-validation running without multiprocessing -- 

```
#!/usr/bin/env python
import wandb
import os
import collections
import random

SweepData = collections.namedtuple(
    "SweepData", ("num", "sweep_id", "sweep_run_name", "config")
)


def reset_wandb_env():
    exclude = {
        "WANDB_PROJECT",
        "WANDB_ENTITY",
        "WANDB_API_KEY",
    }
    for key in os.environ.keys():
        if key.startswith("WANDB_") and key not in exclude:
            del os.environ[key]


def train(sweep_data):

    run_name = "{}-{}".format(sweep_data.sweep_run_name, sweep_data.num)
    config = sweep_data.config
    run = wandb.init(
        group=sweep_data.sweep_id,
        job_type=sweep_data.sweep_run_name,
        name=run_name,
        config=config,
        reinit=True
        # project='kFold-without-MP',
        # entity='anmol',
        # id=wandb.util.generate_id()
    )
    val_accuracy = random.random()
    run.log(dict(val_accuracy=val_accuracy))
    run.finish()
    return val_accuracy


def main():
    num_folds = 5

    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    project_url = sweep_run.get_project_url()
    sweep_group_url = "{}/groups/{}".format(project_url, sweep_id)
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown_2"
    sweep_run_id = sweep_run.id
    sweep_run.finish()
    wandb.sdk.wandb_setup._setup(_reset=True)

    metrics = []
    for num in range(num_folds):
        reset_wandb_env()
        result = train(
            SweepData(
                sweep_id=sweep_id,
                num=num,
                sweep_run_name=sweep_run_name,
                config=dict(sweep_run.config),
            )
        )
        metrics.append(result)

    # resume the sweep run
    sweep_run = wandb.init(id=sweep_run_id, resume="must")
    # log metric to sweep run
    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
    sweep_run.finish()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("*" * 40)


if __name__ == "__main__":
    main()
```

As a workaround, we use `_setup(_reset=True)` in the above script. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

<img width="1660" alt="image" src="https://github.com/wandb/wandb/assets/20401632/47e95844-ffba-4d91-adcf-c1f43841e1cf">

**Comment by sydholl** [comment] 2023-11-25 13:17
WandB Internal User commented: 
anmolmann commented: 
Hey @BagelOrb, the reason this is happening is because `multiprocessing.dummy` is just a wrapper for the threading lib. Therefore, spinning up multiple threads [`multiprocessing.dummy.Process()`] would cause **these threads to share memory and resources** across all of the initialized runs, this wouldn't be the case when multiple processes [`multiprocessing.Process()`] are spawned as they don't share the resources. That's why `worker_q.get()` doesn't fetch anything as it gets executed before the `worker.queue.put` call. And, from the snippets you can see the order in which the runs are initialized.
Currently, we don't support spinning multiple threads in the same context. Once we do you'll see this issue resolve itself. May I ask a reason behind using `multiprocessing.dummy` in your script?

Also, you see 4 folds [runs] in that job type not 5 because the first run (`atomic-gorge-239`) run doesn't have the same job type as the other 4. The job type for the other 4 runs is the same `=atomic-gorge-239` [as seen in the second snippet].
 
<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/acc5dfab-4135-44b3-b70c-8a86ff8b342c">

<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/8a4696fa-4472-4bda-847e-9abe09a3d393">

**Comment by sydholl** [comment] 2023-11-25 13:18
WandB Internal User commented: 
TimKuipersRobinRadar commented: 
> As a workaround, we use _setup(_reset=True) in the above script to reset the settings which are set during the sweep run initialization. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

I don't understand what you are saying here. For what is this a workaround?

I see you've also added `wandb.init(..., reinit=True)` which seems to be important.

Please note that I did not request to allow for multi-threading - I wanted to be able to do cross validation *without* multi-threading. The example file I've linked to above already shows how to do cross-validation in a multi-processing context. (Or am I confusing multi-threading with multi-processing here?)

The only `WANDB_` env var being deleted by `reset_wandb_env` is WANDB_SERVICE. I've tested and the code also works without `reset_wandb_env`. I've simplified the code for anybody reading this thread in the future:


```
#!/usr/bin/env python
import wandb
import os
import collections
import random


def train(num, sweep_id, sweep_run_name, config):

    run_name = f'{sweep_run_name}-{num}'
    run = wandb.init(
        group=sweep_id,
        job_type=sweep_run_name,
        name=run_name,
        config=config,
        reinit=True
    )
    val_accuracy = random.random()
    run.log(dict(val_accuracy=val_accuracy))
    run.finish()
    return val_accuracy


def main():
    num_folds = 5

    sweep_run = wandb.init()
    sweep_id = sweep_run.sweep_id or "unknown"
    sweep_url = sweep_run.get_sweep_url()
    project_url = sweep_run.get_project_url()
    sweep_group_url = f'{project_url}/groups/{sweep_id}'
    sweep_run.notes = sweep_group_url
    sweep_run.save()
    sweep_run_name = sweep_run.name or sweep_run.id or "unknown_2"
    sweep_run_id = sweep_run.id
    sweep_run.finish()
    wandb.sdk.wandb_setup._setup(_reset=True)

    metrics = []
    for num in range(num_folds):
        result = train(
            sweep_id=sweep_id,
            num=num,
            sweep_run_name=sweep_run_name,
            config=dict(sweep_run.config),
        )
        metrics.append(result)

    # resume the sweep run
    sweep_run = wandb.init(id=sweep_run_id, resume="must")
    # log metric to sweep run
    sweep_run.log(dict(val_accuracy=sum(metrics) / len(metrics)))
    sweep_run.finish()

    print("*" * 40)
    print("Sweep URL:       ", sweep_url)
    print("Sweep Group URL: ", sweep_group_url)
    print("*" * 40)


if __name__ == "__main__":
    main()
```

**Comment by sydholl** [comment] 2023-11-25 13:21
WandB Internal User commented: 
anmolmann commented: 
The reason I thought the user [above](https://github.com/wandb/wandb/issues/6547#issue-1975865928) was interested in mult-threading was because of their use of `multiprocessing.dummy` lib. 
However, to achieve cross-validation either without multi-threading or multi-processing, the [example snippet above](https://github.com/wandb/wandb/issues/6547#issuecomment-1819464812) suffices and works well. Please let me know if it doesn't work for you or in case you have further queries in this regard.

**Comment by sydholl** [comment] 2023-11-25 13:25
WandB Internal User commented: 
TimKuipersRobinRadar commented: 
> As a workaround, we use _setup(_reset=True) in the above script to reset the settings which are set during the sweep run initialization. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

I don't understand what you are saying here. For what is this a workaround?

I see you've also added `wandb.init(..., reinit=True)` which seems to be important.

Please note that I did not request to allow for multi-threading - I wanted to be able to do cross validation *without* multi-threading. The example file I've linked to above already shows how to do cross-validation in a multi-processing context. (Or am I confusing multi-threading with multi-processing here?)

**Comment by sydholl** [comment] 2023-11-25 13:34
WandB Internal User commented: 
anmolmann commented: 
Hey @BagelOrb, the reason this is happening is because `multiprocessing.dummy` is just a wrapper for the threading lib. Therefore, spinning up multiple threads [`multiprocessing.dummy.Process()`] would cause **these threads to share memory and resources** across all of the initialized runs, this wouldn't be the case when multiple processes [`multiprocessing.Process()`] are spawned as they don't share the resources. That's why `worker_q.get()` doesn't fetch anything as it gets executed before the `worker.queue.put` call. And, from the snippets you can see the order in which the runs are initialized.
Currently, we don't support spinning multiple threads in the same context. Once we do you'll see this issue resolve itself. May I ask a reason behind using `multiprocessing.dummy` in your script?

Also, you see 4 folds [runs] in that job type not 5 because the first run (`atomic-gorge-239`) run doesn't have the same job type as the other 4. The job type for the other 4 runs is the same `=atomic-gorge-239` [as seen in the second snippet].
 
<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/acc5dfab-4135-44b3-b70c-8a86ff8b342c">

<img width="1666" alt="image" src="https://github.com/wandb/wandb/assets/20401632/8a4696fa-4472-4bda-847e-9abe09a3d393">

**Comment by sydholl** [comment] 2023-11-25 13:41
WandB Internal User commented: 
TimKuipersRobinRadar commented: 
> As a workaround, we use _setup(_reset=True) in the above script to reset the settings which are set during the sweep run initialization. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

I don't understand what you are saying here. For what is this a workaround?

I see you've also added `wandb.init(..., reinit=True)` which seems to be important.

Please note that I did not request to allow for multi-threading - I wanted to be able to do cross validation *without* multi-threading. The example file I've linked to above already shows how to do cross-validation in a multi-processing context. (Or am I confusing multi-threading with multi-processing here?)

**Comment by sydholl** [comment] 2023-11-25 13:44
WandB Internal User commented: 
sydholl commented: 
WandB Internal User commented: 
TimKuipersRobinRadar commented: 
> As a workaround, we use _setup(_reset=True) in the above script to reset the settings which are set during the sweep run initialization. However, it is not added as a first-class primitive in our codebase yet. I've also added this as a feature request internally to allow support for multi-threading.

I don't understand what you are saying here. For what is this a workaround?

I see you've also added `wandb.init(..., reinit=True)` which seems to be important.

Please note that I did not request to allow for multi-threading - I wanted to be able to do cross validation *without* multi-threading. The example file I've linked to above already shows how to do cross-validation in a multi-processing context. (Or am I confusing multi-threading with multi-processing here?)

**Comment by BagelOrb** [comment] 2024-03-05 12:44
I noticed one problem with your suggested cross validation code, namely that because you delete WAND_SWEEP_ID from the environment the fold runs of the cross validation won't have the proper Sweep associated. However, when I don't delete it from the environment then the code crashes. 

Adjusting the environment variables feels like a hack.

Now I just use a workaround for logging the correct sweep_id: `log({'sweep_id': sweep_id})`, but I think it's a bit ugly to not have the proper Sweep field logged with the correct values for the fold runs.

Is cross validation such an outdated concept that wandb has such difficulty with it?
