### ISSUE TITLE
[App]: Searching for columns does not display all columns

### ISSUE THREAD

**Issue by zplizzi** [wandb/wandb#4091] opened 2022-08-12 16:02 UTC
### Current Behavior

I have a number of columns in my runs that start with `train/eat/`, such as `train/eat/final_success_mean`. But in the table view, when I go to add a column, and search for this, they don't show up. Actually, they show up for an instant, and then disappear. This happens in both "fuzzy" and "exact" mode. See this loom for an example: https://www.loom.com/share/484a5c6515754d97b61447e65733ed24

### Environment

OS: Mac

Browsers: Chrome

Version: 104

**Comment by Gnabe** [comment] 2022-08-15 14:53
I have the same problem with Chrome and Firefox on Ubuntu

**Comment by justinengelmann** [comment] 2022-08-15 19:35
I have a similar problem. 
Firefox on windows. 
Columns cannot be found with exact, fuzzy or regex search. 
Except that when I search, I can see the matching columns flicker up in the hidden columns section; but then after a split second they disappear. 
I know the columns exist because they can be plotted just fine, I just can't add them in the table view.

**Comment by zplizzi** [comment] 2022-08-15 20:11
For what it's worth, if you copy the tag you want and paste it in the box with your mouse over where the first item will come up, and click at just the right time, you can still select the column to be shown.

**Comment by justinengelmann** [comment] 2022-08-15 23:05
Thanks! That's my current workaround, too, but it's a bit silly.

**Comment by MBakirWB** [comment] 2022-08-18 01:09
Hi @zplizzi , thank-you for reporting this. We are aware of the bug and actively investigating. I will provide an update when a fix has been deployed. Apologies for the inconvenience this is causing.

**Comment by rubencart** [comment] 2022-09-08 09:12
Same problem: https://github.com/wandb/wandb/issues/4248

**Comment by MBakirWB** [comment] 2022-09-12 16:55
@rubencart , thank-you for writing in. The issue is still being worked on.

**Comment by MBakirWB** [comment] 2022-09-16 18:12
@zplizzi @rubencart @justinengelmann @Gnabe. A fix has been released to address this and is immediately reflected in the UI.

**Closed** 2024-11-18 21:05 UTC
Labels: a:app
