### ISSUE TITLE
[Bug-App]: W&B Sweeps do not terminate if the number of runs is large

### ISSUE THREAD

**Issue by RylanSchaeffer** [wandb/wandb#8549] opened 2024-10-04 18:06 UTC
### Describe the bug

I'm trying to run a sweep with 22500 runs. I've now attempted running the sweep twice. In both cases, the sweep failed to stop once finishing all the runs. Here is an example:

https://wandb.ai/rylan/rerevisiting-model-collapse-fit-lin-regr/sweeps/1agbl0la

Right now, it has  `124070` runs out of `22500` total runs and is still going.

**Comment by RylanSchaeffer** [comment] 2024-10-04 18:18
I can also now no longer delete the sweeps or delete the project

**Comment by RylanSchaeffer** [comment] 2024-10-10 16:12
> Have you experienced the same issue with any of the other Sweep you have run since?

Yes. This is a pretty common experience.  If you look at this project https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps you'll see that the number of runs per sweep pretty much always exceeds the correct number. For instance, you'll see sweeps with [4533](https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/s1anms73), [4523](https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/yar30vwc), [4585](https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/m1li7d4q), [4634](https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/isodemet) runs. These should all be 4500.

> What computing environment have you been using to start the agents and what command or code did you use to start the parallel agents?

These runs are CPU only (no GPU) and run in separate processes in separate tmux sessions.

**Comment by RylanSchaeffer** [comment] 2024-10-10 16:13
It appears to me that W&B sweeps can't keep track of so many runs and agents, and begin screwing up as the number of runs and agents increases. Then, if the number of runs and agents is too large, the sweep completely fails to track what has been completed.

**Comment by RylanSchaeffer** [comment] 2024-10-11 15:55
This keeps happening for large sweeps. Here is another sweep that should have 1k runs but somehow has 2.5k runs

https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/e1o3scvu/table?nw=nwuserrylan

**Comment by RylanSchaeffer** [comment] 2024-10-11 15:59
What's weird with the above sweep is that 2.5k runs displayed but 5 agents each display ~240 runs:

![Image](https://github.com/user-attachments/assets/557f78bc-e2ac-4f70-a693-c912335e08bb)

Unless agents disappear, that math doesn't make sense

**Comment by RylanSchaeffer** [comment] 2024-10-14 16:36
The problem is still ongoing...

Example: https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/vl8bvwnp/overview

@fmamberti-wandb I wanted to follow up on this request. Please let me know if you can be of further assistance

**Comment by fmamberti-wandb** [comment] 2024-10-15 15:51
Hi @RylanSchaeffer , thank you sharing the additional information.  I will be working to reproduce the behaviour on my end. Would you be able to share:

- A snippet of code from the script ran via the sweeps? Especially how the run is being initialised.

Re how the agents are run: `These runs are CPU only (no GPU) and run in separate processes in separate tmux sessions`. Are the sessions all running on the same compute node or are you starting sessions on different compute nodes? Do the nodes have constant access to the internet (specifically `api.wandb.api`?)

**Comment by RylanSchaeffer** [comment] 2024-10-15 15:55
> A snippet of code from the script ran via the sweeps? Especially how the run is being initialised.

Of course!

```
    run = wandb.init(
        project="rerevisiting-model-collapse-fit-kdes",
        config=src.globals.DEFAULT_KERNEL_DENSITY_FITTING_CONFIG,
        entity=wandb.api.default_entity,
    )
```

`src.globals.DEFAULT_KERNEL_DENSITY_FITTING_CONFIG` is just a python dictionary of simple objects (strings, floats, etc.). Then at the end of the python script, I call `wandb.finish()`.

**Comment by RylanSchaeffer** [comment] 2024-10-15 15:57
The actual script I've been using isn't all that long. Here is the script:

```
import numpy as np
import os
import pprint
from sklearn.neighbors import KernelDensity
from typing import Any, Dict, Tuple
import wandb

import src.globals
import src.data


def fit_kernel_density_estimators():
    run = wandb.init(
        project="rerevisiting-model-collapse-fit-kdes",
        config=src.globals.DEFAULT_KERNEL_DENSITY_FITTING_CONFIG,
        entity=wandb.api.default_entity,
    )

    # Convert to a dictionary; otherwise, can't distribute because W&B
    # config is not pickle-able.
    wandb_config: Dict[str, Any] = dict(wandb.config)
    pprint.pprint(wandb_config)

    # Set the random seed for reproducibility
    np.random.seed(wandb_config["seed"])

    setting = wandb_config["setting"]
    assert setting in {"Accumulate", "Accumulate-Subsample", "Replace"}
    num_samples_per_iteration = wandb_config["num_samples_per_iteration"]

    init_data_train = src.data.create_dataset_for_kde(
        num_samples_per_iteration=wandb_config["num_samples_per_iteration"],
        data_config_dict=wandb_config["data_config"],
    )[0]
    init_data_test = src.data.create_dataset_for_kde(
        num_samples_per_iteration=500,  # Hard coded to ensure we have a large population of data for evaluation.
        data_config_dict=wandb_config["data_config"],
    )[0]
    all_data_train = init_data_train.copy()

    # sklearn also permits two string bandwidths ("scott", "silverman").
    # If the bandwidth can be a float, make it a float.
    # Otherwise, it's a string; check that it's one of the two allowed strings.
    bandwidth = wandb_config["kernel_bandwidth"]
    try:
        bandwidth = float(bandwidth)
    except ValueError:
        assert isinstance(bandwidth, str)
        assert bandwidth in {"scott", "silverman"}

    kde = KernelDensity(kernel=wandb_config["kernel"], bandwidth=bandwidth)

    # Iterate over the number of iterations
    for iteration_idx in range(1, wandb_config["num_iterations"] + 1):
        if setting in {"Accumulate", "Replace"}:
            # Fit the data.
            kde.fit(all_data_train)
        elif setting in {"Accumulate-Subsample"}:
            # Subsample the total data.
            subsample_idx = np.random.choice(
                np.arange(all_data_train.shape[0]),
                size=num_samples_per_iteration,
                replace=False,
            )
            kde.fit(all_data_train[subsample_idx])
        else:
            raise ValueError(f"Unknown setting: {setting}")

        # Score the test data.
        mean_neg_log_prob_test = -np.mean(kde.score_samples(init_data_test))

        # Create data for the next model-fitting iteration.
        new_data = kde.sample(n_samples=num_samples_per_iteration)
        if setting == "Replace":
            all_data_train = new_data
        elif setting in {"Accumulate", "Accumulate-Subsample"}:
            all_data_train = np.concatenate((all_data_train, new_data))
        else:
            raise ValueError(f"Unknown setting: {setting}")

        wandb.log(
            {
                "Model-Fitting Iteration": iteration_idx,
                "Mean Negative Log Prob (Test)": mean_neg_log_prob_test,
            },
        )

    wandb.finish()


if __name__ == "__main__":
    fit_kernel_density_estimators()
    print("Finished fit_kdes.py!")
```

And here are the two imports you'll also need:

```
DEFAULT_KERNEL_DENSITY_FITTING_CONFIG = {
    "data_config": {
        "dataset_name": "blobs",
        "dataset_kwargs":
            "n_features": 2,
        },
    },
    "kernel": "gaussian",
    "kernel_bandwidth": 0.75,
    "num_samples_per_iteration": 100,
    "num_iterations": 100,
    "seed": 0,
    "setting": "Accumulate",
}
```

and 

```
def create_dataset_for_kde(
    num_samples_per_iteration: int, data_config_dict: Dict[str, Any]
):
    dataset_name = data_config_dict["dataset_name"]

    if dataset_name == "blobs":
        from sklearn import datasets

        init_data = datasets.make_blobs(
            n_samples=num_samples_per_iteration,
            **data_config_dict["dataset_kwargs"],
        )
    elif dataset_name == "circles":
        from sklearn import datasets

        init_data = datasets.make_circles(
            n_samples=num_samples_per_iteration,
            **data_config_dict["dataset_kwargs"],
        )
    elif dataset_name == "moons":
        from sklearn import datasets

        init_data = datasets.make_moons(
            n_samples=num_samples_per_iteration,
            **data_config_dict["dataset_kwargs"],
        )
    elif dataset_name == "swiss_roll":
        from sklearn import datasets

        # We multiply by 2 because we need test data too!
        init_data = datasets.make_swiss_roll(
            n_samples=num_samples_per_iteration,
            **data_config_dict["dataset_kwargs"],
        )
    else:
        raise ValueError(f"Unknown dataset name: {dataset_name}")
    return init_data
```

**Comment by fmamberti-wandb** [comment] 2024-10-17 11:56
Thank you for sharing all the information @RylanSchaeffer . I will work to repro on my end and will keep you posted

**Comment by RylanSchaeffer** [comment] 2024-10-19 02:46
@fmamberti-wandb I killed the old sweeps because they weren't finishing and created new sweeps. Now I have a new problem in this sweep: https://wandb.ai/rylan/rerevisiting-model-collapse-fit-kdes/sweeps/k0zp4ich/overview

My agents keep saying `wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)` and don't finish.

This is becoming increasing frustrating.

**Comment by thanos-wandb** [comment] 2024-11-05 13:27
Hi @RylanSchaeffer I wanted to follow up on this issue, and gather some additional information to help us troubleshooting:
- do you still notice it in any new sweeps?
- were you deleting any of the sweep runs before sweeps completion?
- how many agents were you executing in parallel?
- it seems the sweeps in `rerevisiting-model-collapse-fit-lin-regr`  page (except `1agbl0la`) to have almost terminated within the estimated runs count (there are few exceptions with some extra runs, which could be explained from above 2 questions). 
- do you still have available the logs from the agents? (the`wandb/debug-cli.*user*.log` files)

**Comment by thanos-wandb** [comment] 2024-11-08 14:36
Hi @RylanSchaeffer we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by RylanSchaeffer** [comment] 2024-11-08 16:49
@thanos-wandb it took you 3 weeks to respond and you nudge me for a response after 3 days. I had to pivot to a different project because I was blocked on this project. Please give me till the weekend to context switch back.

**Comment by RylanSchaeffer** [comment] 2024-11-08 16:50
I still remember when W&B had a help chat feature where a live person would help solve your problem in minutes :(

**Comment by thanos-wandb** [comment] 2024-11-08 17:15
Hi @RylanSchaeffer, I completely understand, and I apologize for the delay you've experienced. This issue just came my way this week, and I'm here to make sure we get it resolved as soon as possible. The ticket will remain open, so please feel free to share any additional details whenever it works best for you. We're committed to addressing this thoroughly, and I appreciate your patience in the meantime.

**Comment by thanos-wandb** [comment] 2024-11-13 11:25
Hi @RylanSchaeffer just checking in on this issue, had you had a chance to gather those additional information above? thanks so much.

**Comment by thanos-wandb** [comment] 2024-11-19 15:08
Hi @RylanSchaeffer just a quick follow-up to let you know that I’m actively looking into this. I’m currently running a large sweep using the grid method to see if the issue can be reproduced. I’ll keep you updated on my findings. If you had the time to run a new sweep on your end, where this issue occurred - please feel free to share any additional context. Thank you for your patience.

**Comment by thanos-wandb** [comment] 2024-11-26 11:46
Hi @RylanSchaeffer this hasn't been possible to be reproduced on our end, when running very large sweeps (>10000 runs) using the `grid` method. Since it's expensive to try various configurations/parameters and see when it fails any more details would be much appreciated and helpful to troubleshoot further - it might be related to the environment you are running your code, eg are the agents containerised and are you running many in parallel? are you deleting runs in the meantime? 

Since we haven't heard back from you in a while, I will have to close this ticket for now as part of our ticket admin process, but please be assured, we’re not dropping it. I am more than happy to dig deeper into this issue as soon as you’re able to provide additional information or context. Feel free to reopen this ticket anytime, and we will continue investigating. Thanks again for your patience and understanding!

**Closed by thanos-wandb** 2024-11-26 11:46 UTC
Labels: ty:bug, c:sweeps, a:app
