### ISSUE TITLE
[App]: Run summary has stopped working

### ISSUE THREAD

**Issue by davidgilbertson** [wandb/wandb#5653] opened 2023-06-02 02:56 UTC
### Current Behavior

I'm not sure if I've changed something that broke this, or if there's a bug in the platform, but I'm no longer seeing summary data. In this screenshot, `val/accuracy` stopped showing up in the last column, even though it's being logged just the same.
![image](https://github.com/wandb/wandb/assets/4443482/d53359b7-3d29-4d07-b8a5-d647316f2e14)

If I jump to the details for that run I see this in the overview:
![image](https://github.com/wandb/wandb/assets/4443482/fb7dda0f-1ee9-4556-8a76-7e5e9f9a9f56)

If I just do this:
```py
run = wandb.init(...)
for i in range(10):
    log_dict = {
        "loss": random.uniform(0, 1 / (i + 1)),
        "acc": random.uniform(1 / (i + 1), 1),
    }
    wandb.log(log_dict)

run.finish()
```

I see this in the console:
![image](https://github.com/wandb/wandb/assets/4443482/2780440a-424c-4e73-97df-157a84f0751d)

But this in the UI: "No summary metrics saved for this run"

However if I don't do `run.finish()` but then call it manually a few seconds later, I _do_ see a summary in the UI.

Please note that I have always done `run.finish()` in the past and gotten a summary, and if I don't do this then wandb doesn't work correctly in PyCharm Python Console (it doesn't complete the run after I run my code, and also will break if I run a cell multiple times to perform multiple runs).

It's only in the last day or so that summaries have stopped working. I haven't updated the wandb package recently, so I suspect it's a problem in the platform, or something else.

### Environment

OS: Windows

Browsers: Chrome

Version: 0.15.2

**Comment by davidgilbertson** [comment] 2023-06-02 03:34
Actually I think this is causing my sweeps to fail too. I have some code that ran a successful sweep this morning, I've just run it again now (the same code) and the sweep is no longer registering the val/accuracy and so fails.

![image](https://github.com/wandb/wandb/assets/4443482/abbc7d97-acbb-49e2-be7f-0af92d200c57)

Did you happen to push an update to the platform a few hours ago?

**Comment by self-disciplineprogress** [comment] 2023-06-02 04:01
I also encountered the same problem this morning

**Comment by ZedRover** [comment] 2023-06-02 06:23
same problem till now, I can see the log summary file in the artifacts, but it's not shown in the Table

**Comment by marshuang80** [comment] 2023-06-02 10:04
Same problem here. Did anyone find a solution?

**Comment by thanos-wandb** [comment] 2023-06-02 11:15
Hi @davidgilbertson @marshuang80 @ZedRover @self-disciplineprogress we're really sorry for any inconvenience this issue has caused.

Just a quick update here, this was escalated as a P0 issue, our Infra team identified the cause and have rolled back the change. Any new runs should show up the metrics in summary table now. The summary of the affected runs will be backfilled, this process has started and you should soon see the metrics being populated there.

I can keep you posted here once the backfilling has been completed. Thank you!

**Comment by thanos-wandb** [comment] 2023-06-02 14:42
Hi everyone, the backfill of the summary metrics should be completed by now. I will now close this ticket, but please do let us know if you're still experiencing any issue and we will be happy to keep investigating. Thanks all for your patience.

**Closed by thanos-wandb** 2023-06-02 14:42 UTC
Labels: app
