### ISSUE TITLE
[Q] Setting WANDB_NOTEBOOK_NAME and storing Databricks notebooks in wandb

### ISSUE THREAD

**Issue by kstathou** [wandb/wandb#3116] opened 2022-01-06 13:25 UTC
Hi, I'd like to save a Databricks notebook in `wandb` and display it in the Code menu of wandb's UI. I am trying the following:

```python
import wandb
import os

os.environ["WANDB_NOTEBOOK_NAME"] = "/Repos/my-repo/my-notebook"

api_key = dbutils.secrets.get("wandb", "my-api-key")
wandb.login(key=api_key)

wandb.init(project="my-project", save_code=True)

wandb.log({"my_var": 123})

wandb.finish()
```

It logs the run and its variables as expected, however, I receive the following warning when running `wandb.login(key=api_key)` and it doesn't create a ` _session_history.ipynb` object:

```
wandb: WARNING WANDB_NOTEBOOK_NAME should be a path to a notebook file, couldn't find /Repos/my-repo/my-notebook
```

Note: Regular jupyter notebooks work fine, I only have this issue with Databricks. Any ideas? 

Thanks a lot!

**Comment by vanpelt** [comment] 2022-01-06 22:06
I'm assuming there's no file named `/Repos/my-repo/my-notebook` on that machine.  I haven't tried databricks notebooks for some time, but you should be setting `WANDB_NOTEBOOK_NAME` to the path for the `notebook.ipynb` file that's currently open.

**Comment by kstathou** [comment] 2022-01-07 12:45
Hi @vanpelt, thanks a lot for the reply! 

I was picking up the path with `dbutils.notebook.entry_point.getDbutils().notebook().getContext().notebookPath().get()` which was removing `/Workspace/` from the full path. 

My initial error is fixed but I came across the following when running `wandb.init(project="my-project", save_code=True, dir="/tmp")`:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/databricks/python/lib/python3.8/site-packages/backcall/backcall.py in adapted(*args, **kwargs)
    102                 kwargs.pop(name)
    103 #            print(args, kwargs, unmatched_pos, cut_positional, unmatched_kw)
--> 104             return callback(*args, **kwargs)
    105 
    106         return adapted

/databricks/python/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in _pause_backend(self)
    284             logger.info("pausing backend")
    285             # Attempt to save the code on every execution
--> 286             if self.notebook.save_ipynb():
    287                 res = self.run.log_code(root=None)
    288                 logger.info("saved code: %s", res)

/databricks/python/lib/python3.8/site-packages/wandb/jupyter.py in save_ipynb(self)
    378         if relpath:
    379             if os.path.exists(relpath):
--> 380                 shutil.copy(
    381                     relpath,
    382                     os.path.join(

/usr/lib/python3.8/shutil.py in copy(src, dst, follow_symlinks)
    416     if os.path.isdir(dst):
    417         dst = os.path.join(dst, os.path.basename(src))
--> 418     copyfile(src, dst, follow_symlinks=follow_symlinks)
    419     copymode(src, dst, follow_symlinks=follow_symlinks)
    420     return dst

/usr/lib/python3.8/shutil.py in copyfile(src, dst, follow_symlinks)
    262         os.symlink(os.readlink(src), dst)
    263     else:
--> 264         with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    265             # macOS
    266             if _HAS_FCOPYFILE:

OSError: [Errno 95] Operation not supported: '/Workspace/Repos/my-repo/my-notebook'
```

The error is caused when `save_code=True`. Initially, I thought it was caused due to this [Databricks design](https://kb.databricks.com/dbfs/errno95-operation-not-supported.html), however, the error persists with both local storage and a mounted S3 bucket. Any ideas?

**Comment by vanpelt** [comment] 2022-01-07 21:10
Thar error indicates we can't read that file from the filesystem.  Are we sure that's a file, or is it a directory.  Can you run `ls -al` in the `my-repo` and or `my-notebook` directories?

**Comment by kstathou** [comment] 2022-01-10 15:47
Hi @vanpelt, I ran `ls -al` in `my-repo`:

```
total 0
drwxrwxrwx 2 root root 0 Jan 10 15:40 .
drwxrwxrwx 2 root root 0 Jan 10 15:40 ..
-rwxrwxrwx 1 root root 0 Jan  1  1970 my-notebook
-rwxrwxrwx 1 root root 0 Jan  1  1970 my-notebook-2
```

In case it's helpful, I changed the `dir` to `wandb.init(project="my-project", save_code=True, dir="/Workspace/Repos/my-repo/")` and got a slightly extended error message:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/databricks/python/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
    927         wi = _WandbInit()
--> 928         wi.setup(kwargs)
    929         except_exit = wi.settings._except_exit

/databricks/python/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in setup(self, kwargs)
    208         if not settings._noop:
--> 209             self._log_setup(settings)
    210 

/databricks/python/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in _log_setup(self, settings)
    340         """Sets up logging from settings."""
--> 341         filesystem._safe_makedirs(os.path.dirname(settings.log_user))
    342         filesystem._safe_makedirs(os.path.dirname(settings.log_internal))

/databricks/python/lib/python3.8/site-packages/wandb/sdk/lib/filesystem.py in _safe_makedirs(dir_name)
     10     try:
---> 11         os.makedirs(dir_name)
     12     except OSError as e:

/usr/lib/python3.8/os.py in makedirs(name, mode, exist_ok)
    212         try:
--> 213             makedirs(head, exist_ok=exist_ok)
    214         except FileExistsError:

/usr/lib/python3.8/os.py in makedirs(name, mode, exist_ok)
    212         try:
--> 213             makedirs(head, exist_ok=exist_ok)
    214         except FileExistsError:

/usr/lib/python3.8/os.py in makedirs(name, mode, exist_ok)
    222     try:
--> 223         mkdir(name, mode)
    224     except OSError:

OSError: [Errno 38] Function not implemented: '/Workspace/Repos/my-repo/wandb'

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<command-3626329098573567> in <module>
----> 1 wandb.init(project="my-project", save_code=True, dir="/Workspace/Repos/my-repo/")

/databricks/python/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
    967             if except_exit:
    968                 os._exit(-1)
--> 969             six.raise_from(Exception("problem"), error_seen)
    970     return run

/databricks/python/lib/python3.8/site-packages/six.py in raise_from(value, from_value)

Exception: problem
```

**Comment by vanpelt** [comment] 2022-01-11 00:02
@kstathou it looks like notebook code saving is unable to work in databricks notebooks because it's not providing a real filesystem at `/Workspace/Repos/...` we'll need to dig in and attempt to reproduce.  I wonder if `/tmp` is writable.  One thing to try would be setting `dir="/tmp"` and see if that still causes errors.

**Comment by kstathou** [comment] 2022-01-11 09:50
Hi @vanpelt, thanks again for the help! I tried `dir="/tmp"` but got this error: 
```
OSError: [Errno 95] Operation not supported: '/Workspace/Repos/my-repo/my-notebook
```

I confirmed we can write to `/tmp` but I think the problem is that Databricks doesn't allow copying from `/Workspace/Repos/...`. I tried to `%sh cp my-notebook /tmp/my-notebook` and received the following error: 

```
cp: cannot open 'my-notebook' for reading: Operation not supported
```

**Comment by aidanjdonohue** [comment] 2022-01-24 20:50
Thanks for the info. We're looking into this and will keep you updated here.

**Comment by kijewskimateusz** [comment] 2023-04-14 15:33
@kstathou By any chance have you found a solution for this issue? I have noticed too that we are unable to cp / cat or open Databricks notebook files

**Comment by sydholl** [comment] 2023-10-12 22:01
WandB Internal User commented: 
github-actions[bot] commented: 
This issue is stale because it has been open 60 days with no activity.

**Comment by kptkin** [comment] 2024-04-18 02:32
I think this issue should be solved now. Closing this ticket if it is still an issue

**Closed by kptkin** 2024-04-18 02:32 UTC
Labels: env:notebook, a:cli
