### ISSUE TITLE
[Q] How can I compare different types of data from different experiments?

### ISSUE THREAD

**Issue by be-well** [wandb/wandb#6221] opened 2023-09-05 07:49 UTC
I want to show two data from experiment A and one data from experiment B in the same graph to compare the three curves. However, I can only choose the data type, but not the specific experiment, which leads to the selection of two types of data in experiment B.

**Comment by rsanandres-wandb** [comment] 2023-09-06 20:32
Hello @be-well !

You can use a Report to do this. Once you add a plot from the first project, add the second run set (experiment) to the panel grid and you will be able to graph data from both experiments in one graph. See the video below for how to do this.




https://github.com/wandb/wandb/assets/122482606/d745bc25-251c-4c1f-82d8-00bc6a2a9208

**Comment by rsanandres-wandb** [comment] 2023-09-07 15:28
.

**Comment by sydholl** [comment] 2023-09-08 22:08
Raphael San Andres commented: 
Hello @be-well !

You can use a Report to do this. Once you add a plot from the first project, add the second run set (experiment) to the panel grid and you will be able to graph data from both experiments in one graph. See the video below for how to do this.

**Comment by sydholl** [comment] 2023-09-08 22:08
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello @be-well !

You can use a Report to do this. Once you add a plot from the first project, add the second run set (experiment) to the panel grid and you will be able to graph data from both experiments in one graph. See the video below for how to do this.




https://github.com/wandb/wandb/assets/122482606/d745bc25-251c-4c1f-82d8-00bc6a2a9208

**Comment by sydholl** [comment] 2023-09-08 22:08
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by be-well** [comment] 2023-09-09 10:16
I'm sorry I didn't explain the problem clearly. And I want to re-open the conversation.

I ran two experiments (called "origalgo"and "training"respectively) in the same project, the same group but different job types. The "training" has two recorded sets of data: "win_rate" and "stu_win_rate" while the "origalgo" has only the former "win_rate". 

Now, I want to plot these three pieces of data on a picture for comparison. When I select the two sets of data simultaneously, the graph will display four curves: "win_rate" and "stu_win_rate", for "training" and "origalgo" respectively. 

The "stu_win_rate" for  "origalgo" does not exist, and it is plotted using the data same as "win_rate", which is not what I want. I just want the other 3 curves. How can I do that?

By the way, I want to pull another question: When I select multiple experiments in the same job type, a curve with a shaded area would be plotted. I want the shaded area to be plotted based on the 25th and 75th percentiles (if it's possible to choose custom percentiles, that would be even better), but there are no such options. How can this be achieved?

**Comment by rsanandres-wandb** [comment] 2023-09-13 01:23
Hello! Ah, I have been able to reproduce this behavior now. For future viewers, I have attached an image of the described behavior. There are two lines in the legend of `metric_A` and `metric_B` for `smart-breeze-2` despite `smart-breeze-2` only logging values for `metric_A`.  You could create a [Vega Spec in a Custom Chart](https://docs.wandb.ai/guides/app/features/custom-charts) but there is no `wandb` preset that would be able to do what you are looking for so if you go down this route, you would have to create your own Vega Spec. I will report this to the team as a behavior and see what they think

[Project for Reference](https://wandb.ai/raph-test/multiple-metrics-test?workspace=user-raphael-sanandres)
<img width="1206" alt="image" src="https://github.com/wandb/wandb/assets/122482606/19ccd4be-0e03-4ec5-9f7e-12ce38def0d5">
<img width="965" alt="image" src="https://github.com/wandb/wandb/assets/122482606/e4773258-03f5-4823-99da-3426cc9c7595">


As for the second point that you made:
```When I select multiple experiments in the same job type, a curve with a shaded area would be plotted. I want the shaded area to be plotted based on the 25th and 75th percentiles```

[Here are the current options](https://docs.wandb.ai/guides/runs/grouping#grouping-graph-settings) we have for grouping charts. The closest we currently have is to have the shaded area be `Std Dev` but we do not currently support custom percentiles as you mentioned. I can certainly make a feature request if you wish.

**Comment by be-well** [comment] 2023-09-13 06:02
I am grateful for your detailed reply to my question. I finally accomplished this by downloading the source data and drawing it in Python.

**Comment by rsanandres-wandb** [comment] 2023-09-13 19:41
Perfect! Good to hear you were able to find a solution.  I will be closing out this thread but feel free to make a new one if you have any more questions.

**Closed by rsanandres-wandb** 2023-09-13 19:41 UTC
