### ISSUE TITLE
[CLI]: hangs when stopping a run when using PyCharm, forced to SIGKILL

### ISSUE THREAD

**Issue by logan-dunbar** [wandb/wandb#5991] opened 2023-08-02 15:46 UTC
### Describe the bug

WandB hangs at the end of a run when running using PyCharm's debugger/runner. After pressing the 'stop' button which should trigger the equivalent of ctrl+c I receive the below error after a few seconds pause, and then I am forced to kill the process by issuing a SIGKILL.

Run the below code for about a minute and then press the stop button, the stacktrace below shows up and I'm forced to kill the process.

When I run the sample using normal bash, things finish properly and I receive the second trace below. I use a lot of PyCharm's integrated runner/debugger, so it is a hassle for WandB to keep hanging at the end of every run. Would be awesome if you could take a look and sort this out please!

```python
from time import sleep
import wandb
import numpy as np


def main():
  wandb.login()

  with wandb.init(
    dir='../',
    project="wandb-test") as run:

    for i in range(1000):
      sleep(5)
      run.log(dict(episode=i, reward=np.random.random()))


if __name__ == '__main__':
  main()

```

```shell
wandb: Currently logged in as: ____. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.8
wandb: Run data is saved locally in ../wandb/____
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run cosmic-water-3
wandb: ⭐️ View project at https://wandb.ai/____/wandb-test
wandb: 🚀 View run at https://wandb.ai/____/wandb-test/____

Aborted!
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
Exception in thread Thread-11 (_thread_body):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "____/venv/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 172, in _thread_body
    self._handle_event(event)
  File "____/venv/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 236, in _handle_event
    self._start_upload_job(event)
  File "____/venv/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 257, in _start_upload_job
    self._spawn_upload_sync(event)
  File "____/venv/lib/python3.10/site-packages/wandb/filesync/step_upload.py", line 292, in _spawn_upload_sync
    self._pool.submit(run_and_notify)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 167, in submit
    raise RuntimeError('cannot schedule new futures after shutdown')
RuntimeError: cannot schedule new futures after shutdown

# after killing the process
Process finished with exit code 137 (interrupted by signal 9: SIGKILL)
```

```shell
wandb: Currently logged in as: ____. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.8
wandb: Run data is saved locally in ../wandb/____
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run eternal-blaze-2
wandb: ⭐️ View project at https://wandb.ai/____/wandb-test
wandb: 🚀 View run at https://wandb.ai/____/wandb-test/runs/____
^Cwandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 
wandb: Run history:
wandb: episode ▁▁▂▃▃▃▄▅▅▅▆▇▇▇█
wandb:  reward ▁▁▇▄▃█▃▂▃▆▃▆█▇▇
wandb: 
wandb: Run summary:
wandb: episode 14
wandb:  reward 0.80094
wandb: 
wandb: 🚀 View run eternal-blaze-2 at: https://wandb.ai/____/wandb-test/runs/____
wandb: ️⚡ View job at https://wandb.ai/____/wandb-test/jobs/____/version_details/v0
wandb: Synced 4 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ../wandb/____/logs
Traceback (most recent call last):
  File "____/wandb_test.py", line 19, in <module>
    main()
  File "____/wandb_test.py", line 14, in main
    sleep(5)
KeyboardInterrupt

```

### Additional Files

It looks like the only difference is that the one that fails never gets to rendering the footer, with the footer function calls the only difference between the log files:  `_footer_history_summary_info()` and `_footer_sync_info()` are not in the failed log.

[debug_log (success).txt](https://github.com/wandb/wandb/files/12241957/debug_log.success.txt)
[debug_log (failure).txt](https://github.com/wandb/wandb/files/12241959/debug_log.failure.txt)

#### \*\*\*Edit\*\*\*
[debug_internal (failure).txt](https://github.com/wandb/wandb/files/12254700/debug_internal.failure.txt)
[debug_internal (success).txt](https://github.com/wandb/wandb/files/12254701/debug_internal.success.txt)

### Environment

WandB version: **0.15.8**

OS: **ubuntu 20.04**

Python version: **3.10.12**

**Comment by rsanandres-wandb** [comment] 2023-08-03 16:53
Hello @logan-dunbar !

One more thing that would be helpful would be the `debug-internal.log` which should be in the same folder as the `debug.log`. The `debug-internal.log` provides the log of the processes which should help trace to which process is hanging.

**Comment by logan-dunbar** [comment] 2023-08-03 20:07
Hi @rsanandres-wandb, I have added the requested file to the issue above, thanks for looking into this!

**Comment by logan-dunbar** [comment] 2023-08-11 11:25
@rsanandres-wandb I'll try that, but I thought the `with wandb.init(` context manager would handle that implicitly (like automatic file handler closing), surely that is how it should be implemented? Will I need to put the `finish()` call in a `try:` `finally:`, because just adding at the end will not ensure it is actually called, right? Running some experiments at the moment, but I'll try this as soon as I get a chance.

**Comment by logan-dunbar** [comment] 2023-08-11 11:37
The context manager is already calling finish for me in [wandb_run.py#L3050](https://github.com/wandb/wandb/blob/0846effe26f41c9af1afdcdb9ff6a7ecb1e8d0c8/wandb/sdk/wandb_run.py#L3050):

```python
    def __exit__(
        self,
        exc_type: Type[BaseException],
        exc_val: BaseException,
        exc_tb: TracebackType,
    ) -> bool:
        exit_code = 0 if exc_type is None else 1
        self._finish(exit_code)
        return exc_type is None
```
So I doubt adding a `wandb.finish()` call will change anything, it seems like there is something else going on.

**Comment by rsanandres-wandb** [comment] 2023-08-16 18:20
After looking around and attempting to reproduce this, this does look to be a compatibility issue between us and the PyCharm debugger and I will be reporting this to the team.

**Comment by sydholl** [comment] 2024-02-15 00:11
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello @logan-dunbar !

One more thing that would be helpful would be the `debug-internal.log` which should be in the same folder as the `debug.log`. The `debug-internal.log` provides the log of the processes which should help trace to which process is hanging.

**Comment by sydholl** [comment] 2024-02-15 00:11
WandB Internal User commented: 
logan-dunbar commented: 
Hi @rsanandres-wandb, I have added the requested file to the issue above, thanks for looking into this!

**Comment by sydholl** [comment] 2024-02-15 00:11
WandB Internal User commented: 
logan-dunbar commented: 
@rsanandres-wandb I'll try that, but I thought the `with wandb.init(` context manager would handle that implicitly (like automatic file handler closing), surely that is how it should be implemented? Will I need to put the `finish()` call in a `try:` `finally:`, because just adding at the end will not ensure it is actually called, right? Running some experiments at the moment, but I'll try this as soon as I get a chance.

**Comment by sydholl** [comment] 2024-02-15 00:11
WandB Internal User commented: 
logan-dunbar commented: 
The context manager is already calling finish for me in [wandb_run.py#L3050](https://github.com/wandb/wandb/blob/0846effe26f41c9af1afdcdb9ff6a7ecb1e8d0c8/wandb/sdk/wandb_run.py#L3050):

```python
    def __exit__(
        self,
        exc_type: Type[BaseException],
        exc_val: BaseException,
        exc_tb: TracebackType,
    ) -> bool:
        exit_code = 0 if exc_type is None else 1
        self._finish(exit_code)
        return exc_type is None
```
So I doubt adding a `wandb.finish()` call will change anything, it seems like there is something else going on.

**Comment by sephmard** [comment] 2024-08-22 20:04
Hey @logan-dunbar, i wanted to provide an update. We have a new Go based client that improves logging reliability:  https://wandb.me/wandb-core. This update includes some stability improvements that might help with the run hangs issue you encountered. You can try it out by adding upgrading wandb and adding wandb.require("core") to your scripts. 

Mind letting us know if this helps?

**Closed** 2024-08-27 16:18 UTC
Labels: c:core, a:cli, s:nexus-fix
