### ISSUE TITLE
BO and random search not exploring search space

### ISSUE THREAD

**Issue by dreamflasher** [wandb/wandb#1082] opened 2020-06-03 16:49 UTC
wandb, version 0.8.36
Python 3.8.2
Linux

### Description

I am doing a wandb sweep. The sweep config has only discrete values and a low space size of about 30 unique configurations.

Expectation: All 30 configurations are tested after each other.

Actually: A few configurations are tested multiple times, while others are not run at all.

I observe this both with BO and random search.

**Comment by ariG23498** [comment] 2020-12-04 05:46
Hey @dreamflasher 
Could you let us know whether we could close this ticket?

**Comment by dreamflasher** [comment] 2021-02-03 12:50
> 
> 
> Hey @dreamflasher
> Could you let us know whether we could close this ticket?

As soon as it's fixed, sure ;) 
Afaik the proposed changes are not done yet?

**Comment by sydholl** [comment] 2024-11-21 21:41
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Closed by sydholl** 2024-11-21 21:41 UTC
Labels: ty:bug, c:sweeps
