### ISSUE TITLE
Store layout across sweeps per project

### ISSUE THREAD

**Issue by dreamflasher** [wandb/wandb#948] opened 2020-03-31 07:09 UTC
wandb, version 0.8.31
Python 3.8.2
Linux

### Description

As a user I can customize which columns are shown (and in which order) in the sweep view. 
But this configuration is not saved between individual sweeps. 
By now in my project there are hundreds of columns shown by default, from all previous runs, out of which I need maybe 10. I don't want to select these columns at every new sweep.
I don't know what an ideal solution is here, but the current one where the view config is per sweep is not good. For me personally (but of course there are others with other  needs) it would be sufficient if I change the view for all sweeps per project. And it would be even better if all sweeps and the normal run view share the layout (per project).

**Comment by kennazilis** [comment] 2020-04-01 17:59
Hello! That is a great feature request. I've added it to our internal ticket tracker and shared it with the rest of the team.

Thank you for the suggestion!

**Comment by cvphelps** [comment] 2020-04-01 18:22
Hi Marcel, it sounds like you're opening the sweep workspace for each individual sweep, which gives you a separate layout. If you'd like to see the same set of columns and graphs but with different sweeps, I'd recommend using the project page and using the filter in the sidebar to switch between different sweeps.

**Comment by ariG23498** [comment] 2020-12-03 06:33
Hey @dreamflasher 
In the past year we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by dreamflasher** [comment] 2020-12-03 06:47
Please reopen

**Comment by abaisero** [comment] 2021-03-30 06:41
Is there any update on this?  I'm in the process of running many different sweeps (training multiple methods on multiple environments), and configuring each sweep workspace/view independently can be a bit overwhelming.

**Comment by vanpelt** [comment] 2021-03-30 15:02
Hey @abaisero you can create a wandb [report](https://docs.wandb.ai/reports) in your project, then easily clone it to change which sweep you're visualizing to use as a templating system.  Would that work for your use case?

**Comment by abaisero** [comment] 2021-04-26 03:52
I suppose that could work for now, but it's still very far from ideal;  cloning a report and updating all the fields to find the correct sweep is still overwhelming and error-prone (especially since you have to refer to the sweeps by its random code)..

**Comment by dreamflasher** [comment] 2021-05-14 09:11
> 
> 
> Hi Marcel, it sounds like you're opening the sweep workspace for each individual sweep, which gives you a separate layout. If you'd like to see the same set of columns and graphs but with different sweeps, I'd recommend for the moment using the project page and using the filter in the sidebar to switch between different sweeps.

I am using Carey's workaround, but for this you need to go to the sweep view first, copy the sweep ID, and then change the filter. Could you add a link the the sweep view to each sweep that just does that? (Link back to the project view, changing the sweep filter to itself)

**Comment by sydholl** [comment] 2024-11-21 21:39
We are closing this issue due to inactivity. If you feel that it merits additional review, please provide a reproduction and add a comment explaining why. Thank you.

**Closed by sydholl** 2024-11-21 21:39 UTC
Labels: ty:feature, c:sweeps
