### ISSUE TITLE
[CLI]: [OSError: [Errno 24] Too many open files] when using sweep

### ISSUE THREAD

**Issue by AllenZ01** [wandb/wandb#7124] opened 2024-03-08 08:04 UTC
### Describe the bug

Hi, I am using sweep to conduct grid search for my model. I created 1 sweep and used 1 agent to conduct runs. In each run I open:

1. a csv file using pandas `pd.read_csv()`
2. a log file using logging `file_handler = logging.FileHandler(...)`

My code (simplifed) is like:

```python
def main(cfg=None):
    with wandb.init(
            name=time_now,
            allow_val_change=True,
            config=cfg
    ):
        raw_data = pd.read_csv(f'{path}/{dataset}.csv')
        file_handler = logging.FileHandler(filename=save_path, mode='w')
        run_model()

if __name__ == '__main__':
    sweep_config = {
        'method': 'grid',
        'name': time_now,
        'metric': {'goal': 'maximize', 'name': 'aucroc'},
        'parameters': {
            'encoder': {'value': 'gcn'},  # gcn
            'hidden': {'values': [16, 32, 64]},
        }
    }
    sweep_id = wandb.sweep(sweep=sweep_config, project='myproject')
    wandb.agent(sweep_id=sweep_id, function=main)
```

The first 900 runs in the sweep were fine. Yet starting from around 922th run, I began to experience Error when opening files:
(1)
```shell
Traceback (most recent call last):
	File "/MyDataProcessin.py", line 154, in load_dataset
		raw_data = pd.read_csv(f'{path}/{dataset}.csv')
	File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
	File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
	File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
	File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
	File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
OSError: [Errno 24] Too many open files: './dataset/german/german.csv'
```
or (2)
```shell
Traceback (most recent call last):
	File "MyNIFTY_german.py", line 76, in init_flogger
		file_handler = logging.FileHandler(filename=save_path, mode='w')
	File "/root/anaconda3/envs/lib/python3.8/logging/__init__.py", line 1147, in __init__
	File "/root/anaconda3/envs/lib/python3.8/logging/__init__.py", line 1176, in _open
OSError: [Errno 24] Too many open files: '/results/2024-03-07-16-23-49/mylog.log'
```
in one run.

I am confused, since I only use 1 agent to conduct runs in 1 sweep. And in each run I only open the csv (and the log) file once. I suppose the agent conduct runs sequentially. Therefore at any point in time there should only be 1 process opening the files. I don't know why the error `[Errno 24] Too many open files` occur.

And also, following these Failed runs (starting from 923th run), there are a large number of crashed runs. I don't know if they have something to do with the above error. 

I've also searched if the same issue had been opened, and got these results:

1. [[CLI]: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)](https://github.com/wandb/wandb/issues/5948)
2. [OSError Too many open files: /tmp/tmphv67gzd0wandb-media](https://github.com/wandb/wandb/issues/2825)
3. [[CLI]: OSError [Errno 24] when running many experiments from same script](https://github.com/wandb/wandb/issues/3329)

Yet their Error occurs when conducting wandb codes, mine occurs when conducting pandas/logging codes, suggesting their cause might not be the same. Therefore I am opening a new issue and hope someone can help.

### Environment

WandB version: 0.16.3

OS: Linux version 5.4.0-150-generic (buildd@bos03-amd64-012) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))

Python version: 3.8

Versions of relevant libraries:

**Comment by fdsig** [comment] 2024-03-11 12:26
Hey @AllenZ01, thank you so much for writing in, sharing other related threads, OS details, wandb version, and a super helpful code snippet.

I can see why this situation seems distinct here; the cause of the crash appears to stem from not closing your .csv or .log files, in addition to other files that are open.

I wonder if you'd object to trying/providing a couple of details here:

- Could you advise if this issue was first observed in version 16.3 of our SDK, or has it occurred with any other versions of wandb?


Regarding getting you back on track here are two potential helpful steps:

> would be able to run `ulimit -n` to get the number of files open at one time and then run `ulimit -n 4096` to set to (4096) or some other higher number.
> I notice here in your code :

```python
raw_data = pd.read_csv(f'{path}/{dataset}.csv')
 file_handler = logging.FileHandler(filename=save_path, mode='w')
 ```
 
>  finally i wonder here if it would work for you to try also giving this a try (slight modification to your existing code):
 
```python
with open(f'{path}/{dataset}.csv', 'r') as file:
    raw_data = pd.read_csv(file)
with logging.FileHandler(filename=save_path, mode='w') as file_handler:
    # Configure your logger here
```

**Comment by fdsig** [comment] 2024-03-14 14:20
Hey @AllenZ01 ,

I am checking in if the above has given you what you require to mitigate hitting open file limits in your compute environment and the additional context to help identify if there is a possible issue in wandb SDK/Client.

Look forward to hearing back from you.

**Comment by thanos-wandb** [comment] 2024-03-18 16:24
Hi @AllenZ01 we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by AllenZ01** [comment] 2024-03-19 06:32
Hi @fdsig @thanos-wandb ,
Thank you so much for your detailed reply. And sorry for my late response, I've been doing experiments to figure out why this problem occurs.
### My Conclusion
My problem [**Hitting open file limits when using W&B Sweep**] is caused by [**not closing the LOG file**].
To be specific, for each run I record the results in a log file using Logging module. Yet I do not close the log files. Therefore it keeps opening files until the number of opened files hit the limit.
### Other Findings
1. We don't need to close the files opened by pandas manully.
I think this line `raw_data = pd.read_csv(f'{path}/{dataset}.csv')` opens and then automatically closes the csv file. 
I conducted a sweep with only `raw_data = pd.read_csv(f'{path}/{dataset}.csv')` in each run. And the sweep went well with no failed or crashed runs.
2. The error message resulted from not closing files might vary.
The exception occurs when attempting to open another file after reaching the limit for opened files. The file attempting to open might be (1) files I open explicitly in my code (e.g. log file or csv file) or (2) files attempting to open implicitly by other modules (e.g. wandb, shutil,...). To be specific, I came across  
```
Traceback (most recent call last):                                                                                                  
  File "/root/anaconda3/envs/Myenv/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 233, in _launch_server             
    _sentry.reraise(e)                                                                                                             
  File "/root/anaconda3/envs/Myenv/lib/python3.8/site-packages/wandb/analytics/sentry.py", line 154, in reraise             
    raise exc.with_traceback(sys.exc_info()[2])                                                                                             
  File "/root/anaconda3/envs/Myenv/lib/python3.8/site-packages/wandb/sdk/service/service.py", line 227, in _launch_server             
    internal_proc = subprocess.Popen(                                                                         
  File "/root/anaconda3/envs/Myenv/lib/python3.8/subprocess.py", line 858, in __init__             
    self._execute_child(args, executable, preexec_fn, close_fds,                                      
  File "/root/anaconda3/envs/Myenv/lib/python3.8/subprocess.py", line 1621, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
```
and
```
Traceback (most recent call last):
  File "/MyDataProcessin.py", line 154, in load_dataset
    raw_data = pd.read_csv(f'{path}/{dataset}.csv')
  File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
  File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
  File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
  File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
  File "/root/anaconda3/envs/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
OSError: [Errno 24] Too many open files: './dataset/german/german.csv'
```
It might be confusing and people may consider this as a wandb / pandas 's problem. But they actually originate from not closing other files in our codes.

### All in all, 
I think my problem is caused by not closing log files when using Logging module. It is not caused by wandb SDK/client, though wandb might show up in the error message. And as for in which version of wandb SDK I first observe this issue, I haven't tried other versions so I can't answer this question. Yet I believe this is not a wandb issue so the question might not need to be answered?
I deleted the Logging part and sweeps went well. But I haven't find a way to close log files explicitly. I tried `file_handler.close()` or `logging.shutdown()` at the end of each run yet neither seems to work. I'll try the `with` statement and see if it works.

Thanks again for your help!

**Comment by thanos-wandb** [comment] 2024-03-22 10:31
Thank you for the update, @AllenZ01 it does sound like it's not caused by `wandb` library per se. Could you try to use `with` statement? This will ensure that resources are properly managed and that files are closed once they are no longer needed. Here’s an example of how to use it with logging FileHandler:

```
import logging

def setup_logger(save_path):
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    
    with logging.FileHandler(filename=save_path, mode='w') as file_handler:
        formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
        file_handler.setFormatter(formatter)
        logger.addHandler(file_handler)
        # logger.info("test log message")
```

I hope this helps! Please let us know if that resolves the issue for you.

**Comment by AllenZ01** [comment] 2024-03-25 05:41
Thanks for the reply @thanos-wandb . I've tried `with` statement, yet it seems that `logging.FileHandler(...)` method is not compatible with `with` statement. 
```
Traceback (most recent call last):
  File "/project/mytest1.py", line 23, in <module>
    setup_logger('./testlog.log')
  File "/project/mytest1.py", line 14, in setup_logger
    with logging.FileHandler(filename=save_path, mode='w') as file_handler:
AttributeError: __enter__
```


I've also tried `removeHandler(...)` method, and **the problem's solved**. Here's the code:
```
def setup_logger(save_path):
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)

    file_handler = logging.FileHandler(filename=save_path, mode='w')
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    file_handler.setFormatter(formatter)
    logger.addHandler(file_handler)

    logger.info("test log message")

    logger.removeHandler(file_handler)
```
I think `removeHandler(...)` method closes the opened file, preventing the program from reaching the limit for opened files.

Thanks again for your help! I'll close this issue since problem's been solved.

**Closed** 2024-03-25 05:41 UTC
Labels: c:sweeps

**Comment by fdsig** [comment] 2024-03-25 10:33
Hey @AllenZ01, Thanks so much for the clarifying detail here -- I will go ahead and close this off for you.
