### ISSUE TITLE
[CLI]: unable to safely convert LangChain Run into W&B Trace due to: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by zacps** [wandb/wandb#5987] opened 2023-08-01 22:13 UTC
### Describe the bug

```
wandb: WARNING Skipping trace saving - unable to safely convert LangChain Run into W&B Trace due to: 'NoneType' object has no attribute 'get'
```

Running [paper-qa](https://github.com/whitead/paper-qa/) (langchain based) with Llama 2 via LlamaCpp.

The run does appear in wandb, but it's possible some information is missing.

### Environment

WandB version: wandb==0.15.7

OS: Ubuntu 20.04.6

Python version: 3.8.10

Versions of relevant libraries: langchain==0.0.234

### Additional Context

Possibly related https://github.com/wandb/wandb/issues/5766

**Comment by umakrishnaswamy** [comment] 2023-08-02 22:13
Hey @zacps, thanks for writing in. I'm working on reproducing this issue and will get back to you shortly

**Comment by umakrishnaswamy** [comment] 2023-08-04 20:19
Hey @zacps, I took a look at the project you linked. Could you provide a toy example of where exactly you're running into this error so I could use this to reproduce the behavior? A code chunk would be incredibly helpful here!

**Comment by umakrishnaswamy** [comment] 2023-08-09 03:21
Hi @zacps ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,

Uma

**Comment by zacps** [comment] 2023-08-09 03:26
Hey, sorry I haven't been able to find time to create a minimally reproducible example yet. I have found that this doesn't occur when using the `OpenAI` langchain llm. I suspect any inference with `llama.cpp` will trigger this, in which case something from the [langchain integration docs](https://python.langchain.com/docs/integrations/llms/llamacpp) will probably trigger it:

```python
import os
os.environ["LANGCHAIN_WANDB_TRACING"] = "true"

from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

template = """Question: {question}

Answer: Let's work this out in a step by step way to be sure we have the right answer."""

prompt = PromptTemplate(template=template, input_variables=["question"])

callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
llm = LlamaCpp(
    model_path="/path/to/a/ggml/model/file",
    input={"temperature": 0.75, "max_length": 2000, "top_p": 1},
    callback_manager=callback_manager,
    verbose=True,
)

prompt = """
Question: A rap battle between Stephen Colbert and John Oliver
"""
llm(prompt)
```

**Comment by umakrishnaswamy** [comment] 2023-08-17 21:42
Hey @zacps thanks for including this workaround. If you see this error again in your workflow, please feel free to write back in and I'd love to explore this further. I was unable to reproduce the error on my end, so if you could send over a code snippet reproducing the error, that would be great!

**Comment by sydholl** [comment] 2023-09-06 22:02
WandB Internal User commented: 
umakrishnaswamy commented: 
Hey @zacps, thanks for writing in. I'm working on reproducing this issue and will get back to you shortly

**Comment by sydholl** [comment] 2023-09-06 22:02
WandB Internal User commented: 
zacps commented: 
Hey, sorry I haven't been able to find time to create a minimally reproducible example yet. I have found that this doesn't occur when using the `OpenAI` langchain llm. I suspect any inference with `llama.cpp` will trigger this, in which case something from the [langchain integration docs](https://python.langchain.com/docs/integrations/llms/llamacpp) will probably trigger it:

```python
import os
os.environ["LANGCHAIN_WANDB_TRACING"] = "true"

from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

template = """Question: {question}

Answer: Let's work this out in a step by step way to be sure we have the right answer."""

prompt = PromptTemplate(template=template, input_variables=["question"])

callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])
llm = LlamaCpp(
    model_path="/path/to/a/ggml/model/file",
    input={"temperature": 0.75, "max_length": 2000, "top_p": 1},
    callback_manager=callback_manager,
    verbose=True,
)

prompt = """
Question: A rap battle between Stephen Colbert and John Oliver
"""
llm(prompt)
```

**Comment by sydholl** [comment] 2023-09-06 22:02
WandB Internal User commented: 
umakrishnaswamy commented: 
Hey @zacps thanks for including this workaround. If you see this error again in your workflow, please feel free to write back in and I'd love to explore this further. I was unable to reproduce the error on my end, so if you could send over a code snippet reproducing the error, that would be great!

**Comment by helinwang** [comment] 2023-10-21 00:01
Here is an example:

wandb==0.15.12
langchain==0.0.319

```import os

# turn on wandb logging for langchain
os.environ["LANGCHAIN_WANDB_TRACING"] = "true"

# optionally set your wandb settings or configs
os.environ["WANDB_PROJECT"] = "langchain-tracing"

os.environ["OPENAI_API_KEY"] = "..."

from langchain.chat_models import ChatOpenAI
from langchain.agents import load_tools, initialize_agent, AgentType

llm = ChatOpenAI(temperature=0)
tools = load_tools(["llm-math"], llm=llm)
math_agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION)

# some sample maths questions
questions = [
    "Find the square root of 5.4.",
    "What is 3 divided by 7.34 raised to the power of pi?",
    "What is the sin of 0.47 radians, divided by the cube root of 27?",
]

for question in questions:
    try:
        # call your Agent as normal
        answer = math_agent.run(question)
        print(answer)
    except Exception as e:
        # any errors will be also logged to Weights & Biases
        print(e)
        pass
```

**Comment by ayulockin** [comment] 2024-04-17 05:37
Hey @zacps, W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the Langchain integration.

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.

**Closed by ayulockin** 2024-04-17 05:37 UTC
Labels: c:integration, c:weave
