### ISSUE TITLE
[CLI]: AMD GPU Monitoring

### ISSUE THREAD

**Issue by kavanase** [wandb/wandb#8072] opened 2024-08-01 20:56 UTC
### Describe the bug

Thanks for developing such a fantastic code!

I noticed an issue when trying to use `wandb` on the Frontier supercomputer, which uses AMD MI250X GPUs (see [here](https://docs.olcf.ornl.gov/systems/frontier_user_guide.html)). `wandb` was not recognising the AMD GPUs, and so the logged system information was not returning any info on GPU usage etc.

This can be quickly checked by looking at the `System Hardware` field in the run overviews on the web app, or in the metadata JSON in `Files` (which has no `gpu_devices` entry):
![image](https://github.com/user-attachments/assets/5ea2e7c3-1f2c-4b18-a7db-2ecd2b5c263f)

Dropping to `wandb==0.16.6`, the GPUs now seem to be recognised:
![image](https://github.com/user-attachments/assets/44cd17e3-ea0b-4372-89f3-c1d5634170ad)

and `gpu_devices` appears in the metadata JSON file.

Looking through the repo history and issues, I think the issue here is related to the catch added by @dmitryduev in #7322. I'm not familiar with GO code so I can't totally tell what the issue is, but it seems that the GO function being used is returning an empty dict in these cases, despite `rocm-smi` working as expected?
I'm not sure if this is due to the format of the `rocm-smi -a --json` output on this system, which gives a dict of `{"card0": {...}, "card1", {...}, ...}`, and so `parse_stats(get_rocm_smi_stats())` doesn't work (returns an empty dict), but `GPUAMDStats.sample()` (which loops over the `"cardX"` subdicts) does – from the python implementation in https://github.com/wandb/wandb/blob/main/wandb/sdk/internal/system/assets/gpu_amd.py. 
I'm not sure, but I think maybe this is the issue here, where this check is assuming a dict formatted without the higher-level `"cardX"` sections?

### Environment

WandB version: 0.17.5

OS: Linux

Python version: 3.12.4

Versions of relevant libraries:

**Comment by kavanase** [comment] 2024-08-01 20:58
Fyi, the `rocm-smi -a --json` output on this system is in the same form as in the AMD GPU python tests [here](https://github.com/wandb/wandb/blob/4436fca4c04003a99a7a91d6e39028db48a0461f/tests/pytest_tests/unit_tests/test_system_metrics/test_gpu_amd.py#L19)

**Comment by ArtsiomWB** [comment] 2024-08-12 21:29
Thank you so much for writing in!

Are you using [wandb's new Go back end for this](https://github.com/wandb/wandb/blob/main/core/README.md) or just the regular wandb python backend? In order to use the new backend you need to specify `wandb.require("core")` before you init your run.

**Comment by kavanase** [comment] 2024-08-13 02:41
No problem! I've been using the regular backend. Should switching to the new one fix this?

**Comment by vitoria-wandb** [comment] 2024-08-15 17:36
Hey Kavanase!

Yeah - we would suggest to use our improved go backend as a lot of the issues that we were having with our previous backed got updated with our new backend. 

Could you please try your setup with the `core` wandb setup? In case you still see this issue with it, please let us know in this thread!

Thank you!  :raised_hands:

**Comment by vitoria-wandb** [comment] 2024-08-19 20:08
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

Thank you! 🙌

**Comment by amorehead** [comment] 2024-09-02 20:26
This issue seems to be happening for me with AMD MI250xs and `wandb==0.17.8`.

**Comment by ArtsiomWB** [comment] 2024-09-04 17:37
Thank you for the follow-up, I've tried this out with an EC2 instance with an AMD GPU and I seem to have a similar behavior. I will go ahead and report it to our engineering team.

**Comment by dmitryduev** [comment] 2024-09-07 00:01
@kavanase: thank you for reporting this! indeed, a stupid bug - should be fixed here https://github.com/wandb/wandb/pull/8299 - we'll include it in the next release next week.

@amorehead: this is really strange! I've just tested #8299 on AMD's cloud with MI250's. The latest wandb version works with core on (wandb.require("core")) and does not with core off (but does work with the #8299 branch). The logic in the go and python code is very similar, so would you mind reporting here what this prints for you:

```
which rocm-smi
rocm-smi -a --json
cat /sys/module/amdgpu/initstate
```

@ArtsiomWB: AWS currently only offers vms with V520 cards that are not supported by ROCm, so that behavior is expected.

**Comment by dmitryduev** [comment] 2024-09-07 00:05
Merged #8299, but reopening until @amorehead's issue is resolved.

**Comment by dmitryduev** [comment] 2024-09-07 00:06
@kavanase: does it work for you with wandb-core on (`wandb.require("core")`)?

**Comment by amorehead** [comment] 2024-09-07 16:34
@dmitryduev, thank you very much for your quick patch for this issue! I can confirm on my end that the ROCm (MI250x) system I am using is now properly having its GPU logs received and displayed in the WandB UI using `wandb==0.17.10.dev1` and with `wandb.require("core")` set. I believe my issue has been resolved.

**Closed** 2024-09-07 18:38 UTC
Labels: a:cli, c:monitor

**Comment by amorehead** [comment] 2024-09-13 21:34
@dmitryduev, to confirm, is this fix included in `wandb==0.18.0`? I ask because I didn't see it listed in 1.18.0's release notes.

**Comment by kptkin** [comment] 2024-09-13 21:59
@amorehead yes all the commits in v0.18.0 will be included in that release. good point about adding this into the release notes. thanks for verifying!

**Comment by amorehead** [comment] 2024-09-25 18:06
@dmitryduev @dmitryduev, I noticed today that with `torch>2.2` and ROCm 6.1/6.2 (e.g., torch 2.3.0 or 2.4.1), `wandb==0.18.0` captures all relevant ROCm GPU metrics except for GPU memory usage (e.g., GPU utilization is reported). Any idea why this might be the case? With ROCm 5.7 and `torch==2.2.0` paired with `wandb==0.18.0`, I was able to see GPU memory being logged.

**Comment by dmitryduev** [comment] 2024-09-25 23:48
@amorehead never mind, this is the fix: https://github.com/wandb/wandb/pull/8493. We'll include it in this weeks release (v 0.18.2). Thanks for the report!
