### ISSUE TITLE
[App]: Images logged to files, but not visible in workspace

### ISSUE THREAD

**Issue by dyunis** [wandb/wandb#4830] opened 2023-01-24 18:45 UTC
### Current Behavior

When logging images, I am not able to view them in the workspace, even though the files are available.

### Expected Behavior

An image panel should pop up automatically (the same code was working previously), and if not, I should be able to add a panel for images.

### Steps To Reproduce

On the python side, I'm logging images with a line like

`wandb.log({'images': wandb.Image(image_grid)}, step=iteration, commit=True)`

for which I encounter the problems described.

See the difference between https://wandb.ai/dyunis/deq_diffusion/runs/zv2phncl?workspace=user-dyunis (working) and https://wandb.ai/dyunis/deq_diffusion/runs/c85nrhug?workspace=user-dyunis (not working)

### Screenshots

Here are the files in the web app for the working run:
<img width="947" alt="working_imgs" src="https://user-images.githubusercontent.com/22402584/214376861-1b890136-785f-46a5-a4f7-249b7ab34340.png">

Here is the workspace with a "Media" section:
<img width="947" alt="working_panel" src="https://user-images.githubusercontent.com/22402584/214377059-447b2f13-c8c9-4fa8-aa89-03aae592c248.png">

And here is the ability to add a new panel with images:
<img width="947" alt="working_panel_add" src="https://user-images.githubusercontent.com/22402584/214377127-3a9c0aad-2527-4f5a-bd8b-b6894f9b1949.png">

Now for a run that does not seem to be displaying correctly, here are the same screenshots, for the media:
<img width="947" alt="broken_imgs" src="https://user-images.githubusercontent.com/22402584/214377247-ccbf2734-e847-4a93-84ae-7845e4fd30c3.png">

For the workspace, now missing a "Media" section by default:
<img width="947" alt="broken_panels" src="https://user-images.githubusercontent.com/22402584/214377353-db60d08a-9d84-4b51-b5eb-c99ce8accd86.png">

And the inability to add a panel with images to the workspace:
<img width="947" alt="broken_panel_add" src="https://user-images.githubusercontent.com/22402584/214377423-6df5a8f0-5fbd-465f-9654-ec88c8319dd7.png">

### Environment

OS: macOS Monterey 12.6.2

Browsers: Safari 15.6.1, Chrome 109.0.5414.87

Version: wandb 0.13.9

### Additional Context

https://github.com/wandb/wandb/issues/3936 seems like the same issue, but for video, but there hasn't been any activity on that for many months.

Thanks for this wonderful software, it's really invaluable in my day-to-day!

**Comment by lesliewandb** [comment] 2023-01-25 01:41
Hi @dyunis I'm so happy that you have liked our product so far! This is a known issue that we have previously ticketed. I have increased the priority on this and I'll let you know if there are any updates here.

**Comment by dyunis** [comment] 2023-01-25 16:02
Hi @lesliewandb, thanks for keeping me in the loop. Is there anything you can say more about the cause of the issue so that I might adjust something on my end?

**Comment by lesliewandb** [comment] 2023-01-26 01:33
I don't have any information about what is causing this, but I talked to the engineer in charge of this ticket and he says that he's currently looking into the cause for this

**Comment by dyunis** [comment] 2023-01-26 17:14
Thanks a lot!

**Comment by MRzNone** [comment] 2023-01-31 16:08
Is there any follow up to this?  I am having the same issue with HTML

**Comment by drscotthawley** [comment] 2023-02-03 04:33
Just a note that I've been interacting with Luis @ wandb support on this same problem.  Will email him back and link to this issue.

**Comment by drscotthawley** [comment] 2023-02-03 14:29
Tried downgrading from v0.13.9  to`wandb==0.12.21` which was the last installation I had where media was appearing as expected, but this did not change the behavior: still no Media.

**Comment by kptkin** [comment] 2023-02-14 03:21
Hi @dyunis @sepsamavi @MRzNone @drscotthawley 

I think I know what is happening, if you look in your logs (`<run-dir>/logs/debug-internal.log`), you might find that we have a warning says:
```
WARNING HandlerThread:89979 [handler.py:handle_request_partial_history():550] Step 0 < 1001. Dropping entry: ...
```
we only allow the steps to be monotonically increasing, hence if you are using something like a resume where you have something like 

```
wandb.log({'images': wandb.Image(image_grid)}, step=iteration, commit=True)
```
and `iteration` is smaller than the last step you resumed from, we by default drop the data. 
If this is indeed the issue, the solution is to either not specify the steps or make sure the steps are monotonically increasing. 

In case this not the issue, if you could provide a repro of how you run your script it would be helpful for me to keep trying to debug this issue.

Looking to hear back from you :)

**Comment by drscotthawley** [comment] 2023-02-14 03:29
@kptkin Not applicable to my case.  Not doing any resuming.  All one run.  My steps will are monotonically increasing.  No "Dropping" in the debug log file.

**Comment by kptkin** [comment] 2023-02-14 03:30
@drscotthawley could you provide a repro? it is very interesting case, i can't currently understand how that would happen.

**Comment by drscotthawley** [comment] 2023-02-14 03:39
@kptkin Please refer to the 14-message email thread with support@wandb Re:  "[Weights & Biases] [Frontend] Media not appearing in Workspace", opened February 1, with responses from Luis and Frida.   All my history, repos, logs, records, run links, etc. are documented there.   

Earlier today Frida suggested a workaround which I have yet to try today. Will do so in a little whiel.

**Comment by kptkin** [comment] 2023-02-14 03:49
@drscotthawley sorry, I didn't realized you were already talking to support. I will ask them for more information.

**Comment by drscotthawley** [comment] 2023-02-14 05:39
Partial success: Current workaround suggested by Frida to encapsulate audio and images inside tables and use `wandb_logger.log_table()`, works for me for everything but my Plotly figures, which are not JSON-serializable.

**Comment by kptkin** [comment] 2023-02-14 06:19
@drscotthawley That's good to hear! If you don't need to interact with the plots, maybe you can convert them into images in the meantime? 

Also, looking into your issue it seems to be related to our PL integration. We are going to look into it more closely and I will update this issue with our findings and fixes!

**Comment by dyunis** [comment] 2023-02-14 15:57
@kptkin Thanks for getting back, like @drscotthawley I don't think this case applies to me (I support resuming in my code, but I am not resuming from anything when I see the bug, and it seems to come and go at random), but I would not like to share the code publicly. Is there a convenient way for me to do so?

**Comment by kptkin** [comment] 2023-02-14 16:42
Hi @dyunis 

1. In case you want to share this information in private you could email support at: [support@wandb.com](mailto:support@wandb.com).
2. In the link to the bad run you provided I see that the run is being resumed, if that wasn't your intent, we could you help you figure out what went wrong.

**Comment by jbloomAus** [comment] 2023-02-14 21:30
> f the step (in the example above `iteration`) is smaller than the last step you resumed from, we are dropping this data from our history log, hence it doesn't appear in the run page. We have a separate logic to save the media files and uploading them to our remote app, so you might see the files regardless.
> 
> If this is indeed the issue, the solution is to either not specify the steps or make sure the steps are monotonically increasing.
> 
> In case this not the issue, if you could provide a repro of how you run your script it would be helpful for me to keep trying to debug this issue.
> 
> Looking to hear back from you :)

@kptkin This is the case for me however changing the step to a monotonically increasing value solved the problem! Thankyou!

**Comment by kptkin** [comment] 2023-02-14 22:11
@jbloomAus Glad to hear it worked for you! Sorry for the inconvenience! We are working on making the indications more obvious and planning to add more fixes in this area in one of the up-coming releases!

**Comment by drscotthawley** [comment] 2023-02-15 19:50
Got a fix for me today after talking to Frida for an hour.  In my case, I'd been passing in a `step=` kwarg to the Pytorch Lightning logger, which had been fine for several months, but apparently recently that was found to produce a conflict (but wasn't throwing any error messages or warnings).  As soon as I removed that kwarg, i.e.  going from 

```python
trainer.logger.experiment.log(log_dict, step=trainer.global_step)
```
to 
```python
trainer.logger.experiment.log(log_dict)
```
...fixed everything; media now appears reliably when using the second version of the code above.   The first version still works sometimes, intermittently, but Frida recommended removing the step altogether.  The logger still logs the step elsewhere, so media still have steps attached to them. 👍

**Comment by dyunis** [comment] 2023-03-09 18:30
@kptkin Sorry to come back to this late, but thanks for your diligence! I checked and it seems I was resuming a run, and in addition, in some cases where I failed to see output, steps were not monotonically increasing. Happy to have a better understanding now 🙂

**Comment by kptkin** [comment] 2023-03-18 19:16
@dyunis Thanks for the the reply. Glad we could help.

**Comment by kptkin** [comment] 2023-03-18 19:16
I will be closing this issue for now, but if someone still have issue and or question, please feel free to re-open this issue again!

**Closed by kptkin** 2023-03-18 19:16 UTC
Labels: app

**Comment by aryamohan23** [comment] 2023-04-01 13:20
Hello, I am facing a similar issue, but the solution suggested by @drscotthawley does nothing for me. 
I am using it in a sweep, and my sweep crashes even though all my images are logged in files.

**Comment by b8raoult** [comment] 2023-04-04 09:06
Having the same issue. I added some tables to my sweep, now the images are not visible anymore: no Media panel in the sweep. When running the core outside a sweep, and get my tables and my images.

**Comment by phtu-cs** [comment] 2023-04-05 23:12
I am facing the same issue when I resume an experiment. The images are successfully uploaded to the Wandb server, but they are not visible in the workspace.

**Comment by kptkin** [comment] 2023-04-12 21:07
> I am facing the same issue when I resume an experiment. The images are successfully uploaded to the Wandb server, but they are not visible in the workspace.

@phtu-cs could you provide additional information, such as debug log, reproduction script, description of how you are doing resume?

**Comment by MBakirWB** [comment] 2023-04-25 22:28
Hi @phtu-cs , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know.

**Comment by junzhin** [comment] 2024-03-30 00:57
This problem still exists

**Comment by kptkin** [comment] 2024-03-30 02:03
@junzhin would you mind providing more information to help us debug this issue? ideally reproduction script and/or debug logs would be very helpful. Also feel free to open a new issue and link to this one, for discoverability.
