### ISSUE TITLE
[CLI]: Can't log from multiple threads

### ISSUE THREAD

**Issue by sparisi** [wandb/wandb#5527] opened 2023-05-10 15:47 UTC
### Describe the bug

My code runs on 2 threads, one for training and one for testing. I need to log training and testing stats at the same time, and I try to do that by calling `wandb.log()` in the training and testing function. However, only the thread that calls first `wandb.log()` will successfully log stats. The other thread log will be ignored.  
If you submit first the training function, you will have always have training stats. 

Here is a MWE. If you try it will always log testing stats, because they are started first. Sometimes (out of luck?) it also logs main stats. Sometimes (veeeery rarely) I get all 3 logs, but incomplete.

I have read somewhere that WandB is not thread safe, but in this case it is not even logging anything and it's behavior is completely non-deterministic. 

```python
import torch
from concurrent.futures import ThreadPoolExecutor
import wandb
import time

def run():
    wandb.init(
        entity='sparisi',
        project='abcd',
        mode='online',
    )

    done_train = False
    done_test = False

    def test():
        nonlocal done_test
        for i in range(100):
            wandb.log({'test': torch.rand(1).item()}, step=i, commit=True)
        done_test = True

    def train():
        nonlocal done_train
        for i in range(100):
            wandb.log({'train': torch.rand(1).item()}, step=i, commit=True)
        done_train = True

    thread_test = ThreadPoolExecutor(1)
    thread_train = ThreadPoolExecutor(1)
    thread_test.submit(test)
    thread_train.submit(train)

    for i in range(100):
        wandb.log({'main': torch.rand(1).item()}, step=i, commit=True)

    while not done_test and not done_train:
        time.sleep(0.1)

    wandb.finish()


if __name__ == '__main__':
    run()

```

### Environment

WandB version: 0.15.2

OS: Windows

Python version: 3.10

**Comment by nate-wandb** [comment] 2023-05-15 14:03
Hi @sparisi, are you looking for each of the threads to log to the same run or would you want each thread to spawn its own run?

**Comment by sparisi** [comment] 2023-05-15 15:22
> Hi @sparisi, are you looking for each of the threads to log to the same run or would you want each thread to spawn its own run?

Same run. I think the problem is that the step argument is not monotonically increasing.

**Comment by nate-wandb** [comment] 2023-05-18 23:43
@sparisi I see, yes any log calls made to a step < the current step would not get ingested by the server which would explain the somewhat non-deterministic nature of what you are seeing. 

I think for your use case though, it would make sense to use two different `wandb.run`'s and give them a group so they are associated with each other in the UI.

**Comment by sparisi** [comment] 2023-05-19 17:00
@nate-wandb The problem is that I need to use the same ID because I may need to resume my run later. And I cannot use two `wandb.run` with the same id, right? I tried and I get the error 

```
FileExistsError: [Errno 17] File exists: '<path>\\wandb\\run-20230519_105638-EnvX-20230519-105631\\run-EnvX-20230519-105631.wandb'
```

The is here `EnvX-<timestamp>` but for sweeps it depends on hyperparameters.

**Comment by nate-wandb** [comment] 2023-05-24 18:12
@sparisi I see. One workaround could be to use the [define metric workflow here](https://docs.wandb.ai/guides/technical-faq/metrics-and-performance#can-i-log-metrics-on-two-different-time-scales-for-example-i-want-to-log-training-accuracy-per-batch-and-validation-accuracy-per-epoch) and then don't add the step argument to `wandb.log` but rather track the step as another metric yourself. The UI will plot the actual metric against your custom step metric if you do this. 

Do you think this could be a possible solution?

**Comment by sparisi** [comment] 2023-05-24 18:57
@nate-wandb Yes this works, thanks! It makes a plot for my additional metric ("Steps") which I have to hide every time, though, and sometimes it doesn't set "Steps" as default metric, but it's not a big deal.

**Comment by nate-wandb** [comment] 2023-06-05 17:30
Great! We have a feature request currently pending to be able to hide the defined metrics from `wandb` which should help. 

Is it non-deterministic when "Steps" will not be set as the x-axis? Do you have a minimal repro I could test with?

**Comment by sparisi** [comment] 2023-06-07 20:10
@nate-wandb Do you mean a minimal example with two different time steps? 
This is my original example with some `time.sleep` to make it kinda deterministic. The `train` thread will log before the `test` and on the server only `train = i ** 2` will be logged. The `test` plot will be empty.

```python
from concurrent.futures import ThreadPoolExecutor
import wandb
import time

def run():
    wandb.init(
        project='abcd',
        mode='online',
    )

    done_train = False
    done_test = False

    def test():
        nonlocal done_test
        for i in range(100):
            time.sleep(0.2)
            wandb.log({'test': i}, step=i)
        done_test = True

    def train():
        nonlocal done_train
        for i in range(100):
            wandb.log({'train': i ** 2}, step=i)
        done_train = True

    thread_test = ThreadPoolExecutor(1)
    thread_train = ThreadPoolExecutor(1)
    thread_test.submit(test)
    thread_train.submit(train)

    while not done_test and not done_train:
        time.sleep(0.1)

    wandb.finish()


if __name__ == '__main__':
    run()

```

**Comment by nate-wandb** [comment] 2023-06-09 18:57
Hi @sparisi, sorry I was referring to this:

> sometimes it doesn't set "Steps" as default metric

Is this something that is happening consistently or does this seem to non-deterministically happen?

**Comment by nate-wandb** [comment] 2023-06-13 15:16
HI @sparisi, I just wanted to follow up and see if you think the define metric workflow is an acceptable workaround or if there was anything else I can help with around this?

**Comment by sparisi** [comment] 2023-06-14 15:20
Hi @nate-wandb, unfortunatley I cannot reproduce it with some code. If I run something locally everything works fine, but all runs submitted as slurm jobs don't show my custom metric "steps" as default x-axis, and I need to manually set it everytime in the plots.

**Comment by nate-wandb** [comment] 2023-06-15 14:16
@sparisi Are the slurm jobs using the same version of W&B as when you test locally?

**Comment by sparisi** [comment] 2023-06-15 16:11
@nate-wandb yes, the latest.

**Comment by nate-wandb** [comment] 2023-06-20 19:20
@sparisi, interesting. If this is a blocker, could you possibly create a minimal reproduction of the issue that uses SLURM so that we can try to get a fix on this?

**Comment by nate-wandb** [comment] 2023-06-22 21:09
Hi @sparisi, I'll close this for now since the define metric flow solves the original issue but feel free to open another issue if you want us to investigate the default x-axis issue with Slurm. Thank you!

**Closed by nate-wandb** 2023-06-22 21:09 UTC
Labels: cli
